// Code generated by go-swagger; DO NOT EDIT.

package namespace

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV1NamespaceLogParams creates a new GetAPIV1NamespaceLogParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1NamespaceLogParams() *GetAPIV1NamespaceLogParams {
	return &GetAPIV1NamespaceLogParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1NamespaceLogParamsWithTimeout creates a new GetAPIV1NamespaceLogParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1NamespaceLogParamsWithTimeout(timeout time.Duration) *GetAPIV1NamespaceLogParams {
	return &GetAPIV1NamespaceLogParams{
		timeout: timeout,
	}
}

// NewGetAPIV1NamespaceLogParamsWithContext creates a new GetAPIV1NamespaceLogParams object
// with the ability to set a context for a request.
func NewGetAPIV1NamespaceLogParamsWithContext(ctx context.Context) *GetAPIV1NamespaceLogParams {
	return &GetAPIV1NamespaceLogParams{
		Context: ctx,
	}
}

// NewGetAPIV1NamespaceLogParamsWithHTTPClient creates a new GetAPIV1NamespaceLogParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1NamespaceLogParamsWithHTTPClient(client *http.Client) *GetAPIV1NamespaceLogParams {
	return &GetAPIV1NamespaceLogParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1NamespaceLogParams contains all the parameters to send to the API endpoint

	for the get API v1 namespace log operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1NamespaceLogParams struct {

	/* LogID.

	   log id
	*/
	LogID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 namespace log params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1NamespaceLogParams) WithDefaults() *GetAPIV1NamespaceLogParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 namespace log params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1NamespaceLogParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 namespace log params
func (o *GetAPIV1NamespaceLogParams) WithTimeout(timeout time.Duration) *GetAPIV1NamespaceLogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 namespace log params
func (o *GetAPIV1NamespaceLogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 namespace log params
func (o *GetAPIV1NamespaceLogParams) WithContext(ctx context.Context) *GetAPIV1NamespaceLogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 namespace log params
func (o *GetAPIV1NamespaceLogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 namespace log params
func (o *GetAPIV1NamespaceLogParams) WithHTTPClient(client *http.Client) *GetAPIV1NamespaceLogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 namespace log params
func (o *GetAPIV1NamespaceLogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLogID adds the logID to the get API v1 namespace log params
func (o *GetAPIV1NamespaceLogParams) WithLogID(logID int64) *GetAPIV1NamespaceLogParams {
	o.SetLogID(logID)
	return o
}

// SetLogID adds the logId to the get API v1 namespace log params
func (o *GetAPIV1NamespaceLogParams) SetLogID(logID int64) {
	o.LogID = logID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1NamespaceLogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param log_id
	qrLogID := o.LogID
	qLogID := swag.FormatInt64(qrLogID)
	if qLogID != "" {

		if err := r.SetQueryParam("log_id", qLogID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
