// Code generated by go-swagger; DO NOT EDIT.

package namespace

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.corp.mail.ru/ai/streamflow/backend/cplane/tests/private/models"
)

// GetAPIV1NamespaceConfigsReader is a Reader for the GetAPIV1NamespaceConfigs structure.
type GetAPIV1NamespaceConfigsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1NamespaceConfigsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1NamespaceConfigsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1NamespaceConfigsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAPIV1NamespaceConfigsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAPIV1NamespaceConfigsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV1NamespaceConfigsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1NamespaceConfigsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/namespace/configs] GetAPIV1NamespaceConfigs", response, response.Code())
	}
}

// NewGetAPIV1NamespaceConfigsOK creates a GetAPIV1NamespaceConfigsOK with default headers values
func NewGetAPIV1NamespaceConfigsOK() *GetAPIV1NamespaceConfigsOK {
	return &GetAPIV1NamespaceConfigsOK{}
}

/*
GetAPIV1NamespaceConfigsOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1NamespaceConfigsOK struct {
	Payload *models.ResponsesListNamespaceConfigsResponse
}

// IsSuccess returns true when this get Api v1 namespace configs o k response has a 2xx status code
func (o *GetAPIV1NamespaceConfigsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 namespace configs o k response has a 3xx status code
func (o *GetAPIV1NamespaceConfigsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 namespace configs o k response has a 4xx status code
func (o *GetAPIV1NamespaceConfigsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 namespace configs o k response has a 5xx status code
func (o *GetAPIV1NamespaceConfigsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 namespace configs o k response a status code equal to that given
func (o *GetAPIV1NamespaceConfigsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 namespace configs o k response
func (o *GetAPIV1NamespaceConfigsOK) Code() int {
	return 200
}

func (o *GetAPIV1NamespaceConfigsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/namespace/configs][%d] getApiV1NamespaceConfigsOK %s", 200, payload)
}

func (o *GetAPIV1NamespaceConfigsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/namespace/configs][%d] getApiV1NamespaceConfigsOK %s", 200, payload)
}

func (o *GetAPIV1NamespaceConfigsOK) GetPayload() *models.ResponsesListNamespaceConfigsResponse {
	return o.Payload
}

func (o *GetAPIV1NamespaceConfigsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesListNamespaceConfigsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1NamespaceConfigsBadRequest creates a GetAPIV1NamespaceConfigsBadRequest with default headers values
func NewGetAPIV1NamespaceConfigsBadRequest() *GetAPIV1NamespaceConfigsBadRequest {
	return &GetAPIV1NamespaceConfigsBadRequest{}
}

/*
GetAPIV1NamespaceConfigsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAPIV1NamespaceConfigsBadRequest struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 namespace configs bad request response has a 2xx status code
func (o *GetAPIV1NamespaceConfigsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 namespace configs bad request response has a 3xx status code
func (o *GetAPIV1NamespaceConfigsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 namespace configs bad request response has a 4xx status code
func (o *GetAPIV1NamespaceConfigsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 namespace configs bad request response has a 5xx status code
func (o *GetAPIV1NamespaceConfigsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 namespace configs bad request response a status code equal to that given
func (o *GetAPIV1NamespaceConfigsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v1 namespace configs bad request response
func (o *GetAPIV1NamespaceConfigsBadRequest) Code() int {
	return 400
}

func (o *GetAPIV1NamespaceConfigsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/namespace/configs][%d] getApiV1NamespaceConfigsBadRequest %s", 400, payload)
}

func (o *GetAPIV1NamespaceConfigsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/namespace/configs][%d] getApiV1NamespaceConfigsBadRequest %s", 400, payload)
}

func (o *GetAPIV1NamespaceConfigsBadRequest) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1NamespaceConfigsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1NamespaceConfigsUnauthorized creates a GetAPIV1NamespaceConfigsUnauthorized with default headers values
func NewGetAPIV1NamespaceConfigsUnauthorized() *GetAPIV1NamespaceConfigsUnauthorized {
	return &GetAPIV1NamespaceConfigsUnauthorized{}
}

/*
GetAPIV1NamespaceConfigsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAPIV1NamespaceConfigsUnauthorized struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 namespace configs unauthorized response has a 2xx status code
func (o *GetAPIV1NamespaceConfigsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 namespace configs unauthorized response has a 3xx status code
func (o *GetAPIV1NamespaceConfigsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 namespace configs unauthorized response has a 4xx status code
func (o *GetAPIV1NamespaceConfigsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 namespace configs unauthorized response has a 5xx status code
func (o *GetAPIV1NamespaceConfigsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 namespace configs unauthorized response a status code equal to that given
func (o *GetAPIV1NamespaceConfigsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v1 namespace configs unauthorized response
func (o *GetAPIV1NamespaceConfigsUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV1NamespaceConfigsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/namespace/configs][%d] getApiV1NamespaceConfigsUnauthorized %s", 401, payload)
}

func (o *GetAPIV1NamespaceConfigsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/namespace/configs][%d] getApiV1NamespaceConfigsUnauthorized %s", 401, payload)
}

func (o *GetAPIV1NamespaceConfigsUnauthorized) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1NamespaceConfigsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1NamespaceConfigsForbidden creates a GetAPIV1NamespaceConfigsForbidden with default headers values
func NewGetAPIV1NamespaceConfigsForbidden() *GetAPIV1NamespaceConfigsForbidden {
	return &GetAPIV1NamespaceConfigsForbidden{}
}

/*
GetAPIV1NamespaceConfigsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAPIV1NamespaceConfigsForbidden struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 namespace configs forbidden response has a 2xx status code
func (o *GetAPIV1NamespaceConfigsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 namespace configs forbidden response has a 3xx status code
func (o *GetAPIV1NamespaceConfigsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 namespace configs forbidden response has a 4xx status code
func (o *GetAPIV1NamespaceConfigsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 namespace configs forbidden response has a 5xx status code
func (o *GetAPIV1NamespaceConfigsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 namespace configs forbidden response a status code equal to that given
func (o *GetAPIV1NamespaceConfigsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v1 namespace configs forbidden response
func (o *GetAPIV1NamespaceConfigsForbidden) Code() int {
	return 403
}

func (o *GetAPIV1NamespaceConfigsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/namespace/configs][%d] getApiV1NamespaceConfigsForbidden %s", 403, payload)
}

func (o *GetAPIV1NamespaceConfigsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/namespace/configs][%d] getApiV1NamespaceConfigsForbidden %s", 403, payload)
}

func (o *GetAPIV1NamespaceConfigsForbidden) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1NamespaceConfigsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1NamespaceConfigsNotFound creates a GetAPIV1NamespaceConfigsNotFound with default headers values
func NewGetAPIV1NamespaceConfigsNotFound() *GetAPIV1NamespaceConfigsNotFound {
	return &GetAPIV1NamespaceConfigsNotFound{}
}

/*
GetAPIV1NamespaceConfigsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAPIV1NamespaceConfigsNotFound struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 namespace configs not found response has a 2xx status code
func (o *GetAPIV1NamespaceConfigsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 namespace configs not found response has a 3xx status code
func (o *GetAPIV1NamespaceConfigsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 namespace configs not found response has a 4xx status code
func (o *GetAPIV1NamespaceConfigsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 namespace configs not found response has a 5xx status code
func (o *GetAPIV1NamespaceConfigsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 namespace configs not found response a status code equal to that given
func (o *GetAPIV1NamespaceConfigsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v1 namespace configs not found response
func (o *GetAPIV1NamespaceConfigsNotFound) Code() int {
	return 404
}

func (o *GetAPIV1NamespaceConfigsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/namespace/configs][%d] getApiV1NamespaceConfigsNotFound %s", 404, payload)
}

func (o *GetAPIV1NamespaceConfigsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/namespace/configs][%d] getApiV1NamespaceConfigsNotFound %s", 404, payload)
}

func (o *GetAPIV1NamespaceConfigsNotFound) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1NamespaceConfigsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1NamespaceConfigsInternalServerError creates a GetAPIV1NamespaceConfigsInternalServerError with default headers values
func NewGetAPIV1NamespaceConfigsInternalServerError() *GetAPIV1NamespaceConfigsInternalServerError {
	return &GetAPIV1NamespaceConfigsInternalServerError{}
}

/*
GetAPIV1NamespaceConfigsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetAPIV1NamespaceConfigsInternalServerError struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 namespace configs internal server error response has a 2xx status code
func (o *GetAPIV1NamespaceConfigsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 namespace configs internal server error response has a 3xx status code
func (o *GetAPIV1NamespaceConfigsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 namespace configs internal server error response has a 4xx status code
func (o *GetAPIV1NamespaceConfigsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 namespace configs internal server error response has a 5xx status code
func (o *GetAPIV1NamespaceConfigsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 namespace configs internal server error response a status code equal to that given
func (o *GetAPIV1NamespaceConfigsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 namespace configs internal server error response
func (o *GetAPIV1NamespaceConfigsInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1NamespaceConfigsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/namespace/configs][%d] getApiV1NamespaceConfigsInternalServerError %s", 500, payload)
}

func (o *GetAPIV1NamespaceConfigsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/namespace/configs][%d] getApiV1NamespaceConfigsInternalServerError %s", 500, payload)
}

func (o *GetAPIV1NamespaceConfigsInternalServerError) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1NamespaceConfigsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
