// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new app API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new app API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new app API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for app API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteAPIV1AppBanner(params *DeleteAPIV1AppBannerParams, opts ...ClientOption) (*DeleteAPIV1AppBannerOK, error)

	DeleteAPIV1AppUpdate(params *DeleteAPIV1AppUpdateParams, opts ...ClientOption) (*DeleteAPIV1AppUpdateOK, error)

	GetAPIV1AppAbout(params *GetAPIV1AppAboutParams, opts ...ClientOption) (*GetAPIV1AppAboutOK, error)

	GetAPIV1AppBanner(params *GetAPIV1AppBannerParams, opts ...ClientOption) (*GetAPIV1AppBannerOK, error)

	GetAPIV1AppBannerTypes(params *GetAPIV1AppBannerTypesParams, opts ...ClientOption) (*GetAPIV1AppBannerTypesOK, error)

	GetAPIV1AppBanners(params *GetAPIV1AppBannersParams, opts ...ClientOption) (*GetAPIV1AppBannersOK, error)

	GetAPIV1AppBannersCurrent(params *GetAPIV1AppBannersCurrentParams, opts ...ClientOption) (*GetAPIV1AppBannersCurrentOK, error)

	GetAPIV1AppIsAdmin(params *GetAPIV1AppIsAdminParams, opts ...ClientOption) (*GetAPIV1AppIsAdminOK, error)

	GetAPIV1AppUpcoming(params *GetAPIV1AppUpcomingParams, opts ...ClientOption) (*GetAPIV1AppUpcomingOK, error)

	GetAPIV1AppUpdate(params *GetAPIV1AppUpdateParams, opts ...ClientOption) (*GetAPIV1AppUpdateOK, error)

	GetAPIV1AppUpdates(params *GetAPIV1AppUpdatesParams, opts ...ClientOption) (*GetAPIV1AppUpdatesOK, error)

	PostAPIV1AppBanner(params *PostAPIV1AppBannerParams, opts ...ClientOption) (*PostAPIV1AppBannerOK, error)

	PostAPIV1AppUpdate(params *PostAPIV1AppUpdateParams, opts ...ClientOption) (*PostAPIV1AppUpdateOK, error)

	PutAPIV1AppAbout(params *PutAPIV1AppAboutParams, opts ...ClientOption) (*PutAPIV1AppAboutOK, error)

	PutAPIV1AppBanner(params *PutAPIV1AppBannerParams, opts ...ClientOption) (*PutAPIV1AppBannerOK, error)

	PutAPIV1AppUpcoming(params *PutAPIV1AppUpcomingParams, opts ...ClientOption) (*PutAPIV1AppUpcomingOK, error)

	PutAPIV1AppUpdate(params *PutAPIV1AppUpdateParams, opts ...ClientOption) (*PutAPIV1AppUpdateOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteAPIV1AppBanner deletes app banner
*/
func (a *Client) DeleteAPIV1AppBanner(params *DeleteAPIV1AppBannerParams, opts ...ClientOption) (*DeleteAPIV1AppBannerOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteAPIV1AppBannerParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteAPIV1AppBanner",
		Method:             "DELETE",
		PathPattern:        "/api/v1/app/banner",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteAPIV1AppBannerReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteAPIV1AppBannerOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteAPIV1AppBanner: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteAPIV1AppUpdate deletes app update
*/
func (a *Client) DeleteAPIV1AppUpdate(params *DeleteAPIV1AppUpdateParams, opts ...ClientOption) (*DeleteAPIV1AppUpdateOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteAPIV1AppUpdateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteAPIV1AppUpdate",
		Method:             "DELETE",
		PathPattern:        "/api/v1/app/update",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteAPIV1AppUpdateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteAPIV1AppUpdateOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteAPIV1AppUpdate: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1AppAbout gets app about content
*/
func (a *Client) GetAPIV1AppAbout(params *GetAPIV1AppAboutParams, opts ...ClientOption) (*GetAPIV1AppAboutOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1AppAboutParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1AppAbout",
		Method:             "GET",
		PathPattern:        "/api/v1/app/about",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1AppAboutReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1AppAboutOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1AppAbout: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1AppBanner gets app banner info
*/
func (a *Client) GetAPIV1AppBanner(params *GetAPIV1AppBannerParams, opts ...ClientOption) (*GetAPIV1AppBannerOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1AppBannerParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1AppBanner",
		Method:             "GET",
		PathPattern:        "/api/v1/app/banner",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1AppBannerReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1AppBannerOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1AppBanner: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1AppBannerTypes gets app banner types
*/
func (a *Client) GetAPIV1AppBannerTypes(params *GetAPIV1AppBannerTypesParams, opts ...ClientOption) (*GetAPIV1AppBannerTypesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1AppBannerTypesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1AppBannerTypes",
		Method:             "GET",
		PathPattern:        "/api/v1/app/banner/types",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1AppBannerTypesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1AppBannerTypesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1AppBannerTypes: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1AppBanners lists app banners
*/
func (a *Client) GetAPIV1AppBanners(params *GetAPIV1AppBannersParams, opts ...ClientOption) (*GetAPIV1AppBannersOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1AppBannersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1AppBanners",
		Method:             "GET",
		PathPattern:        "/api/v1/app/banners",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1AppBannersReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1AppBannersOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1AppBanners: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1AppBannersCurrent gets current active app banner
*/
func (a *Client) GetAPIV1AppBannersCurrent(params *GetAPIV1AppBannersCurrentParams, opts ...ClientOption) (*GetAPIV1AppBannersCurrentOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1AppBannersCurrentParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1AppBannersCurrent",
		Method:             "GET",
		PathPattern:        "/api/v1/app/banners/current",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1AppBannersCurrentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1AppBannersCurrentOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1AppBannersCurrent: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1AppIsAdmin checks if user is admin
*/
func (a *Client) GetAPIV1AppIsAdmin(params *GetAPIV1AppIsAdminParams, opts ...ClientOption) (*GetAPIV1AppIsAdminOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1AppIsAdminParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1AppIsAdmin",
		Method:             "GET",
		PathPattern:        "/api/v1/app/is-admin",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1AppIsAdminReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1AppIsAdminOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1AppIsAdmin: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1AppUpcoming gets app upcoming content
*/
func (a *Client) GetAPIV1AppUpcoming(params *GetAPIV1AppUpcomingParams, opts ...ClientOption) (*GetAPIV1AppUpcomingOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1AppUpcomingParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1AppUpcoming",
		Method:             "GET",
		PathPattern:        "/api/v1/app/upcoming",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1AppUpcomingReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1AppUpcomingOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1AppUpcoming: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1AppUpdate gets app update info
*/
func (a *Client) GetAPIV1AppUpdate(params *GetAPIV1AppUpdateParams, opts ...ClientOption) (*GetAPIV1AppUpdateOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1AppUpdateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1AppUpdate",
		Method:             "GET",
		PathPattern:        "/api/v1/app/update",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1AppUpdateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1AppUpdateOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1AppUpdate: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1AppUpdates lists all app updates
*/
func (a *Client) GetAPIV1AppUpdates(params *GetAPIV1AppUpdatesParams, opts ...ClientOption) (*GetAPIV1AppUpdatesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1AppUpdatesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1AppUpdates",
		Method:             "GET",
		PathPattern:        "/api/v1/app/updates",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1AppUpdatesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1AppUpdatesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1AppUpdates: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIV1AppBanner creates app banner
*/
func (a *Client) PostAPIV1AppBanner(params *PostAPIV1AppBannerParams, opts ...ClientOption) (*PostAPIV1AppBannerOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1AppBannerParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1AppBanner",
		Method:             "POST",
		PathPattern:        "/api/v1/app/banner",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1AppBannerReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1AppBannerOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1AppBanner: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIV1AppUpdate creates app update
*/
func (a *Client) PostAPIV1AppUpdate(params *PostAPIV1AppUpdateParams, opts ...ClientOption) (*PostAPIV1AppUpdateOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1AppUpdateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1AppUpdate",
		Method:             "POST",
		PathPattern:        "/api/v1/app/update",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1AppUpdateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1AppUpdateOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1AppUpdate: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutAPIV1AppAbout updates app about content
*/
func (a *Client) PutAPIV1AppAbout(params *PutAPIV1AppAboutParams, opts ...ClientOption) (*PutAPIV1AppAboutOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutAPIV1AppAboutParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutAPIV1AppAbout",
		Method:             "PUT",
		PathPattern:        "/api/v1/app/about",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutAPIV1AppAboutReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutAPIV1AppAboutOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutAPIV1AppAbout: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutAPIV1AppBanner updates app banner
*/
func (a *Client) PutAPIV1AppBanner(params *PutAPIV1AppBannerParams, opts ...ClientOption) (*PutAPIV1AppBannerOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutAPIV1AppBannerParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutAPIV1AppBanner",
		Method:             "PUT",
		PathPattern:        "/api/v1/app/banner",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutAPIV1AppBannerReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutAPIV1AppBannerOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutAPIV1AppBanner: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutAPIV1AppUpcoming updates app upcoming content
*/
func (a *Client) PutAPIV1AppUpcoming(params *PutAPIV1AppUpcomingParams, opts ...ClientOption) (*PutAPIV1AppUpcomingOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutAPIV1AppUpcomingParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutAPIV1AppUpcoming",
		Method:             "PUT",
		PathPattern:        "/api/v1/app/upcoming",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutAPIV1AppUpcomingReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutAPIV1AppUpcomingOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutAPIV1AppUpcoming: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutAPIV1AppUpdate updates app update
*/
func (a *Client) PutAPIV1AppUpdate(params *PutAPIV1AppUpdateParams, opts ...ClientOption) (*PutAPIV1AppUpdateOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutAPIV1AppUpdateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutAPIV1AppUpdate",
		Method:             "PUT",
		PathPattern:        "/api/v1/app/update",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutAPIV1AppUpdateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutAPIV1AppUpdateOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutAPIV1AppUpdate: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
