// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV1AppUpdateParams creates a new GetAPIV1AppUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1AppUpdateParams() *GetAPIV1AppUpdateParams {
	return &GetAPIV1AppUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1AppUpdateParamsWithTimeout creates a new GetAPIV1AppUpdateParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1AppUpdateParamsWithTimeout(timeout time.Duration) *GetAPIV1AppUpdateParams {
	return &GetAPIV1AppUpdateParams{
		timeout: timeout,
	}
}

// NewGetAPIV1AppUpdateParamsWithContext creates a new GetAPIV1AppUpdateParams object
// with the ability to set a context for a request.
func NewGetAPIV1AppUpdateParamsWithContext(ctx context.Context) *GetAPIV1AppUpdateParams {
	return &GetAPIV1AppUpdateParams{
		Context: ctx,
	}
}

// NewGetAPIV1AppUpdateParamsWithHTTPClient creates a new GetAPIV1AppUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1AppUpdateParamsWithHTTPClient(client *http.Client) *GetAPIV1AppUpdateParams {
	return &GetAPIV1AppUpdateParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1AppUpdateParams contains all the parameters to send to the API endpoint

	for the get API v1 app update operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1AppUpdateParams struct {

	/* UpdateID.

	   update_id
	*/
	UpdateID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 app update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1AppUpdateParams) WithDefaults() *GetAPIV1AppUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 app update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1AppUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 app update params
func (o *GetAPIV1AppUpdateParams) WithTimeout(timeout time.Duration) *GetAPIV1AppUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 app update params
func (o *GetAPIV1AppUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 app update params
func (o *GetAPIV1AppUpdateParams) WithContext(ctx context.Context) *GetAPIV1AppUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 app update params
func (o *GetAPIV1AppUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 app update params
func (o *GetAPIV1AppUpdateParams) WithHTTPClient(client *http.Client) *GetAPIV1AppUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 app update params
func (o *GetAPIV1AppUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUpdateID adds the updateID to the get API v1 app update params
func (o *GetAPIV1AppUpdateParams) WithUpdateID(updateID int64) *GetAPIV1AppUpdateParams {
	o.SetUpdateID(updateID)
	return o
}

// SetUpdateID adds the updateId to the get API v1 app update params
func (o *GetAPIV1AppUpdateParams) SetUpdateID(updateID int64) {
	o.UpdateID = updateID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1AppUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param update_id
	qrUpdateID := o.UpdateID
	qUpdateID := swag.FormatInt64(qrUpdateID)
	if qUpdateID != "" {

		if err := r.SetQueryParam("update_id", qUpdateID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
