// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_banner.sql

package core

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateAllBannersExcept = `-- name: DeactivateAllBannersExcept :exec
UPDATE t_app_banner SET active = false WHERE id != $1
`

func (q *Queries) DeactivateAllBannersExcept(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deactivateAllBannersExcept, id)
	return err
}

const deleteAppBanner = `-- name: DeleteAppBanner :exec
DELETE FROM t_app_banner WHERE id = $1
`

func (q *Queries) DeleteAppBanner(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAppBanner, id)
	return err
}

const insertAppBanner = `-- name: InsertAppBanner :one
INSERT INTO t_app_banner (title, message, active, color, color_dark, type, starts, ends)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id
`

type InsertAppBannerParams struct {
	Title     string
	Message   string
	Active    bool
	Color     string
	ColorDark string
	Type      string
	Starts    pgtype.Timestamp
	Ends      pgtype.Timestamp
}

func (q *Queries) InsertAppBanner(ctx context.Context, arg InsertAppBannerParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertAppBanner,
		arg.Title,
		arg.Message,
		arg.Active,
		arg.Color,
		arg.ColorDark,
		arg.Type,
		arg.Starts,
		arg.Ends,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const isExistsActiveBlockBanners = `-- name: IsExistsActiveBlockBanners :one
SELECT COUNT(*) > 0 FROM t_app_banner
WHERE active = true AND type = 'release_block'
  AND (starts IS NULL OR starts <= NOW())
  AND (ends IS NULL OR ends >= NOW())
`

func (q *Queries) IsExistsActiveBlockBanners(ctx context.Context) (*bool, error) {
	row := q.db.QueryRow(ctx, isExistsActiveBlockBanners)
	var column_1 *bool
	err := row.Scan(&column_1)
	return column_1, err
}

const selectActiveAppBanner = `-- name: SelectActiveAppBanner :one
SELECT id, type, title, message, active, color, created_at, updated_at, color_dark, starts, ends FROM t_app_banner
WHERE active = true
  AND (starts IS NULL OR starts <= NOW())
  AND (ends IS NULL OR ends >= NOW())
ORDER BY updated_at DESC LIMIT 1
`

func (q *Queries) SelectActiveAppBanner(ctx context.Context) (TAppBanner, error) {
	row := q.db.QueryRow(ctx, selectActiveAppBanner)
	var i TAppBanner
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Active,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ColorDark,
		&i.Starts,
		&i.Ends,
	)
	return i, err
}

const selectAppBanner = `-- name: SelectAppBanner :one
SELECT id, type, title, message, active, color, created_at, updated_at, color_dark, starts, ends FROM t_app_banner WHERE id = $1
`

func (q *Queries) SelectAppBanner(ctx context.Context, id int32) (TAppBanner, error) {
	row := q.db.QueryRow(ctx, selectAppBanner, id)
	var i TAppBanner
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Active,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ColorDark,
		&i.Starts,
		&i.Ends,
	)
	return i, err
}

const selectAppBanners = `-- name: SelectAppBanners :many
SELECT id, type, title, message, active, color, created_at, updated_at, color_dark, starts, ends FROM t_app_banner ORDER BY created_at DESC
`

func (q *Queries) SelectAppBanners(ctx context.Context) ([]TAppBanner, error) {
	rows, err := q.db.Query(ctx, selectAppBanners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TAppBanner
	for rows.Next() {
		var i TAppBanner
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Active,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ColorDark,
			&i.Starts,
			&i.Ends,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectCurrentAppBanner = `-- name: SelectCurrentAppBanner :one
SELECT id, type, title, message, active, color, created_at, updated_at, color_dark, starts, ends FROM t_app_banner 
WHERE active = true 
  AND (starts IS NULL OR starts <= NOW())
  AND (ends IS NULL OR ends >= NOW())
ORDER BY updated_at DESC 
LIMIT 1
`

func (q *Queries) SelectCurrentAppBanner(ctx context.Context) (TAppBanner, error) {
	row := q.db.QueryRow(ctx, selectCurrentAppBanner)
	var i TAppBanner
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Active,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ColorDark,
		&i.Starts,
		&i.Ends,
	)
	return i, err
}

const updateAppBanner = `-- name: UpdateAppBanner :one
UPDATE t_app_banner
SET
    title = CASE WHEN $2::text != '' THEN $2::text ELSE title END,
    message = CASE WHEN $3::text != '' THEN $3::text ELSE message END,
    active = CASE WHEN $4::bool IS NOT NULL THEN $4 ELSE active END,
    color = CASE WHEN $5::text != '' THEN $5::text ELSE color END,
    color_dark = CASE WHEN $6::text != '' THEN $6::text ELSE color_dark END,
    type = COALESCE($7, type),
    starts = COALESCE($8, starts),
    ends = COALESCE($9, ends),
    updated_at = NOW()
WHERE id = $1 RETURNING id, type, title, message, active, color, created_at, updated_at, color_dark, starts, ends
`

type UpdateAppBannerParams struct {
	ID        int32
	Title     string
	Message   string
	Active    *bool
	Color     string
	ColorDark string
	Type      pgtype.Text
	Starts    pgtype.Timestamp
	Ends      pgtype.Timestamp
}

func (q *Queries) UpdateAppBanner(ctx context.Context, arg UpdateAppBannerParams) (TAppBanner, error) {
	row := q.db.QueryRow(ctx, updateAppBanner,
		arg.ID,
		arg.Title,
		arg.Message,
		arg.Active,
		arg.Color,
		arg.ColorDark,
		arg.Type,
		arg.Starts,
		arg.Ends,
	)
	var i TAppBanner
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Active,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ColorDark,
		&i.Starts,
		&i.Ends,
	)
	return i, err
}
