// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package core

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const addRoleToBatchUsers = `-- name: AddRoleToBatchUsers :batchexec
INSERT INTO t_acl_match (user_id, role_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddRoleToBatchUsersBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AddRoleToBatchUsersParams struct {
	UserID pgtype.Int4
	RoleID pgtype.Int4
}

func (q *Queries) AddRoleToBatchUsers(ctx context.Context, arg []AddRoleToBatchUsersParams) *AddRoleToBatchUsersBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.UserID,
			a.RoleID,
		}
		batch.Queue(addRoleToBatchUsers, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AddRoleToBatchUsersBatchResults{br, len(arg), false}
}

func (b *AddRoleToBatchUsersBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *AddRoleToBatchUsersBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const deleteBatchUsersFromGroup = `-- name: DeleteBatchUsersFromGroup :batchexec
DELETE FROM t_user_group_match 
WHERE user_id = $1 AND user_group_id = $2
`

type DeleteBatchUsersFromGroupBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type DeleteBatchUsersFromGroupParams struct {
	UserID      int32
	UserGroupID int32
}

func (q *Queries) DeleteBatchUsersFromGroup(ctx context.Context, arg []DeleteBatchUsersFromGroupParams) *DeleteBatchUsersFromGroupBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.UserID,
			a.UserGroupID,
		}
		batch.Queue(deleteBatchUsersFromGroup, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &DeleteBatchUsersFromGroupBatchResults{br, len(arg), false}
}

func (b *DeleteBatchUsersFromGroupBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *DeleteBatchUsersFromGroupBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const deleteBatchUsersFromRole = `-- name: DeleteBatchUsersFromRole :batchexec
DELETE FROM t_acl_match
WHERE user_id = $1 AND role_id = $2
`

type DeleteBatchUsersFromRoleBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type DeleteBatchUsersFromRoleParams struct {
	UserID pgtype.Int4
	RoleID pgtype.Int4
}

func (q *Queries) DeleteBatchUsersFromRole(ctx context.Context, arg []DeleteBatchUsersFromRoleParams) *DeleteBatchUsersFromRoleBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.UserID,
			a.RoleID,
		}
		batch.Queue(deleteBatchUsersFromRole, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &DeleteBatchUsersFromRoleBatchResults{br, len(arg), false}
}

func (b *DeleteBatchUsersFromRoleBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *DeleteBatchUsersFromRoleBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertBatchUsersToGroup = `-- name: InsertBatchUsersToGroup :batchexec
INSERT INTO t_user_group_match (user_id, user_group_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertBatchUsersToGroupBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertBatchUsersToGroupParams struct {
	UserID      int32
	UserGroupID int32
}

func (q *Queries) InsertBatchUsersToGroup(ctx context.Context, arg []InsertBatchUsersToGroupParams) *InsertBatchUsersToGroupBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.UserID,
			a.UserGroupID,
		}
		batch.Queue(insertBatchUsersToGroup, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertBatchUsersToGroupBatchResults{br, len(arg), false}
}

func (b *InsertBatchUsersToGroupBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertBatchUsersToGroupBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertExperimentDatasets = `-- name: InsertExperimentDatasets :batchone
INSERT INTO t_experiment_dataset (experiment_id, dataset_id, alias)
VALUES ($1, $2, $3)
    RETURNING id
`

type InsertExperimentDatasetsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertExperimentDatasetsParams struct {
	ExperimentID int32
	DatasetID    int32
	Alias        string
}

func (q *Queries) InsertExperimentDatasets(ctx context.Context, arg []InsertExperimentDatasetsParams) *InsertExperimentDatasetsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ExperimentID,
			a.DatasetID,
			a.Alias,
		}
		batch.Queue(insertExperimentDatasets, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertExperimentDatasetsBatchResults{br, len(arg), false}
}

func (b *InsertExperimentDatasetsBatchResults) QueryRow(f func(int, int32, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id int32
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *InsertExperimentDatasetsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertExperimentVariables = `-- name: InsertExperimentVariables :batchone
INSERT INTO t_experiment_variable (experiment_id, name, value, type) VALUES ($1, $2, $3, $4) RETURNING id
`

type InsertExperimentVariablesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertExperimentVariablesParams struct {
	ExperimentID int32
	Name         string
	Value        string
	Type         string
}

func (q *Queries) InsertExperimentVariables(ctx context.Context, arg []InsertExperimentVariablesParams) *InsertExperimentVariablesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ExperimentID,
			a.Name,
			a.Value,
			a.Type,
		}
		batch.Queue(insertExperimentVariables, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertExperimentVariablesBatchResults{br, len(arg), false}
}

func (b *InsertExperimentVariablesBatchResults) QueryRow(f func(int, int32, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id int32
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *InsertExperimentVariablesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertExperimentVariablesV2 = `-- name: InsertExperimentVariablesV2 :batchone
WITH new_variable AS (
INSERT INTO t_experiment_variable (experiment_id, name)
VALUES ($1, $2)
    RETURNING id
    ),
    new_version AS (
INSERT INTO t_experiment_variable_v (variable_id, version, value, type, created_at, creator, comment)
SELECT id, 1, $3, $4, NOW(), $5, $6
FROM new_variable
    RETURNING t_experiment_variable_v.variable_id, t_experiment_variable_v.id AS version_id
    )
UPDATE t_experiment_variable tpv
SET version_id = nv.version_id
    FROM new_version nv
WHERE tpv.id = nv.variable_id
    RETURNING tpv.id
`

type InsertExperimentVariablesV2BatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertExperimentVariablesV2Params struct {
	ExperimentID int32
	Name         string
	Value        string
	Type         string
	Creator      string
	Comment      string
}

func (q *Queries) InsertExperimentVariablesV2(ctx context.Context, arg []InsertExperimentVariablesV2Params) *InsertExperimentVariablesV2BatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ExperimentID,
			a.Name,
			a.Value,
			a.Type,
			a.Creator,
			a.Comment,
		}
		batch.Queue(insertExperimentVariablesV2, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertExperimentVariablesV2BatchResults{br, len(arg), false}
}

func (b *InsertExperimentVariablesV2BatchResults) QueryRow(f func(int, int32, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id int32
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *InsertExperimentVariablesV2BatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertNewUsers = `-- name: InsertNewUsers :batchone
WITH ins AS (
        INSERT INTO t_user(name) VALUES($1) ON CONFLICT DO NOTHING RETURNING id
)
SELECT id FROM ins
UNION ALL
SELECT id FROM t_user WHERE name = $1
`

type InsertNewUsersBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) InsertNewUsers(ctx context.Context, name []string) *InsertNewUsersBatchResults {
	batch := &pgx.Batch{}
	for _, a := range name {
		vals := []interface{}{
			a,
		}
		batch.Queue(insertNewUsers, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertNewUsersBatchResults{br, len(name), false}
}

func (b *InsertNewUsersBatchResults) QueryRow(f func(int, int32, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id int32
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *InsertNewUsersBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
