// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parents.sql

package core

import (
	"context"
)

const getDatasetNamespace = `-- name: GetDatasetNamespace :one
SELECT t_namespace.id, t_namespace.name FROM t_namespace
JOIN t_dataset ON t_dataset.namespace_id = t_namespace.id
WHERE t_dataset.id = $1 AND t_namespace.deleted = FALSE AND t_dataset.deleted = FALSE
`

type GetDatasetNamespaceRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetDatasetNamespace(ctx context.Context, id int32) (GetDatasetNamespaceRow, error) {
	row := q.db.QueryRow(ctx, getDatasetNamespace, id)
	var i GetDatasetNamespaceRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getDatasetProject = `-- name: GetDatasetProject :one
SELECT t_project.id, t_project.name FROM t_project
                                                 JOIN t_dataset ON t_dataset.project_id = t_project.id
WHERE t_dataset.id = $1 AND t_project.deleted = FALSE AND t_dataset.deleted = FALSE
`

type GetDatasetProjectRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetDatasetProject(ctx context.Context, id int32) (GetDatasetProjectRow, error) {
	row := q.db.QueryRow(ctx, getDatasetProject, id)
	var i GetDatasetProjectRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getExperimentNamespace = `-- name: GetExperimentNamespace :one
SELECT t_namespace.id, t_namespace.name FROM t_namespace
JOIN t_project ON t_project.namespace_id = t_namespace.id
JOIN t_experiment ON t_experiment.project_id = t_project.id
WHERE t_experiment.id = $1 AND t_namespace.deleted = FALSE AND t_project.deleted = FALSE
`

type GetExperimentNamespaceRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetExperimentNamespace(ctx context.Context, id int32) (GetExperimentNamespaceRow, error) {
	row := q.db.QueryRow(ctx, getExperimentNamespace, id)
	var i GetExperimentNamespaceRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getExperimentProject = `-- name: GetExperimentProject :one
SELECT t_project.id FROM t_project
JOIN t_experiment ON t_experiment.project_id = t_project.id
WHERE t_experiment.id = $1 AND t_project.deleted = FALSE
`

func (q *Queries) GetExperimentProject(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, getExperimentProject, id)
	err := row.Scan(&id)
	return id, err
}

const getProjectNamespace = `-- name: GetProjectNamespace :one
SELECT t_namespace.id, t_namespace.name FROM t_namespace
JOIN t_project ON t_project.namespace_id = t_namespace.id
WHERE t_project.id = $1 AND t_namespace.deleted = FALSE AND t_project.deleted = FALSE
`

type GetProjectNamespaceRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetProjectNamespace(ctx context.Context, id int32) (GetProjectNamespaceRow, error) {
	row := q.db.QueryRow(ctx, getProjectNamespace, id)
	var i GetProjectNamespaceRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
