// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoNamespaceConfigVersion dto namespace config version
//
// swagger:model dto.NamespaceConfigVersion
type DtoNamespaceConfigVersion struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this dto namespace config version
func (m *DtoNamespaceConfigVersion) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto namespace config version based on context it is used
func (m *DtoNamespaceConfigVersion) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoNamespaceConfigVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoNamespaceConfigVersion) UnmarshalBinary(b []byte) error {
	var res DtoNamespaceConfigVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
