// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoNamespaceConfig dto namespace config
//
// swagger:model dto.NamespaceConfig
type DtoNamespaceConfig struct {

	// config
	Config string `json:"config,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this dto namespace config
func (m *DtoNamespaceConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto namespace config based on context it is used
func (m *DtoNamespaceConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoNamespaceConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoNamespaceConfig) UnmarshalBinary(b []byte) error {
	var res DtoNamespaceConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
