// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoProjectConfigVersion dto project config version
//
// swagger:model dto.ProjectConfigVersion
type DtoProjectConfigVersion struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this dto project config version
func (m *DtoProjectConfigVersion) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto project config version based on context it is used
func (m *DtoProjectConfigVersion) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoProjectConfigVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoProjectConfigVersion) UnmarshalBinary(b []byte) error {
	var res DtoProjectConfigVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
