// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoValidationError dto validation error
//
// swagger:model dto.ValidationError
type DtoValidationError struct {

	// config pos
	ConfigPos int64 `json:"config_pos,omitempty"`

	// entity name
	EntityName string `json:"entity_name,omitempty"`

	// entity type
	EntityType string `json:"entity_type,omitempty"`

	// error message
	ErrorMessage string `json:"error_message,omitempty"`
}

// Validate validates this dto validation error
func (m *DtoValidationError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto validation error based on context it is used
func (m *DtoValidationError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoValidationError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoValidationError) UnmarshalBinary(b []byte) error {
	var res DtoValidationError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
