// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RequestsAddRuleToRoleRequest requests add rule to role request
//
// swagger:model requests.AddRuleToRoleRequest
type RequestsAddRuleToRoleRequest struct {

	// role id
	// Required: true
	RoleID *int64 `json:"role_id"`

	// rule id
	// Required: true
	RuleID *int64 `json:"rule_id"`
}

// Validate validates this requests add rule to role request
func (m *RequestsAddRuleToRoleRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRoleID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRuleID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RequestsAddRuleToRoleRequest) validateRoleID(formats strfmt.Registry) error {

	if err := validate.Required("role_id", "body", m.RoleID); err != nil {
		return err
	}

	return nil
}

func (m *RequestsAddRuleToRoleRequest) validateRuleID(formats strfmt.Registry) error {

	if err := validate.Required("rule_id", "body", m.RuleID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this requests add rule to role request based on context it is used
func (m *RequestsAddRuleToRoleRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestsAddRuleToRoleRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestsAddRuleToRoleRequest) UnmarshalBinary(b []byte) error {
	var res RequestsAddRuleToRoleRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
