// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RequestsCreateRoleRequest requests create role request
//
// swagger:model requests.CreateRoleRequest
type RequestsCreateRoleRequest struct {

	// description
	Description string `json:"description,omitempty"`

	// IdmID is an optional stable external key stored in t_role.idm_id; when empty, a value is generated.
	IdmID string `json:"idm_id,omitempty"`

	// name
	// Required: true
	// Max Length: 128
	// Min Length: 1
	Name *string `json:"name"`
}

// Validate validates this requests create role request
func (m *RequestsCreateRoleRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RequestsCreateRoleRequest) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", *m.Name, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", *m.Name, 128); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this requests create role request based on context it is used
func (m *RequestsCreateRoleRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestsCreateRoleRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestsCreateRoleRequest) UnmarshalBinary(b []byte) error {
	var res RequestsCreateRoleRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
