// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsesListPinnedProjectsResponse responses list pinned projects response
//
// swagger:model responses.ListPinnedProjectsResponse
type ResponsesListPinnedProjectsResponse struct {

	// pinned projects
	PinnedProjects []*DtoPinnedProject `json:"pinned_projects"`
}

// Validate validates this responses list pinned projects response
func (m *ResponsesListPinnedProjectsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePinnedProjects(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponsesListPinnedProjectsResponse) validatePinnedProjects(formats strfmt.Registry) error {
	if swag.IsZero(m.PinnedProjects) { // not required
		return nil
	}

	for i := 0; i < len(m.PinnedProjects); i++ {
		if swag.IsZero(m.PinnedProjects[i]) { // not required
			continue
		}

		if m.PinnedProjects[i] != nil {
			if err := m.PinnedProjects[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("pinned_projects" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("pinned_projects" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this responses list pinned projects response based on the context it is used
func (m *ResponsesListPinnedProjectsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePinnedProjects(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponsesListPinnedProjectsResponse) contextValidatePinnedProjects(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.PinnedProjects); i++ {

		if m.PinnedProjects[i] != nil {

			if swag.IsZero(m.PinnedProjects[i]) { // not required
				return nil
			}

			if err := m.PinnedProjects[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("pinned_projects" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("pinned_projects" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResponsesListPinnedProjectsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsesListPinnedProjectsResponse) UnmarshalBinary(b []byte) error {
	var res ResponsesListPinnedProjectsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
