// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsesCreateRobotResponse responses create robot response
//
// swagger:model responses.CreateRobotResponse
type ResponsesCreateRobotResponse struct {

	// access token
	AccessToken *JwtClientTokenInfo `json:"access_token,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this responses create robot response
func (m *ResponsesCreateRobotResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccessToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponsesCreateRobotResponse) validateAccessToken(formats strfmt.Registry) error {
	if swag.IsZero(m.AccessToken) { // not required
		return nil
	}

	if m.AccessToken != nil {
		if err := m.AccessToken.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("access_token")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("access_token")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this responses create robot response based on the context it is used
func (m *ResponsesCreateRobotResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAccessToken(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponsesCreateRobotResponse) contextValidateAccessToken(ctx context.Context, formats strfmt.Registry) error {

	if m.AccessToken != nil {

		if swag.IsZero(m.AccessToken) { // not required
			return nil
		}

		if err := m.AccessToken.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("access_token")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("access_token")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResponsesCreateRobotResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsesCreateRobotResponse) UnmarshalBinary(b []byte) error {
	var res ResponsesCreateRobotResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
