// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsesUpdateAppBannerResponse responses update app banner response
//
// swagger:model responses.UpdateAppBannerResponse
type ResponsesUpdateAppBannerResponse struct {

	// app banner
	AppBanner *DtoAppBanner `json:"app_banner,omitempty"`
}

// Validate validates this responses update app banner response
func (m *ResponsesUpdateAppBannerResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAppBanner(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponsesUpdateAppBannerResponse) validateAppBanner(formats strfmt.Registry) error {
	if swag.IsZero(m.AppBanner) { // not required
		return nil
	}

	if m.AppBanner != nil {
		if err := m.AppBanner.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("app_banner")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("app_banner")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this responses update app banner response based on the context it is used
func (m *ResponsesUpdateAppBannerResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAppBanner(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponsesUpdateAppBannerResponse) contextValidateAppBanner(ctx context.Context, formats strfmt.Registry) error {

	if m.AppBanner != nil {

		if swag.IsZero(m.AppBanner) { // not required
			return nil
		}

		if err := m.AppBanner.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("app_banner")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("app_banner")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResponsesUpdateAppBannerResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsesUpdateAppBannerResponse) UnmarshalBinary(b []byte) error {
	var res ResponsesUpdateAppBannerResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
