// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsesUpdateAppUpcomingResponse responses update app upcoming response
//
// swagger:model responses.UpdateAppUpcomingResponse
type ResponsesUpdateAppUpcomingResponse struct {

	// app upcoming
	AppUpcoming *DtoAppUpcoming `json:"app_upcoming,omitempty"`
}

// Validate validates this responses update app upcoming response
func (m *ResponsesUpdateAppUpcomingResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAppUpcoming(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponsesUpdateAppUpcomingResponse) validateAppUpcoming(formats strfmt.Registry) error {
	if swag.IsZero(m.AppUpcoming) { // not required
		return nil
	}

	if m.AppUpcoming != nil {
		if err := m.AppUpcoming.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("app_upcoming")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("app_upcoming")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this responses update app upcoming response based on the context it is used
func (m *ResponsesUpdateAppUpcomingResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAppUpcoming(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponsesUpdateAppUpcomingResponse) contextValidateAppUpcoming(ctx context.Context, formats strfmt.Registry) error {

	if m.AppUpcoming != nil {

		if swag.IsZero(m.AppUpcoming) { // not required
			return nil
		}

		if err := m.AppUpcoming.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("app_upcoming")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("app_upcoming")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResponsesUpdateAppUpcomingResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsesUpdateAppUpcomingResponse) UnmarshalBinary(b []byte) error {
	var res ResponsesUpdateAppUpcomingResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
