// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsesValidationResponse responses validation response
//
// swagger:model responses.ValidationResponse
type ResponsesValidationResponse struct {

	// errors
	Errors string `json:"errors,omitempty"`

	// success
	Success bool `json:"success,omitempty"`
}

// Validate validates this responses validation response
func (m *ResponsesValidationResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this responses validation response based on context it is used
func (m *ResponsesValidationResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponsesValidationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsesValidationResponse) UnmarshalBinary(b []byte) error {
	var res ResponsesValidationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
