// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsesGetAppUpdateResponse responses get app update response
//
// swagger:model responses.GetAppUpdateResponse
type ResponsesGetAppUpdateResponse struct {

	// app update
	AppUpdate *DtoAppUpdate `json:"app_update,omitempty"`
}

// Validate validates this responses get app update response
func (m *ResponsesGetAppUpdateResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAppUpdate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponsesGetAppUpdateResponse) validateAppUpdate(formats strfmt.Registry) error {
	if swag.IsZero(m.AppUpdate) { // not required
		return nil
	}

	if m.AppUpdate != nil {
		if err := m.AppUpdate.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("app_update")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("app_update")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this responses get app update response based on the context it is used
func (m *ResponsesGetAppUpdateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAppUpdate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponsesGetAppUpdateResponse) contextValidateAppUpdate(ctx context.Context, formats strfmt.Registry) error {

	if m.AppUpdate != nil {

		if swag.IsZero(m.AppUpdate) { // not required
			return nil
		}

		if err := m.AppUpdate.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("app_update")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("app_update")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResponsesGetAppUpdateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsesGetAppUpdateResponse) UnmarshalBinary(b []byte) error {
	var res ResponsesGetAppUpdateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
