// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsesListCubesResponse responses list cubes response
//
// swagger:model responses.ListCubesResponse
type ResponsesListCubesResponse struct {

	// cubes
	Cubes []*DtoCube `json:"cubes"`
}

// Validate validates this responses list cubes response
func (m *ResponsesListCubesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCubes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponsesListCubesResponse) validateCubes(formats strfmt.Registry) error {
	if swag.IsZero(m.Cubes) { // not required
		return nil
	}

	for i := 0; i < len(m.Cubes); i++ {
		if swag.IsZero(m.Cubes[i]) { // not required
			continue
		}

		if m.Cubes[i] != nil {
			if err := m.Cubes[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("cubes" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("cubes" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this responses list cubes response based on the context it is used
func (m *ResponsesListCubesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCubes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponsesListCubesResponse) contextValidateCubes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Cubes); i++ {

		if m.Cubes[i] != nil {

			if swag.IsZero(m.Cubes[i]) { // not required
				return nil
			}

			if err := m.Cubes[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("cubes" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("cubes" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResponsesListCubesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsesListCubesResponse) UnmarshalBinary(b []byte) error {
	var res ResponsesListCubesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
