// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsesCreateProjectRolesResponse responses create project roles response
//
// swagger:model responses.CreateProjectRolesResponse
type ResponsesCreateProjectRolesResponse struct {

	// roles created
	RolesCreated int64 `json:"roles_created,omitempty"`
}

// Validate validates this responses create project roles response
func (m *ResponsesCreateProjectRolesResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this responses create project roles response based on context it is used
func (m *ResponsesCreateProjectRolesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponsesCreateProjectRolesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsesCreateProjectRolesResponse) UnmarshalBinary(b []byte) error {
	var res ResponsesCreateProjectRolesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
