// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsesGetOrchestratorConfigResponse responses get orchestrator config response
//
// swagger:model responses.GetOrchestratorConfigResponse
type ResponsesGetOrchestratorConfigResponse struct {

	// config
	Config string `json:"config,omitempty"`
}

// Validate validates this responses get orchestrator config response
func (m *ResponsesGetOrchestratorConfigResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this responses get orchestrator config response based on context it is used
func (m *ResponsesGetOrchestratorConfigResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponsesGetOrchestratorConfigResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsesGetOrchestratorConfigResponse) UnmarshalBinary(b []byte) error {
	var res ResponsesGetOrchestratorConfigResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
