// Code generated by go-swagger; DO NOT EDIT.

package meta

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.corp.mail.ru/ai/streamflow/backend/cplane/tests/private/models"
)

// GetAPIV1PingReader is a Reader for the GetAPIV1Ping structure.
type GetAPIV1PingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1PingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1PingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1PingBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAPIV1PingForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV1PingNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1PingInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/ping] GetAPIV1Ping", response, response.Code())
	}
}

// NewGetAPIV1PingOK creates a GetAPIV1PingOK with default headers values
func NewGetAPIV1PingOK() *GetAPIV1PingOK {
	return &GetAPIV1PingOK{}
}

/*
GetAPIV1PingOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1PingOK struct {
	Payload *models.PrivatePingResponse
}

// IsSuccess returns true when this get Api v1 ping o k response has a 2xx status code
func (o *GetAPIV1PingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 ping o k response has a 3xx status code
func (o *GetAPIV1PingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 ping o k response has a 4xx status code
func (o *GetAPIV1PingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 ping o k response has a 5xx status code
func (o *GetAPIV1PingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 ping o k response a status code equal to that given
func (o *GetAPIV1PingOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 ping o k response
func (o *GetAPIV1PingOK) Code() int {
	return 200
}

func (o *GetAPIV1PingOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/ping][%d] getApiV1PingOK %s", 200, payload)
}

func (o *GetAPIV1PingOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/ping][%d] getApiV1PingOK %s", 200, payload)
}

func (o *GetAPIV1PingOK) GetPayload() *models.PrivatePingResponse {
	return o.Payload
}

func (o *GetAPIV1PingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PrivatePingResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1PingBadRequest creates a GetAPIV1PingBadRequest with default headers values
func NewGetAPIV1PingBadRequest() *GetAPIV1PingBadRequest {
	return &GetAPIV1PingBadRequest{}
}

/*
GetAPIV1PingBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAPIV1PingBadRequest struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 ping bad request response has a 2xx status code
func (o *GetAPIV1PingBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 ping bad request response has a 3xx status code
func (o *GetAPIV1PingBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 ping bad request response has a 4xx status code
func (o *GetAPIV1PingBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 ping bad request response has a 5xx status code
func (o *GetAPIV1PingBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 ping bad request response a status code equal to that given
func (o *GetAPIV1PingBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v1 ping bad request response
func (o *GetAPIV1PingBadRequest) Code() int {
	return 400
}

func (o *GetAPIV1PingBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/ping][%d] getApiV1PingBadRequest %s", 400, payload)
}

func (o *GetAPIV1PingBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/ping][%d] getApiV1PingBadRequest %s", 400, payload)
}

func (o *GetAPIV1PingBadRequest) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1PingBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1PingForbidden creates a GetAPIV1PingForbidden with default headers values
func NewGetAPIV1PingForbidden() *GetAPIV1PingForbidden {
	return &GetAPIV1PingForbidden{}
}

/*
GetAPIV1PingForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAPIV1PingForbidden struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 ping forbidden response has a 2xx status code
func (o *GetAPIV1PingForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 ping forbidden response has a 3xx status code
func (o *GetAPIV1PingForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 ping forbidden response has a 4xx status code
func (o *GetAPIV1PingForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 ping forbidden response has a 5xx status code
func (o *GetAPIV1PingForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 ping forbidden response a status code equal to that given
func (o *GetAPIV1PingForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v1 ping forbidden response
func (o *GetAPIV1PingForbidden) Code() int {
	return 403
}

func (o *GetAPIV1PingForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/ping][%d] getApiV1PingForbidden %s", 403, payload)
}

func (o *GetAPIV1PingForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/ping][%d] getApiV1PingForbidden %s", 403, payload)
}

func (o *GetAPIV1PingForbidden) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1PingForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1PingNotFound creates a GetAPIV1PingNotFound with default headers values
func NewGetAPIV1PingNotFound() *GetAPIV1PingNotFound {
	return &GetAPIV1PingNotFound{}
}

/*
GetAPIV1PingNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAPIV1PingNotFound struct {
	Payload *models.ResponsesCreateAppBannerResponse
}

// IsSuccess returns true when this get Api v1 ping not found response has a 2xx status code
func (o *GetAPIV1PingNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 ping not found response has a 3xx status code
func (o *GetAPIV1PingNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 ping not found response has a 4xx status code
func (o *GetAPIV1PingNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 ping not found response has a 5xx status code
func (o *GetAPIV1PingNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 ping not found response a status code equal to that given
func (o *GetAPIV1PingNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v1 ping not found response
func (o *GetAPIV1PingNotFound) Code() int {
	return 404
}

func (o *GetAPIV1PingNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/ping][%d] getApiV1PingNotFound %s", 404, payload)
}

func (o *GetAPIV1PingNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/ping][%d] getApiV1PingNotFound %s", 404, payload)
}

func (o *GetAPIV1PingNotFound) GetPayload() *models.ResponsesCreateAppBannerResponse {
	return o.Payload
}

func (o *GetAPIV1PingNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesCreateAppBannerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1PingInternalServerError creates a GetAPIV1PingInternalServerError with default headers values
func NewGetAPIV1PingInternalServerError() *GetAPIV1PingInternalServerError {
	return &GetAPIV1PingInternalServerError{}
}

/*
GetAPIV1PingInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetAPIV1PingInternalServerError struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 ping internal server error response has a 2xx status code
func (o *GetAPIV1PingInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 ping internal server error response has a 3xx status code
func (o *GetAPIV1PingInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 ping internal server error response has a 4xx status code
func (o *GetAPIV1PingInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 ping internal server error response has a 5xx status code
func (o *GetAPIV1PingInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 ping internal server error response a status code equal to that given
func (o *GetAPIV1PingInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 ping internal server error response
func (o *GetAPIV1PingInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1PingInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/ping][%d] getApiV1PingInternalServerError %s", 500, payload)
}

func (o *GetAPIV1PingInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/ping][%d] getApiV1PingInternalServerError %s", 500, payload)
}

func (o *GetAPIV1PingInternalServerError) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1PingInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
