// Code generated by go-swagger; DO NOT EDIT.

package meta

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.corp.mail.ru/ai/streamflow/backend/cplane/tests/private/models"
)

// GetAPIV1VersionReader is a Reader for the GetAPIV1Version structure.
type GetAPIV1VersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1VersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1VersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1VersionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAPIV1VersionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAPIV1VersionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV1VersionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1VersionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/version] GetAPIV1Version", response, response.Code())
	}
}

// NewGetAPIV1VersionOK creates a GetAPIV1VersionOK with default headers values
func NewGetAPIV1VersionOK() *GetAPIV1VersionOK {
	return &GetAPIV1VersionOK{}
}

/*
GetAPIV1VersionOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1VersionOK struct {
	Payload *models.PrivateVersionResponse
}

// IsSuccess returns true when this get Api v1 version o k response has a 2xx status code
func (o *GetAPIV1VersionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 version o k response has a 3xx status code
func (o *GetAPIV1VersionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 version o k response has a 4xx status code
func (o *GetAPIV1VersionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 version o k response has a 5xx status code
func (o *GetAPIV1VersionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 version o k response a status code equal to that given
func (o *GetAPIV1VersionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 version o k response
func (o *GetAPIV1VersionOK) Code() int {
	return 200
}

func (o *GetAPIV1VersionOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/version][%d] getApiV1VersionOK %s", 200, payload)
}

func (o *GetAPIV1VersionOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/version][%d] getApiV1VersionOK %s", 200, payload)
}

func (o *GetAPIV1VersionOK) GetPayload() *models.PrivateVersionResponse {
	return o.Payload
}

func (o *GetAPIV1VersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PrivateVersionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1VersionBadRequest creates a GetAPIV1VersionBadRequest with default headers values
func NewGetAPIV1VersionBadRequest() *GetAPIV1VersionBadRequest {
	return &GetAPIV1VersionBadRequest{}
}

/*
GetAPIV1VersionBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAPIV1VersionBadRequest struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 version bad request response has a 2xx status code
func (o *GetAPIV1VersionBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 version bad request response has a 3xx status code
func (o *GetAPIV1VersionBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 version bad request response has a 4xx status code
func (o *GetAPIV1VersionBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 version bad request response has a 5xx status code
func (o *GetAPIV1VersionBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 version bad request response a status code equal to that given
func (o *GetAPIV1VersionBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v1 version bad request response
func (o *GetAPIV1VersionBadRequest) Code() int {
	return 400
}

func (o *GetAPIV1VersionBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/version][%d] getApiV1VersionBadRequest %s", 400, payload)
}

func (o *GetAPIV1VersionBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/version][%d] getApiV1VersionBadRequest %s", 400, payload)
}

func (o *GetAPIV1VersionBadRequest) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1VersionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1VersionUnauthorized creates a GetAPIV1VersionUnauthorized with default headers values
func NewGetAPIV1VersionUnauthorized() *GetAPIV1VersionUnauthorized {
	return &GetAPIV1VersionUnauthorized{}
}

/*
GetAPIV1VersionUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAPIV1VersionUnauthorized struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 version unauthorized response has a 2xx status code
func (o *GetAPIV1VersionUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 version unauthorized response has a 3xx status code
func (o *GetAPIV1VersionUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 version unauthorized response has a 4xx status code
func (o *GetAPIV1VersionUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 version unauthorized response has a 5xx status code
func (o *GetAPIV1VersionUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 version unauthorized response a status code equal to that given
func (o *GetAPIV1VersionUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v1 version unauthorized response
func (o *GetAPIV1VersionUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV1VersionUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/version][%d] getApiV1VersionUnauthorized %s", 401, payload)
}

func (o *GetAPIV1VersionUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/version][%d] getApiV1VersionUnauthorized %s", 401, payload)
}

func (o *GetAPIV1VersionUnauthorized) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1VersionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1VersionForbidden creates a GetAPIV1VersionForbidden with default headers values
func NewGetAPIV1VersionForbidden() *GetAPIV1VersionForbidden {
	return &GetAPIV1VersionForbidden{}
}

/*
GetAPIV1VersionForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAPIV1VersionForbidden struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 version forbidden response has a 2xx status code
func (o *GetAPIV1VersionForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 version forbidden response has a 3xx status code
func (o *GetAPIV1VersionForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 version forbidden response has a 4xx status code
func (o *GetAPIV1VersionForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 version forbidden response has a 5xx status code
func (o *GetAPIV1VersionForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 version forbidden response a status code equal to that given
func (o *GetAPIV1VersionForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v1 version forbidden response
func (o *GetAPIV1VersionForbidden) Code() int {
	return 403
}

func (o *GetAPIV1VersionForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/version][%d] getApiV1VersionForbidden %s", 403, payload)
}

func (o *GetAPIV1VersionForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/version][%d] getApiV1VersionForbidden %s", 403, payload)
}

func (o *GetAPIV1VersionForbidden) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1VersionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1VersionNotFound creates a GetAPIV1VersionNotFound with default headers values
func NewGetAPIV1VersionNotFound() *GetAPIV1VersionNotFound {
	return &GetAPIV1VersionNotFound{}
}

/*
GetAPIV1VersionNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAPIV1VersionNotFound struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 version not found response has a 2xx status code
func (o *GetAPIV1VersionNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 version not found response has a 3xx status code
func (o *GetAPIV1VersionNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 version not found response has a 4xx status code
func (o *GetAPIV1VersionNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 version not found response has a 5xx status code
func (o *GetAPIV1VersionNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 version not found response a status code equal to that given
func (o *GetAPIV1VersionNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v1 version not found response
func (o *GetAPIV1VersionNotFound) Code() int {
	return 404
}

func (o *GetAPIV1VersionNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/version][%d] getApiV1VersionNotFound %s", 404, payload)
}

func (o *GetAPIV1VersionNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/version][%d] getApiV1VersionNotFound %s", 404, payload)
}

func (o *GetAPIV1VersionNotFound) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1VersionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1VersionInternalServerError creates a GetAPIV1VersionInternalServerError with default headers values
func NewGetAPIV1VersionInternalServerError() *GetAPIV1VersionInternalServerError {
	return &GetAPIV1VersionInternalServerError{}
}

/*
GetAPIV1VersionInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetAPIV1VersionInternalServerError struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 version internal server error response has a 2xx status code
func (o *GetAPIV1VersionInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 version internal server error response has a 3xx status code
func (o *GetAPIV1VersionInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 version internal server error response has a 4xx status code
func (o *GetAPIV1VersionInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 version internal server error response has a 5xx status code
func (o *GetAPIV1VersionInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 version internal server error response a status code equal to that given
func (o *GetAPIV1VersionInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 version internal server error response
func (o *GetAPIV1VersionInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1VersionInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/version][%d] getApiV1VersionInternalServerError %s", 500, payload)
}

func (o *GetAPIV1VersionInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/version][%d] getApiV1VersionInternalServerError %s", 500, payload)
}

func (o *GetAPIV1VersionInternalServerError) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1VersionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
