DROP VIEW IF EXISTS v_real_experiment_template;
DROP VIEW IF EXISTS v_real_experiment;
DROP VIEW IF EXISTS v_real_dataset;
DROP VIEW IF EXISTS v_real_project;
DROP VIEW IF EXISTS v_real_namespace;

DROP TABLE IF EXISTS t_app_updates CASCADE;
DROP TABLE IF EXISTS t_app_about CASCADE;
DROP TABLE IF EXISTS t_app_upcoming CASCADE;
DROP TABLE IF EXISTS t_app_banner CASCADE;
DROP TABLE IF EXISTS t_cubes CASCADE;
DROP TABLE IF EXISTS robot_tokens CASCADE;
DROP TABLE IF EXISTS t_user_pinned_projects CASCADE;
DROP TABLE IF EXISTS t_role_object_match CASCADE;
DROP TABLE IF EXISTS t_role_owner CASCADE;
DROP TABLE IF EXISTS t_experiment_status CASCADE;
DROP TABLE IF EXISTS t_experiment_variable_v CASCADE;
DROP TABLE IF EXISTS t_experiment_variable CASCADE;
DROP TABLE IF EXISTS t_project_variable CASCADE;
DROP TABLE IF EXISTS t_namespace_variable CASCADE;
DROP TABLE IF EXISTS t_experiment_dataset CASCADE;
DROP TABLE IF EXISTS t_dataset_v CASCADE;
DROP TABLE IF EXISTS t_experiment_update_log CASCADE;
DROP TABLE IF EXISTS t_dataset_update_log CASCADE;
DROP TABLE IF EXISTS t_project_update_log CASCADE;
DROP TABLE IF EXISTS t_namespace_update_log CASCADE;
DROP TABLE IF EXISTS t_experiment_io CASCADE;
DROP TABLE IF EXISTS t_experiment CASCADE;
DROP TABLE IF EXISTS t_dataset CASCADE;
DROP TABLE IF EXISTS t_experiment_template_v CASCADE;
DROP TABLE IF EXISTS t_experiment_template CASCADE;
DROP TABLE IF EXISTS t_project_config_v CASCADE;
DROP TABLE IF EXISTS t_namespace_config_v CASCADE;
DROP TABLE IF EXISTS t_project CASCADE;
DROP TABLE IF EXISTS t_namespace CASCADE;
DROP TABLE IF EXISTS t_user_rule CASCADE;
DROP TABLE IF EXISTS t_acl_match CASCADE;
DROP TABLE IF EXISTS t_role_match CASCADE;
DROP TABLE IF EXISTS t_rule CASCADE;
DROP TABLE IF EXISTS t_role CASCADE;
DROP TABLE IF EXISTS t_user_group_match CASCADE;
DROP TABLE IF EXISTS t_user_group CASCADE;
DROP TABLE IF EXISTS t_user CASCADE;

DROP FUNCTION IF EXISTS update_project_timestamp();
DROP FUNCTION IF EXISTS safe_jsonb_parse(text);
DROP FUNCTION IF EXISTS add_rule_to_role();
DROP FUNCTION IF EXISTS add_role_to_user_group();
DROP FUNCTION IF EXISTS add_role_to_user();
DROP FUNCTION IF EXISTS add_rule_to_user();
DROP FUNCTION IF EXISTS add_rule_to_user_group();
DROP FUNCTION IF EXISTS add_user_to_user_group();
DROP FUNCTION IF EXISTS remove_rule_from_role();
DROP FUNCTION IF EXISTS remove_role_from_user_group();
DROP FUNCTION IF EXISTS remove_role_from_user();
DROP FUNCTION IF EXISTS remove_rule_from_user();
DROP FUNCTION IF EXISTS remove_rule_from_user_group();
DROP FUNCTION IF EXISTS remove_user_from_user_group();
