// Code generated by go-swagger; DO NOT EDIT.

package project

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV2ProjectsPinnedParams creates a new GetAPIV2ProjectsPinnedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV2ProjectsPinnedParams() *GetAPIV2ProjectsPinnedParams {
	return &GetAPIV2ProjectsPinnedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV2ProjectsPinnedParamsWithTimeout creates a new GetAPIV2ProjectsPinnedParams object
// with the ability to set a timeout on a request.
func NewGetAPIV2ProjectsPinnedParamsWithTimeout(timeout time.Duration) *GetAPIV2ProjectsPinnedParams {
	return &GetAPIV2ProjectsPinnedParams{
		timeout: timeout,
	}
}

// NewGetAPIV2ProjectsPinnedParamsWithContext creates a new GetAPIV2ProjectsPinnedParams object
// with the ability to set a context for a request.
func NewGetAPIV2ProjectsPinnedParamsWithContext(ctx context.Context) *GetAPIV2ProjectsPinnedParams {
	return &GetAPIV2ProjectsPinnedParams{
		Context: ctx,
	}
}

// NewGetAPIV2ProjectsPinnedParamsWithHTTPClient creates a new GetAPIV2ProjectsPinnedParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV2ProjectsPinnedParamsWithHTTPClient(client *http.Client) *GetAPIV2ProjectsPinnedParams {
	return &GetAPIV2ProjectsPinnedParams{
		HTTPClient: client,
	}
}

/*
GetAPIV2ProjectsPinnedParams contains all the parameters to send to the API endpoint

	for the get API v2 projects pinned operation.

	Typically these are written to a http.Request.
*/
type GetAPIV2ProjectsPinnedParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v2 projects pinned params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV2ProjectsPinnedParams) WithDefaults() *GetAPIV2ProjectsPinnedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v2 projects pinned params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV2ProjectsPinnedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v2 projects pinned params
func (o *GetAPIV2ProjectsPinnedParams) WithTimeout(timeout time.Duration) *GetAPIV2ProjectsPinnedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v2 projects pinned params
func (o *GetAPIV2ProjectsPinnedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v2 projects pinned params
func (o *GetAPIV2ProjectsPinnedParams) WithContext(ctx context.Context) *GetAPIV2ProjectsPinnedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v2 projects pinned params
func (o *GetAPIV2ProjectsPinnedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v2 projects pinned params
func (o *GetAPIV2ProjectsPinnedParams) WithHTTPClient(client *http.Client) *GetAPIV2ProjectsPinnedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v2 projects pinned params
func (o *GetAPIV2ProjectsPinnedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV2ProjectsPinnedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
