// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.corp.mail.ru/ai/streamflow/backend/cplane/tests/private/models"
)

// GetAPIV2ProjectsPinnedReader is a Reader for the GetAPIV2ProjectsPinned structure.
type GetAPIV2ProjectsPinnedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV2ProjectsPinnedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV2ProjectsPinnedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV2ProjectsPinnedBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAPIV2ProjectsPinnedUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAPIV2ProjectsPinnedForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV2ProjectsPinnedNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV2ProjectsPinnedInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v2/projects/pinned] GetAPIV2ProjectsPinned", response, response.Code())
	}
}

// NewGetAPIV2ProjectsPinnedOK creates a GetAPIV2ProjectsPinnedOK with default headers values
func NewGetAPIV2ProjectsPinnedOK() *GetAPIV2ProjectsPinnedOK {
	return &GetAPIV2ProjectsPinnedOK{}
}

/*
GetAPIV2ProjectsPinnedOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV2ProjectsPinnedOK struct {
	Payload *models.ResponsesListPinnedProjectsResponse
}

// IsSuccess returns true when this get Api v2 projects pinned o k response has a 2xx status code
func (o *GetAPIV2ProjectsPinnedOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v2 projects pinned o k response has a 3xx status code
func (o *GetAPIV2ProjectsPinnedOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 projects pinned o k response has a 4xx status code
func (o *GetAPIV2ProjectsPinnedOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v2 projects pinned o k response has a 5xx status code
func (o *GetAPIV2ProjectsPinnedOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 projects pinned o k response a status code equal to that given
func (o *GetAPIV2ProjectsPinnedOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v2 projects pinned o k response
func (o *GetAPIV2ProjectsPinnedOK) Code() int {
	return 200
}

func (o *GetAPIV2ProjectsPinnedOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/pinned][%d] getApiV2ProjectsPinnedOK %s", 200, payload)
}

func (o *GetAPIV2ProjectsPinnedOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/pinned][%d] getApiV2ProjectsPinnedOK %s", 200, payload)
}

func (o *GetAPIV2ProjectsPinnedOK) GetPayload() *models.ResponsesListPinnedProjectsResponse {
	return o.Payload
}

func (o *GetAPIV2ProjectsPinnedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesListPinnedProjectsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV2ProjectsPinnedBadRequest creates a GetAPIV2ProjectsPinnedBadRequest with default headers values
func NewGetAPIV2ProjectsPinnedBadRequest() *GetAPIV2ProjectsPinnedBadRequest {
	return &GetAPIV2ProjectsPinnedBadRequest{}
}

/*
GetAPIV2ProjectsPinnedBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAPIV2ProjectsPinnedBadRequest struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v2 projects pinned bad request response has a 2xx status code
func (o *GetAPIV2ProjectsPinnedBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 projects pinned bad request response has a 3xx status code
func (o *GetAPIV2ProjectsPinnedBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 projects pinned bad request response has a 4xx status code
func (o *GetAPIV2ProjectsPinnedBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v2 projects pinned bad request response has a 5xx status code
func (o *GetAPIV2ProjectsPinnedBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 projects pinned bad request response a status code equal to that given
func (o *GetAPIV2ProjectsPinnedBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v2 projects pinned bad request response
func (o *GetAPIV2ProjectsPinnedBadRequest) Code() int {
	return 400
}

func (o *GetAPIV2ProjectsPinnedBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/pinned][%d] getApiV2ProjectsPinnedBadRequest %s", 400, payload)
}

func (o *GetAPIV2ProjectsPinnedBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/pinned][%d] getApiV2ProjectsPinnedBadRequest %s", 400, payload)
}

func (o *GetAPIV2ProjectsPinnedBadRequest) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV2ProjectsPinnedBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV2ProjectsPinnedUnauthorized creates a GetAPIV2ProjectsPinnedUnauthorized with default headers values
func NewGetAPIV2ProjectsPinnedUnauthorized() *GetAPIV2ProjectsPinnedUnauthorized {
	return &GetAPIV2ProjectsPinnedUnauthorized{}
}

/*
GetAPIV2ProjectsPinnedUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAPIV2ProjectsPinnedUnauthorized struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v2 projects pinned unauthorized response has a 2xx status code
func (o *GetAPIV2ProjectsPinnedUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 projects pinned unauthorized response has a 3xx status code
func (o *GetAPIV2ProjectsPinnedUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 projects pinned unauthorized response has a 4xx status code
func (o *GetAPIV2ProjectsPinnedUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v2 projects pinned unauthorized response has a 5xx status code
func (o *GetAPIV2ProjectsPinnedUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 projects pinned unauthorized response a status code equal to that given
func (o *GetAPIV2ProjectsPinnedUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v2 projects pinned unauthorized response
func (o *GetAPIV2ProjectsPinnedUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV2ProjectsPinnedUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/pinned][%d] getApiV2ProjectsPinnedUnauthorized %s", 401, payload)
}

func (o *GetAPIV2ProjectsPinnedUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/pinned][%d] getApiV2ProjectsPinnedUnauthorized %s", 401, payload)
}

func (o *GetAPIV2ProjectsPinnedUnauthorized) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV2ProjectsPinnedUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV2ProjectsPinnedForbidden creates a GetAPIV2ProjectsPinnedForbidden with default headers values
func NewGetAPIV2ProjectsPinnedForbidden() *GetAPIV2ProjectsPinnedForbidden {
	return &GetAPIV2ProjectsPinnedForbidden{}
}

/*
GetAPIV2ProjectsPinnedForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAPIV2ProjectsPinnedForbidden struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v2 projects pinned forbidden response has a 2xx status code
func (o *GetAPIV2ProjectsPinnedForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 projects pinned forbidden response has a 3xx status code
func (o *GetAPIV2ProjectsPinnedForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 projects pinned forbidden response has a 4xx status code
func (o *GetAPIV2ProjectsPinnedForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v2 projects pinned forbidden response has a 5xx status code
func (o *GetAPIV2ProjectsPinnedForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 projects pinned forbidden response a status code equal to that given
func (o *GetAPIV2ProjectsPinnedForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v2 projects pinned forbidden response
func (o *GetAPIV2ProjectsPinnedForbidden) Code() int {
	return 403
}

func (o *GetAPIV2ProjectsPinnedForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/pinned][%d] getApiV2ProjectsPinnedForbidden %s", 403, payload)
}

func (o *GetAPIV2ProjectsPinnedForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/pinned][%d] getApiV2ProjectsPinnedForbidden %s", 403, payload)
}

func (o *GetAPIV2ProjectsPinnedForbidden) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV2ProjectsPinnedForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV2ProjectsPinnedNotFound creates a GetAPIV2ProjectsPinnedNotFound with default headers values
func NewGetAPIV2ProjectsPinnedNotFound() *GetAPIV2ProjectsPinnedNotFound {
	return &GetAPIV2ProjectsPinnedNotFound{}
}

/*
GetAPIV2ProjectsPinnedNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAPIV2ProjectsPinnedNotFound struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v2 projects pinned not found response has a 2xx status code
func (o *GetAPIV2ProjectsPinnedNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 projects pinned not found response has a 3xx status code
func (o *GetAPIV2ProjectsPinnedNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 projects pinned not found response has a 4xx status code
func (o *GetAPIV2ProjectsPinnedNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v2 projects pinned not found response has a 5xx status code
func (o *GetAPIV2ProjectsPinnedNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 projects pinned not found response a status code equal to that given
func (o *GetAPIV2ProjectsPinnedNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v2 projects pinned not found response
func (o *GetAPIV2ProjectsPinnedNotFound) Code() int {
	return 404
}

func (o *GetAPIV2ProjectsPinnedNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/pinned][%d] getApiV2ProjectsPinnedNotFound %s", 404, payload)
}

func (o *GetAPIV2ProjectsPinnedNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/pinned][%d] getApiV2ProjectsPinnedNotFound %s", 404, payload)
}

func (o *GetAPIV2ProjectsPinnedNotFound) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV2ProjectsPinnedNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV2ProjectsPinnedInternalServerError creates a GetAPIV2ProjectsPinnedInternalServerError with default headers values
func NewGetAPIV2ProjectsPinnedInternalServerError() *GetAPIV2ProjectsPinnedInternalServerError {
	return &GetAPIV2ProjectsPinnedInternalServerError{}
}

/*
GetAPIV2ProjectsPinnedInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetAPIV2ProjectsPinnedInternalServerError struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v2 projects pinned internal server error response has a 2xx status code
func (o *GetAPIV2ProjectsPinnedInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 projects pinned internal server error response has a 3xx status code
func (o *GetAPIV2ProjectsPinnedInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 projects pinned internal server error response has a 4xx status code
func (o *GetAPIV2ProjectsPinnedInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v2 projects pinned internal server error response has a 5xx status code
func (o *GetAPIV2ProjectsPinnedInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v2 projects pinned internal server error response a status code equal to that given
func (o *GetAPIV2ProjectsPinnedInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v2 projects pinned internal server error response
func (o *GetAPIV2ProjectsPinnedInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV2ProjectsPinnedInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/pinned][%d] getApiV2ProjectsPinnedInternalServerError %s", 500, payload)
}

func (o *GetAPIV2ProjectsPinnedInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/pinned][%d] getApiV2ProjectsPinnedInternalServerError %s", 500, payload)
}

func (o *GetAPIV2ProjectsPinnedInternalServerError) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV2ProjectsPinnedInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
