// Code generated by go-swagger; DO NOT EDIT.

package project

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.corp.mail.ru/ai/streamflow/backend/cplane/tests/private/models"
)

// GetAPIV2ProjectReader is a Reader for the GetAPIV2Project structure.
type GetAPIV2ProjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV2ProjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV2ProjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV2ProjectBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAPIV2ProjectUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAPIV2ProjectForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV2ProjectNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV2ProjectInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v2/project] GetAPIV2Project", response, response.Code())
	}
}

// NewGetAPIV2ProjectOK creates a GetAPIV2ProjectOK with default headers values
func NewGetAPIV2ProjectOK() *GetAPIV2ProjectOK {
	return &GetAPIV2ProjectOK{}
}

/*
GetAPIV2ProjectOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV2ProjectOK struct {
	Payload *models.ResponsesGetProjectV2Response
}

// IsSuccess returns true when this get Api v2 project o k response has a 2xx status code
func (o *GetAPIV2ProjectOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v2 project o k response has a 3xx status code
func (o *GetAPIV2ProjectOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 project o k response has a 4xx status code
func (o *GetAPIV2ProjectOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v2 project o k response has a 5xx status code
func (o *GetAPIV2ProjectOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 project o k response a status code equal to that given
func (o *GetAPIV2ProjectOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v2 project o k response
func (o *GetAPIV2ProjectOK) Code() int {
	return 200
}

func (o *GetAPIV2ProjectOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/project][%d] getApiV2ProjectOK %s", 200, payload)
}

func (o *GetAPIV2ProjectOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/project][%d] getApiV2ProjectOK %s", 200, payload)
}

func (o *GetAPIV2ProjectOK) GetPayload() *models.ResponsesGetProjectV2Response {
	return o.Payload
}

func (o *GetAPIV2ProjectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesGetProjectV2Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV2ProjectBadRequest creates a GetAPIV2ProjectBadRequest with default headers values
func NewGetAPIV2ProjectBadRequest() *GetAPIV2ProjectBadRequest {
	return &GetAPIV2ProjectBadRequest{}
}

/*
GetAPIV2ProjectBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAPIV2ProjectBadRequest struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v2 project bad request response has a 2xx status code
func (o *GetAPIV2ProjectBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 project bad request response has a 3xx status code
func (o *GetAPIV2ProjectBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 project bad request response has a 4xx status code
func (o *GetAPIV2ProjectBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v2 project bad request response has a 5xx status code
func (o *GetAPIV2ProjectBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 project bad request response a status code equal to that given
func (o *GetAPIV2ProjectBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v2 project bad request response
func (o *GetAPIV2ProjectBadRequest) Code() int {
	return 400
}

func (o *GetAPIV2ProjectBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/project][%d] getApiV2ProjectBadRequest %s", 400, payload)
}

func (o *GetAPIV2ProjectBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/project][%d] getApiV2ProjectBadRequest %s", 400, payload)
}

func (o *GetAPIV2ProjectBadRequest) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV2ProjectBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV2ProjectUnauthorized creates a GetAPIV2ProjectUnauthorized with default headers values
func NewGetAPIV2ProjectUnauthorized() *GetAPIV2ProjectUnauthorized {
	return &GetAPIV2ProjectUnauthorized{}
}

/*
GetAPIV2ProjectUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAPIV2ProjectUnauthorized struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v2 project unauthorized response has a 2xx status code
func (o *GetAPIV2ProjectUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 project unauthorized response has a 3xx status code
func (o *GetAPIV2ProjectUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 project unauthorized response has a 4xx status code
func (o *GetAPIV2ProjectUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v2 project unauthorized response has a 5xx status code
func (o *GetAPIV2ProjectUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 project unauthorized response a status code equal to that given
func (o *GetAPIV2ProjectUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v2 project unauthorized response
func (o *GetAPIV2ProjectUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV2ProjectUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/project][%d] getApiV2ProjectUnauthorized %s", 401, payload)
}

func (o *GetAPIV2ProjectUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/project][%d] getApiV2ProjectUnauthorized %s", 401, payload)
}

func (o *GetAPIV2ProjectUnauthorized) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV2ProjectUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV2ProjectForbidden creates a GetAPIV2ProjectForbidden with default headers values
func NewGetAPIV2ProjectForbidden() *GetAPIV2ProjectForbidden {
	return &GetAPIV2ProjectForbidden{}
}

/*
GetAPIV2ProjectForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAPIV2ProjectForbidden struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v2 project forbidden response has a 2xx status code
func (o *GetAPIV2ProjectForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 project forbidden response has a 3xx status code
func (o *GetAPIV2ProjectForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 project forbidden response has a 4xx status code
func (o *GetAPIV2ProjectForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v2 project forbidden response has a 5xx status code
func (o *GetAPIV2ProjectForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 project forbidden response a status code equal to that given
func (o *GetAPIV2ProjectForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v2 project forbidden response
func (o *GetAPIV2ProjectForbidden) Code() int {
	return 403
}

func (o *GetAPIV2ProjectForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/project][%d] getApiV2ProjectForbidden %s", 403, payload)
}

func (o *GetAPIV2ProjectForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/project][%d] getApiV2ProjectForbidden %s", 403, payload)
}

func (o *GetAPIV2ProjectForbidden) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV2ProjectForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV2ProjectNotFound creates a GetAPIV2ProjectNotFound with default headers values
func NewGetAPIV2ProjectNotFound() *GetAPIV2ProjectNotFound {
	return &GetAPIV2ProjectNotFound{}
}

/*
GetAPIV2ProjectNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAPIV2ProjectNotFound struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v2 project not found response has a 2xx status code
func (o *GetAPIV2ProjectNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 project not found response has a 3xx status code
func (o *GetAPIV2ProjectNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 project not found response has a 4xx status code
func (o *GetAPIV2ProjectNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v2 project not found response has a 5xx status code
func (o *GetAPIV2ProjectNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 project not found response a status code equal to that given
func (o *GetAPIV2ProjectNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v2 project not found response
func (o *GetAPIV2ProjectNotFound) Code() int {
	return 404
}

func (o *GetAPIV2ProjectNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/project][%d] getApiV2ProjectNotFound %s", 404, payload)
}

func (o *GetAPIV2ProjectNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/project][%d] getApiV2ProjectNotFound %s", 404, payload)
}

func (o *GetAPIV2ProjectNotFound) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV2ProjectNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV2ProjectInternalServerError creates a GetAPIV2ProjectInternalServerError with default headers values
func NewGetAPIV2ProjectInternalServerError() *GetAPIV2ProjectInternalServerError {
	return &GetAPIV2ProjectInternalServerError{}
}

/*
GetAPIV2ProjectInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetAPIV2ProjectInternalServerError struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v2 project internal server error response has a 2xx status code
func (o *GetAPIV2ProjectInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 project internal server error response has a 3xx status code
func (o *GetAPIV2ProjectInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 project internal server error response has a 4xx status code
func (o *GetAPIV2ProjectInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v2 project internal server error response has a 5xx status code
func (o *GetAPIV2ProjectInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v2 project internal server error response a status code equal to that given
func (o *GetAPIV2ProjectInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v2 project internal server error response
func (o *GetAPIV2ProjectInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV2ProjectInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/project][%d] getApiV2ProjectInternalServerError %s", 500, payload)
}

func (o *GetAPIV2ProjectInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/project][%d] getApiV2ProjectInternalServerError %s", 500, payload)
}

func (o *GetAPIV2ProjectInternalServerError) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV2ProjectInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
