// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"gitlab.corp.mail.ru/ai/streamflow/backend/cplane/tests/public/models"
)

// NewDeleteAPIV1ProjectParams creates a new DeleteAPIV1ProjectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIV1ProjectParams() *DeleteAPIV1ProjectParams {
	return &DeleteAPIV1ProjectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIV1ProjectParamsWithTimeout creates a new DeleteAPIV1ProjectParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIV1ProjectParamsWithTimeout(timeout time.Duration) *DeleteAPIV1ProjectParams {
	return &DeleteAPIV1ProjectParams{
		timeout: timeout,
	}
}

// NewDeleteAPIV1ProjectParamsWithContext creates a new DeleteAPIV1ProjectParams object
// with the ability to set a context for a request.
func NewDeleteAPIV1ProjectParamsWithContext(ctx context.Context) *DeleteAPIV1ProjectParams {
	return &DeleteAPIV1ProjectParams{
		Context: ctx,
	}
}

// NewDeleteAPIV1ProjectParamsWithHTTPClient creates a new DeleteAPIV1ProjectParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIV1ProjectParamsWithHTTPClient(client *http.Client) *DeleteAPIV1ProjectParams {
	return &DeleteAPIV1ProjectParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIV1ProjectParams contains all the parameters to send to the API endpoint

	for the delete API v1 project operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIV1ProjectParams struct {

	/* Request.

	   request body
	*/
	Request *models.RequestsDeleteProjectRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API v1 project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIV1ProjectParams) WithDefaults() *DeleteAPIV1ProjectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API v1 project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIV1ProjectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API v1 project params
func (o *DeleteAPIV1ProjectParams) WithTimeout(timeout time.Duration) *DeleteAPIV1ProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API v1 project params
func (o *DeleteAPIV1ProjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API v1 project params
func (o *DeleteAPIV1ProjectParams) WithContext(ctx context.Context) *DeleteAPIV1ProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API v1 project params
func (o *DeleteAPIV1ProjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API v1 project params
func (o *DeleteAPIV1ProjectParams) WithHTTPClient(client *http.Client) *DeleteAPIV1ProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API v1 project params
func (o *DeleteAPIV1ProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the delete API v1 project params
func (o *DeleteAPIV1ProjectParams) WithRequest(request *models.RequestsDeleteProjectRequest) *DeleteAPIV1ProjectParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the delete API v1 project params
func (o *DeleteAPIV1ProjectParams) SetRequest(request *models.RequestsDeleteProjectRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIV1ProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
