// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.corp.mail.ru/ai/streamflow/backend/cplane/tests/public/models"
)

// DeleteAPIV1ProjectReader is a Reader for the DeleteAPIV1Project structure.
type DeleteAPIV1ProjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIV1ProjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAPIV1ProjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAPIV1ProjectBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteAPIV1ProjectUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteAPIV1ProjectForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAPIV1ProjectNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAPIV1ProjectInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/v1/project] DeleteAPIV1Project", response, response.Code())
	}
}

// NewDeleteAPIV1ProjectOK creates a DeleteAPIV1ProjectOK with default headers values
func NewDeleteAPIV1ProjectOK() *DeleteAPIV1ProjectOK {
	return &DeleteAPIV1ProjectOK{}
}

/*
DeleteAPIV1ProjectOK describes a response with status code 200, with default header values.

OK
*/
type DeleteAPIV1ProjectOK struct {
}

// IsSuccess returns true when this delete Api v1 project o k response has a 2xx status code
func (o *DeleteAPIV1ProjectOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api v1 project o k response has a 3xx status code
func (o *DeleteAPIV1ProjectOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v1 project o k response has a 4xx status code
func (o *DeleteAPIV1ProjectOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api v1 project o k response has a 5xx status code
func (o *DeleteAPIV1ProjectOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api v1 project o k response a status code equal to that given
func (o *DeleteAPIV1ProjectOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete Api v1 project o k response
func (o *DeleteAPIV1ProjectOK) Code() int {
	return 200
}

func (o *DeleteAPIV1ProjectOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/project][%d] deleteApiV1ProjectOK", 200)
}

func (o *DeleteAPIV1ProjectOK) String() string {
	return fmt.Sprintf("[DELETE /api/v1/project][%d] deleteApiV1ProjectOK", 200)
}

func (o *DeleteAPIV1ProjectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV1ProjectBadRequest creates a DeleteAPIV1ProjectBadRequest with default headers values
func NewDeleteAPIV1ProjectBadRequest() *DeleteAPIV1ProjectBadRequest {
	return &DeleteAPIV1ProjectBadRequest{}
}

/*
DeleteAPIV1ProjectBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteAPIV1ProjectBadRequest struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this delete Api v1 project bad request response has a 2xx status code
func (o *DeleteAPIV1ProjectBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete Api v1 project bad request response has a 3xx status code
func (o *DeleteAPIV1ProjectBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v1 project bad request response has a 4xx status code
func (o *DeleteAPIV1ProjectBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete Api v1 project bad request response has a 5xx status code
func (o *DeleteAPIV1ProjectBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api v1 project bad request response a status code equal to that given
func (o *DeleteAPIV1ProjectBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete Api v1 project bad request response
func (o *DeleteAPIV1ProjectBadRequest) Code() int {
	return 400
}

func (o *DeleteAPIV1ProjectBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/project][%d] deleteApiV1ProjectBadRequest %s", 400, payload)
}

func (o *DeleteAPIV1ProjectBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/project][%d] deleteApiV1ProjectBadRequest %s", 400, payload)
}

func (o *DeleteAPIV1ProjectBadRequest) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *DeleteAPIV1ProjectBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAPIV1ProjectUnauthorized creates a DeleteAPIV1ProjectUnauthorized with default headers values
func NewDeleteAPIV1ProjectUnauthorized() *DeleteAPIV1ProjectUnauthorized {
	return &DeleteAPIV1ProjectUnauthorized{}
}

/*
DeleteAPIV1ProjectUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteAPIV1ProjectUnauthorized struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this delete Api v1 project unauthorized response has a 2xx status code
func (o *DeleteAPIV1ProjectUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete Api v1 project unauthorized response has a 3xx status code
func (o *DeleteAPIV1ProjectUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v1 project unauthorized response has a 4xx status code
func (o *DeleteAPIV1ProjectUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete Api v1 project unauthorized response has a 5xx status code
func (o *DeleteAPIV1ProjectUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api v1 project unauthorized response a status code equal to that given
func (o *DeleteAPIV1ProjectUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete Api v1 project unauthorized response
func (o *DeleteAPIV1ProjectUnauthorized) Code() int {
	return 401
}

func (o *DeleteAPIV1ProjectUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/project][%d] deleteApiV1ProjectUnauthorized %s", 401, payload)
}

func (o *DeleteAPIV1ProjectUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/project][%d] deleteApiV1ProjectUnauthorized %s", 401, payload)
}

func (o *DeleteAPIV1ProjectUnauthorized) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *DeleteAPIV1ProjectUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAPIV1ProjectForbidden creates a DeleteAPIV1ProjectForbidden with default headers values
func NewDeleteAPIV1ProjectForbidden() *DeleteAPIV1ProjectForbidden {
	return &DeleteAPIV1ProjectForbidden{}
}

/*
DeleteAPIV1ProjectForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteAPIV1ProjectForbidden struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this delete Api v1 project forbidden response has a 2xx status code
func (o *DeleteAPIV1ProjectForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete Api v1 project forbidden response has a 3xx status code
func (o *DeleteAPIV1ProjectForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v1 project forbidden response has a 4xx status code
func (o *DeleteAPIV1ProjectForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete Api v1 project forbidden response has a 5xx status code
func (o *DeleteAPIV1ProjectForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api v1 project forbidden response a status code equal to that given
func (o *DeleteAPIV1ProjectForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete Api v1 project forbidden response
func (o *DeleteAPIV1ProjectForbidden) Code() int {
	return 403
}

func (o *DeleteAPIV1ProjectForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/project][%d] deleteApiV1ProjectForbidden %s", 403, payload)
}

func (o *DeleteAPIV1ProjectForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/project][%d] deleteApiV1ProjectForbidden %s", 403, payload)
}

func (o *DeleteAPIV1ProjectForbidden) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *DeleteAPIV1ProjectForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAPIV1ProjectNotFound creates a DeleteAPIV1ProjectNotFound with default headers values
func NewDeleteAPIV1ProjectNotFound() *DeleteAPIV1ProjectNotFound {
	return &DeleteAPIV1ProjectNotFound{}
}

/*
DeleteAPIV1ProjectNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteAPIV1ProjectNotFound struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this delete Api v1 project not found response has a 2xx status code
func (o *DeleteAPIV1ProjectNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete Api v1 project not found response has a 3xx status code
func (o *DeleteAPIV1ProjectNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v1 project not found response has a 4xx status code
func (o *DeleteAPIV1ProjectNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete Api v1 project not found response has a 5xx status code
func (o *DeleteAPIV1ProjectNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api v1 project not found response a status code equal to that given
func (o *DeleteAPIV1ProjectNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete Api v1 project not found response
func (o *DeleteAPIV1ProjectNotFound) Code() int {
	return 404
}

func (o *DeleteAPIV1ProjectNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/project][%d] deleteApiV1ProjectNotFound %s", 404, payload)
}

func (o *DeleteAPIV1ProjectNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/project][%d] deleteApiV1ProjectNotFound %s", 404, payload)
}

func (o *DeleteAPIV1ProjectNotFound) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *DeleteAPIV1ProjectNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAPIV1ProjectInternalServerError creates a DeleteAPIV1ProjectInternalServerError with default headers values
func NewDeleteAPIV1ProjectInternalServerError() *DeleteAPIV1ProjectInternalServerError {
	return &DeleteAPIV1ProjectInternalServerError{}
}

/*
DeleteAPIV1ProjectInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type DeleteAPIV1ProjectInternalServerError struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this delete Api v1 project internal server error response has a 2xx status code
func (o *DeleteAPIV1ProjectInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete Api v1 project internal server error response has a 3xx status code
func (o *DeleteAPIV1ProjectInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v1 project internal server error response has a 4xx status code
func (o *DeleteAPIV1ProjectInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api v1 project internal server error response has a 5xx status code
func (o *DeleteAPIV1ProjectInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete Api v1 project internal server error response a status code equal to that given
func (o *DeleteAPIV1ProjectInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete Api v1 project internal server error response
func (o *DeleteAPIV1ProjectInternalServerError) Code() int {
	return 500
}

func (o *DeleteAPIV1ProjectInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/project][%d] deleteApiV1ProjectInternalServerError %s", 500, payload)
}

func (o *DeleteAPIV1ProjectInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/project][%d] deleteApiV1ProjectInternalServerError %s", 500, payload)
}

func (o *DeleteAPIV1ProjectInternalServerError) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *DeleteAPIV1ProjectInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
