// Code generated by go-swagger; DO NOT EDIT.

package rule

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.corp.mail.ru/ai/streamflow/backend/cplane/tests/private/models"
)

// PostAPIV1RuleReader is a Reader for the PostAPIV1Rule structure.
type PostAPIV1RuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1RuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1RuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1RuleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1RuleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIV1RuleForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPIV1RuleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1RuleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/rule] PostAPIV1Rule", response, response.Code())
	}
}

// NewPostAPIV1RuleOK creates a PostAPIV1RuleOK with default headers values
func NewPostAPIV1RuleOK() *PostAPIV1RuleOK {
	return &PostAPIV1RuleOK{}
}

/*
PostAPIV1RuleOK describes a response with status code 200, with default header values.

OK
*/
type PostAPIV1RuleOK struct {
	Payload *models.ResponsesCreateRuleResponse
}

// IsSuccess returns true when this post Api v1 rule o k response has a 2xx status code
func (o *PostAPIV1RuleOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 rule o k response has a 3xx status code
func (o *PostAPIV1RuleOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 rule o k response has a 4xx status code
func (o *PostAPIV1RuleOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 rule o k response has a 5xx status code
func (o *PostAPIV1RuleOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 rule o k response a status code equal to that given
func (o *PostAPIV1RuleOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 rule o k response
func (o *PostAPIV1RuleOK) Code() int {
	return 200
}

func (o *PostAPIV1RuleOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/rule][%d] postApiV1RuleOK %s", 200, payload)
}

func (o *PostAPIV1RuleOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/rule][%d] postApiV1RuleOK %s", 200, payload)
}

func (o *PostAPIV1RuleOK) GetPayload() *models.ResponsesCreateRuleResponse {
	return o.Payload
}

func (o *PostAPIV1RuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesCreateRuleResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1RuleBadRequest creates a PostAPIV1RuleBadRequest with default headers values
func NewPostAPIV1RuleBadRequest() *PostAPIV1RuleBadRequest {
	return &PostAPIV1RuleBadRequest{}
}

/*
PostAPIV1RuleBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAPIV1RuleBadRequest struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this post Api v1 rule bad request response has a 2xx status code
func (o *PostAPIV1RuleBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 rule bad request response has a 3xx status code
func (o *PostAPIV1RuleBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 rule bad request response has a 4xx status code
func (o *PostAPIV1RuleBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 rule bad request response has a 5xx status code
func (o *PostAPIV1RuleBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 rule bad request response a status code equal to that given
func (o *PostAPIV1RuleBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 rule bad request response
func (o *PostAPIV1RuleBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1RuleBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/rule][%d] postApiV1RuleBadRequest %s", 400, payload)
}

func (o *PostAPIV1RuleBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/rule][%d] postApiV1RuleBadRequest %s", 400, payload)
}

func (o *PostAPIV1RuleBadRequest) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *PostAPIV1RuleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1RuleUnauthorized creates a PostAPIV1RuleUnauthorized with default headers values
func NewPostAPIV1RuleUnauthorized() *PostAPIV1RuleUnauthorized {
	return &PostAPIV1RuleUnauthorized{}
}

/*
PostAPIV1RuleUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostAPIV1RuleUnauthorized struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this post Api v1 rule unauthorized response has a 2xx status code
func (o *PostAPIV1RuleUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 rule unauthorized response has a 3xx status code
func (o *PostAPIV1RuleUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 rule unauthorized response has a 4xx status code
func (o *PostAPIV1RuleUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 rule unauthorized response has a 5xx status code
func (o *PostAPIV1RuleUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 rule unauthorized response a status code equal to that given
func (o *PostAPIV1RuleUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 rule unauthorized response
func (o *PostAPIV1RuleUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1RuleUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/rule][%d] postApiV1RuleUnauthorized %s", 401, payload)
}

func (o *PostAPIV1RuleUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/rule][%d] postApiV1RuleUnauthorized %s", 401, payload)
}

func (o *PostAPIV1RuleUnauthorized) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *PostAPIV1RuleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1RuleForbidden creates a PostAPIV1RuleForbidden with default headers values
func NewPostAPIV1RuleForbidden() *PostAPIV1RuleForbidden {
	return &PostAPIV1RuleForbidden{}
}

/*
PostAPIV1RuleForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PostAPIV1RuleForbidden struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this post Api v1 rule forbidden response has a 2xx status code
func (o *PostAPIV1RuleForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 rule forbidden response has a 3xx status code
func (o *PostAPIV1RuleForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 rule forbidden response has a 4xx status code
func (o *PostAPIV1RuleForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 rule forbidden response has a 5xx status code
func (o *PostAPIV1RuleForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 rule forbidden response a status code equal to that given
func (o *PostAPIV1RuleForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post Api v1 rule forbidden response
func (o *PostAPIV1RuleForbidden) Code() int {
	return 403
}

func (o *PostAPIV1RuleForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/rule][%d] postApiV1RuleForbidden %s", 403, payload)
}

func (o *PostAPIV1RuleForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/rule][%d] postApiV1RuleForbidden %s", 403, payload)
}

func (o *PostAPIV1RuleForbidden) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *PostAPIV1RuleForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1RuleNotFound creates a PostAPIV1RuleNotFound with default headers values
func NewPostAPIV1RuleNotFound() *PostAPIV1RuleNotFound {
	return &PostAPIV1RuleNotFound{}
}

/*
PostAPIV1RuleNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PostAPIV1RuleNotFound struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this post Api v1 rule not found response has a 2xx status code
func (o *PostAPIV1RuleNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 rule not found response has a 3xx status code
func (o *PostAPIV1RuleNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 rule not found response has a 4xx status code
func (o *PostAPIV1RuleNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 rule not found response has a 5xx status code
func (o *PostAPIV1RuleNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 rule not found response a status code equal to that given
func (o *PostAPIV1RuleNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post Api v1 rule not found response
func (o *PostAPIV1RuleNotFound) Code() int {
	return 404
}

func (o *PostAPIV1RuleNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/rule][%d] postApiV1RuleNotFound %s", 404, payload)
}

func (o *PostAPIV1RuleNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/rule][%d] postApiV1RuleNotFound %s", 404, payload)
}

func (o *PostAPIV1RuleNotFound) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *PostAPIV1RuleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1RuleInternalServerError creates a PostAPIV1RuleInternalServerError with default headers values
func NewPostAPIV1RuleInternalServerError() *PostAPIV1RuleInternalServerError {
	return &PostAPIV1RuleInternalServerError{}
}

/*
PostAPIV1RuleInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PostAPIV1RuleInternalServerError struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this post Api v1 rule internal server error response has a 2xx status code
func (o *PostAPIV1RuleInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 rule internal server error response has a 3xx status code
func (o *PostAPIV1RuleInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 rule internal server error response has a 4xx status code
func (o *PostAPIV1RuleInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 rule internal server error response has a 5xx status code
func (o *PostAPIV1RuleInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 rule internal server error response a status code equal to that given
func (o *PostAPIV1RuleInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 rule internal server error response
func (o *PostAPIV1RuleInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1RuleInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/rule][%d] postApiV1RuleInternalServerError %s", 500, payload)
}

func (o *PostAPIV1RuleInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/rule][%d] postApiV1RuleInternalServerError %s", 500, payload)
}

func (o *PostAPIV1RuleInternalServerError) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *PostAPIV1RuleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
