/* eslint-disable @typescript-eslint/no-var-requires */
const twColors = require('tailwindcss/colors');

delete twColors['lightBlue'];
delete twColors['warmGray'];
delete twColors['trueGray'];
delete twColors['coolGray'];
delete twColors['blueGray'];

const rem = (px) => `${px / 16}rem`;

const range = (from, to, step) => {
  const arr = [from];
  let last_el = arr[arr.length - 1];
  while (last_el < to) {
    arr.push(last_el + step);
    last_el = arr[arr.length - 1];
  }
  return arr;
};

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{html,js,jsx,ts,tsx}'],
  theme: {
    extend: {
      boxShadow: {
        '2xl': '0 8px 20px 0 rgba(0, 0, 0, 0.15)',
      },
      minHeight: {
        ...range(0, 100, 0.5).reduce((acc, spacing) => {
          acc[spacing] = rem(spacing * 4);
          return acc;
        }, {}),
      },
      minWidth: {
        ...range(0, 100, 0.5).reduce((acc, spacing) => {
          acc[spacing] = rem(spacing * 4);
          return acc;
        }, {}),
      },
      spacing: {
        ...range(0, 100, 0.5).reduce((acc, spacing) => {
          acc[spacing] = rem(spacing * 4);
          return acc;
        }, {}),
      },
      borderRadius: {
        inherit: 'inherit',
      },
      lineHeight: {
        0: '0',
      },
      width: {
        inherit: 'inherit',
        34: '8.5rem',
      },
      maxWidth: {
        inherit: 'inherit',
      },
      height: {
        inherit: 'inherit',
      },
      maxHeight: {
        inherit: 'inherit',
      },
      keyframes: {
        'fade-out': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-in': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
      },
      animation: {
        'fade-out': 'fade-out 1s linear forwards',
      },
      padding: {
        inherit: 'inherit',
      },
    },
    corePlugins: {
      preflight: false,
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      white: {
        50: 'var(--color-white-50)',
        70: 'var(--color-white-70)',
        100: 'var(--color-white-100)',
        150: 'var(--color-white-150)',
        200: 'var(--color-white-200)',
        250: 'var(--color-white-250)',
        300: 'var(--color-white-300)',
        350: 'var(--color-white-350)',
        400: 'var(--color-white-400)',
        450: 'var(--color-white-450)',
        500: 'var(--color-white-500)',
        550: 'var(--color-white-550)',
        600: 'var(--color-white-600)',
        650: 'var(--color-white-650)',
        700: 'var(--color-white-700)',
        750: 'var(--color-white-750)',
        800: 'var(--color-white-800)',
        850: 'var(--color-white-850)',
        900: 'var(--color-white-900)',
        950: 'var(--color-white-950)',
        solid: {
          50: 'var(--color-white-50-solid)',
          70: 'var(--color-white-70-solid)',
          100: 'var(--color-white-100-solid)',
          150: 'var(--color-white-150-solid)',
          200: 'var(--color-white-200-solid)',
          250: 'var(--color-white-250-solid)',
          300: 'var(--color-white-300-solid)',
          350: 'var(--color-white-350-solid)',
          400: 'var(--color-white-400-solid)',
          450: 'var(--color-white-450-solid)',
          500: 'var(--color-white-500-solid)',
          550: 'var(--color-white-550-solid)',
          600: 'var(--color-white-600-solid)',
          650: 'var(--color-white-650-solid)',
          700: 'var(--color-white-700-solid)',
          750: 'var(--color-white-750-solid)',
          800: 'var(--color-white-800-solid)',
          850: 'var(--color-white-850-solid)',
          900: 'var(--color-white-900-solid)',
          950: 'var(--color-white-950-solid)',
          1000: 'var(--color-white-1000-solid)',
        },
        dynamic: {
          1000: 'var(--color-white-dynamic-1000-solid)',
        },
      },
      black: {
        50: 'var(--color-black-50)',
        70: 'var(--color-black-70)',
        100: 'var(--color-black-100)',
        150: 'var(--color-black-150)',
        200: 'var(--color-black-200)',
        250: 'var(--color-black-250)',
        300: 'var(--color-black-300)',
        350: 'var(--color-black-350)',
        400: 'var(--color-black-400)',
        450: 'var(--color-black-450)',
        500: 'var(--color-black-500)',
        550: 'var(--color-black-550)',
        600: 'var(--color-black-600)',
        650: 'var(--color-black-650)',
        700: 'var(--color-black-700)',
        750: 'var(--color-black-750)',
        800: 'var(--color-black-800)',
        850: 'var(--color-black-850)',
        900: 'var(--color-black-900)',
        950: 'var(--color-black-950)',
        solid: {
          20: 'var(--color-black-20-solid)',
          50: 'var(--color-black-50-solid)',
          100: 'var(--color-black-100-solid)',
          150: 'var(--color-black-150-solid)',
          200: 'var(--color-black-200-solid)',
          250: 'var(--color-black-250-solid)',
          300: 'var(--color-black-300-solid)',
          350: 'var(--color-black-350-solid)',
          400: 'var(--color-black-400-solid)',
          450: 'var(--color-black-450-solid)',
          500: 'var(--color-black-500-solid)',
          550: 'var(--color-black-550-solid)',
          600: 'var(--color-black-600-solid)',
          650: 'var(--color-black-650-solid)',
          700: 'var(--color-black-700-solid)',
          750: 'var(--color-black-750-solid)',
          800: 'var(--color-black-800-solid)',
          850: 'var(--color-black-850-solid)',
          900: 'var(--color-black-900-solid)',
          950: 'var(--color-black-950-solid)',
          1000: 'var(--color-black-1000-solid)',
        },
      },
      blue: {
        50: 'var(--color-blue-50)',
        100: 'var(--color-blue-100)',
        150: 'var(--color-blue-150)',
        200: 'var(--color-blue-200)',
        250: 'var(--color-blue-250)',
        300: 'var(--color-blue-300)',
        350: 'var(--color-blue-350)',
        400: 'var(--color-blue-400)',
        450: 'var(--color-blue-450)',
        500: 'var(--color-blue-500)',
        600: 'var(--color-blue-600)',
        800: 'var(--color-blue-800)',
        900: 'var(--color-blue-900)',
        1000: 'var(--color-blue-1000)',
        solid: {
          50: 'var(--color-blue-50-solid)',
          100: 'var(--color-blue-100-solid)',
          150: 'var(--color-blue-150-solid)',
          200: 'var(--color-blue-200-solid)',
          250: 'var(--color-blue-250-solid)',
          300: 'var(--color-blue-300-solid)',
          350: 'var(--color-blue-350-solid)',
          400: 'var(--color-blue-400-solid)',
          450: 'var(--color-blue-450-solid)',
          500: 'var(--color-blue-500-solid)',
          550: 'var(--color-blue-550-solid)',
          600: 'var(--color-blue-600-solid)',
          650: 'var(--color-blue-650-solid)',
          700: 'var(--color-blue-700-solid)',
          750: 'var(--color-blue-750-solid)',
          800: 'var(--color-blue-800-solid)',
          850: 'var(--color-blue-850-solid)',
          900: 'var(--color-blue-900-solid)',
          950: 'var(--color-blue-950-solid)',
          1000: 'var(--color-blue-1000-solid)',
        },
      },
      green: {
        50: 'var(--color-green-50)',
        100: 'var(--color-green-100)',
        150: 'var(--color-green-150)',
        200: 'var(--color-green-200)',
        250: 'var(--color-green-250)',
        300: 'var(--color-green-300)',
        350: 'var(--color-green-350)',
        400: 'var(--color-green-400)',
        450: 'var(--color-green-450)',
        500: 'var(--color-green-500)',
        solid: {
          50: 'var(--color-green-50-solid)',
          100: 'var(--color-green-100-solid)',
          150: 'var(--color-green-150-solid)',
          200: 'var(--color-green-200-solid)',
          250: 'var(--color-green-250-solid)',
          300: 'var(--color-green-300-solid)',
          350: 'var(--color-green-350-solid)',
          400: 'var(--color-green-400-solid)',
          450: 'var(--color-green-450-solid)',
          500: 'var(--color-green-500-solid)',
          550: 'var(--color-green-550-solid)',
          600: 'var(--color-green-600-solid)',
          650: 'var(--color-green-650-solid)',
          700: 'var(--color-green-700-solid)',
          750: 'var(--color-green-750-solid)',
          800: 'var(--color-green-800-solid)',
          850: 'var(--color-green-850-solid)',
          900: 'var(--color-green-900-solid)',
          950: 'var(--color-green-950-solid)',
          1000: 'var(--color-green-1000-solid)',
        },
      },
      yellow: {
        50: 'var(--color-yellow-50)',
        100: 'var(--color-yellow-100)',
        150: 'var(--color-yellow-150)',
        200: 'var(--color-yellow-200)',
        250: 'var(--color-yellow-250)',
        300: 'var(--color-yellow-300)',
        350: 'var(--color-yellow-350)',
        400: 'var(--color-yellow-400)',
        450: 'var(--color-yellow-450)',
        500: 'var(--color-yellow-500)',
        solid: {
          50: 'var(--color-yellow-50-solid)',
          100: 'var(--color-yellow-100-solid)',
          150: 'var(--color-yellow-150-solid)',
          200: 'var(--color-yellow-200-solid)',
          250: 'var(--color-yellow-250-solid)',
          300: 'var(--color-yellow-300-solid)',
          350: 'var(--color-yellow-350-solid)',
          400: 'var(--color-yellow-400-solid)',
          450: 'var(--color-yellow-450-solid)',
          500: 'var(--color-yellow-500-solid)',
          550: 'var(--color-yellow-550-solid)',
          600: 'var(--color-yellow-600-solid)',
          650: 'var(--color-yellow-650-solid)',
          700: 'var(--color-yellow-700-solid)',
          750: 'var(--color-yellow-750-solid)',
          800: 'var(--color-yellow-800-solid)',
          850: 'var(--color-yellow-850-solid)',
          900: 'var(--color-yellow-900-solid)',
          950: 'var(--color-yellow-950-solid)',
          1000: 'var(--color-yellow-1000-solid)',
        },
      },
      orange: {
        50: 'var(--color-orange-50)',
        100: 'var(--color-orange-100)',
        150: 'var(--color-orange-150)',
        200: 'var(--color-orange-200)',
        250: 'var(--color-orange-250)',
        300: 'var(--color-orange-300)',
        350: 'var(--color-orange-350)',
        400: 'var(--color-orange-400)',
        450: 'var(--color-orange-450)',
        500: 'var(--color-orange-500)',
        solid: {
          50: 'var(--color-orange-50-solid)',
          100: 'var(--color-orange-100-solid)',
          150: 'var(--color-orange-150-solid)',
          200: 'var(--color-orange-200-solid)',
          250: 'var(--color-orange-250-solid)',
          300: 'var(--color-orange-300-solid)',
          350: 'var(--color-orange-350-solid)',
          400: 'var(--color-orange-400-solid)',
          450: 'var(--color-orange-450-solid)',
          500: 'var(--color-orange-500-solid)',
          550: 'var(--color-orange-550-solid)',
          600: 'var(--color-orange-600-solid)',
          650: 'var(--color-orange-650-solid)',
          700: 'var(--color-orange-700-solid)',
          750: 'var(--color-orange-750-solid)',
          800: 'var(--color-orange-800-solid)',
          850: 'var(--color-orange-850-solid)',
          900: 'var(--color-orange-900-solid)',
          950: 'var(--color-orange-950-solid)',
          1000: 'var(--color-orange-1000-solid)',
        },
      },
      red: {
        50: 'var(--color-red-50)',
        100: 'var(--color-red-100)',
        150: 'var(--color-red-150)',
        200: 'var(--color-red-200)',
        250: 'var(--color-red-250)',
        300: 'var(--color-red-300)',
        350: 'var(--color-red-350)',
        400: 'var(--color-red-400)',
        450: 'var(--color-red-450)',
        500: 'var(--color-red-500)',
        solid: {
          50: 'var(--color-red-50-solid)',
          100: 'var(--color-red-100-solid)',
          150: 'var(--color-red-150-solid)',
          200: 'var(--color-red-200-solid)',
          250: 'var(--color-red-250-solid)',
          300: 'var(--color-red-300-solid)',
          350: 'var(--color-red-350-solid)',
          400: 'var(--color-red-400-solid)',
          450: 'var(--color-red-450-solid)',
          500: 'var(--color-red-500-solid)',
          550: 'var(--color-red-550-solid)',
          600: 'var(--color-red-600-solid)',
          650: 'var(--color-red-650-solid)',
          700: 'var(--color-red-700-solid)',
          750: 'var(--color-red-750-solid)',
          800: 'var(--color-red-800-solid)',
          850: 'var(--color-red-850-solid)',
          900: 'var(--color-red-900-solid)',
          950: 'var(--color-red-950-solid)',
          1000: 'var(--color-red-1000-solid)',
        },
      },
      purple: {
        50: 'var(--color-purple-50)',
        100: 'var(--color-purple-100)',
        150: 'var(--color-purple-150)',
        200: 'var(--color-purple-200)',
        250: 'var(--color-purple-250)',
        300: 'var(--color-purple-300)',
        350: 'var(--color-purple-350)',
        400: 'var(--color-purple-400)',
        450: 'var(--color-purple-450)',
        500: 'var(--color-purple-500)',
        solid: {
          50: 'var(--color-purple-50-solid)',
          100: 'var(--color-purple-100-solid)',
          150: 'var(--color-purple-150-solid)',
          200: 'var(--color-purple-200-solid)',
          250: 'var(--color-purple-250-solid)',
          300: 'var(--color-purple-300-solid)',
          350: 'var(--color-purple-350-solid)',
          400: 'var(--color-purple-400-solid)',
          450: 'var(--color-purple-450-solid)',
          500: 'var(--color-purple-500-solid)',
          550: 'var(--color-purple-550-solid)',
          600: 'var(--color-purple-600-solid)',
          650: 'var(--color-purple-650-solid)',
          700: 'var(--color-purple-700-solid)',
          750: 'var(--color-purple-750-solid)',
          800: 'var(--color-purple-800-solid)',
          850: 'var(--color-purple-850-solid)',
          900: 'var(--color-purple-900-solid)',
          950: 'var(--color-purple-950-solid)',
          1000: 'var(--color-purple-1000-solid)',
        },
      },
      'cool-grey': {
        50: 'var(--color-cool-grey-50)',
        100: 'var(--color-cool-grey-100)',
        150: 'var(--color-cool-grey-150)',
        200: 'var(--color-cool-grey-200)',
        250: 'var(--color-cool-grey-250)',
        300: 'var(--color-cool-grey-300)',
        350: 'var(--color-cool-grey-350)',
        400: 'var(--color-cool-grey-400)',
        450: 'var(--color-cool-grey-450)',
        500: 'var(--color-cool-grey-500)',
        solid: {
          50: 'var(--color-cool-grey-50-solid)',
          100: 'var(--color-cool-grey-100-solid)',
          150: 'var(--color-cool-grey-150-solid)',
          200: 'var(--color-cool-grey-200-solid)',
          250: 'var(--color-cool-grey-250-solid)',
          300: 'var(--color-cool-grey-300-solid)',
          350: 'var(--color-cool-grey-350-solid)',
          400: 'var(--color-cool-grey-400-solid)',
          450: 'var(--color-cool-grey-450-solid)',
          500: 'var(--color-cool-grey-500-solid)',
          550: 'var(--color-cool-grey-550-solid)',
          600: 'var(--color-cool-grey-600-solid)',
          650: 'var(--color-cool-grey-650-solid)',
          700: 'var(--color-cool-grey-700-solid)',
          750: 'var(--color-cool-grey-750-solid)',
          800: 'var(--color-cool-grey-800-solid)',
          850: 'var(--color-cool-grey-850-solid)',
          900: 'var(--color-cool-grey-900-solid)',
          950: 'var(--color-cool-grey-950-solid)',
          1000: 'var(--color-cool-grey-1000-solid)',
        },
      },
      uikit: {
        'text-primary': 'var(--g-color-text-primary)',
        'text-complementary': 'var(--g-color-text-complementary)',
        'text-secondary': 'var(--g-color-text-secondary)',
        'text-hint': 'var(--g-color-text-hint)',
        'text-info': 'var(--g-color-text-info)',
        'text-positive': 'var(--g-color-text-positive)',
        'text-warning': 'var(--g-color-text-warning)',
        'text-danger': 'var(--g-color-text-danger)',
        'text-utility': 'var(--g-color-text-utility)',
        'text-misc': 'var(--g-color-text-misc)',
        'text-info-heavy': 'var(--g-color-text-info-heavy)',
        'text-positive-heavy': 'var(--g-color-text-positive-heavy)',
        'text-warning-heavy': 'var(--g-color-text-warning-heavy)',
        'text-danger-heavy': 'var(--g-color-text-danger-heavy)',
        'text-utility-heavy': 'var(--g-color-text-utility-heavy)',
        'text-misc-heavy': 'var(--g-color-text-misc-heavy)',
        'text-brand': 'var(--g-color-text-brand)',
        'text-brand-heavy': 'var(--g-color-text-brand-heavy)',
        'text-brand-contrast': 'var(--g-color-text-brand-contrast)',
        'text-link': 'var(--g-color-text-link)',
        'text-link-hover': 'var(--g-color-text-link-hover)',
        'text-link-visited': 'var(--g-color-text-link-visited)',
        'text-link-visited-hover': 'var(--g-color-text-link-visited-hover)',
        'text-dark-primary': 'var(--g-color-text-dark-primary)',
        'text-dark-complementary': 'var(--g-color-text-dark-complementary)',
        'text-dark-secondary': 'var(--g-color-text-dark-secondary)',
        'text-dark-hint': 'var(--g-color-text-dark-hint)',
        'text-light-primary': 'var(--g-color-text-light-primary)',
        'text-light-complementary': 'var(--g-color-text-light-complementary)',
        'text-light-secondary': 'var(--g-color-text-light-secondary)',
        'text-light-hint': 'var(--g-color-text-light-hint)',
        'text-inverted-primary': 'var(--g-color-text-inverted-primary)',
        'text-inverted-complementary':
          'var(--g-color-text-inverted-complementary)',
        'text-inverted-secondary': 'var(--g-color-text-inverted-secondary)',
        'text-inverted-hint': 'var(--g-color-text-inverted-hint)',
        'base-background': 'var(--g-color-base-background)',
        'base-generic': 'var(--g-color-base-generic)',
        'base-generic-hover': 'var(--g-color-base-generic-hover)',
        'base-generic-medium': 'var(--g-color-base-generic-medium)',
        'base-generic-medium-hover': 'var(--g-color-base-generic-medium-hover)',
        'base-generic-accent': 'var(--g-color-base-generic-accent)',
        'base-generic-accent-disabled':
          'var(--g-color-base-generic-accent-disabled)',
        'base-generic-ultralight': 'var(--g-color-base-generic-ultralight)',
        'base-simple-hover': 'var(--g-color-base-simple-hover)',
        'base-simple-hover-solid': 'var(--g-color-base-simple-hover-solid)',
        'base-brand': 'var(--g-color-base-brand)',
        'base-brand-hover': 'var(--g-color-base-brand-hover)',
        'base-selection': 'var(--g-color-base-selection)',
        'base-selection-hover': 'var(--g-color-base-selection-hover)',
        'base-info-light': 'var(--g-color-base-info-light)',
        'base-info-light-hover': 'var(--g-color-base-info-light-hover)',
        'base-info-medium': 'var(--g-color-base-info-medium)',
        'base-info-medium-hover': 'var(--g-color-base-info-medium-hover)',
        'base-info-heavy': 'var(--g-color-base-info-heavy)',
        'base-info-heavy-hover': 'var(--g-color-base-info-heavy-hover)',
        'base-positive-light': 'var(--g-color-base-positive-light)',
        'base-positive-light-hover': 'var(--g-color-base-positive-light-hover)',
        'base-positive-medium': 'var(--g-color-base-positive-medium)',
        'base-positive-medium-hover':
          'var(--g-color-base-positive-medium-hover)',
        'base-positive-heavy': 'var(--g-color-base-positive-heavy)',
        'base-positive-heavy-hover': 'var(--g-color-base-positive-heavy-hover)',
        'base-warning-light': 'var(--g-color-base-warning-light)',
        'base-warning-light-hover': 'var(--g-color-base-warning-light-hover)',
        'base-warning-medium': 'var(--g-color-base-warning-medium)',
        'base-warning-medium-hover': 'var(--g-color-base-warning-medium-hover)',
        'base-warning-heavy': 'var(--g-color-base-warning-heavy)',
        'base-warning-heavy-hover': 'var(--g-color-base-warning-heavy-hover)',
        'base-danger-light': 'var(--g-color-base-danger-light)',
        'base-danger-light-hover': 'var(--g-color-base-danger-light-hover)',
        'base-danger-medium': 'var(--g-color-base-danger-medium)',
        'base-danger-medium-hover': 'var(--g-color-base-danger-medium-hover)',
        'base-danger-heavy': 'var(--g-color-base-danger-heavy)',
        'base-danger-heavy-hover': 'var(--g-color-base-danger-heavy-hover)',
        'base-neutral-light': 'var(--g-color-base-neutral-light)',
        'base-neutral-light-hover': 'var(--g-color-base-neutral-light-hover)',
        'base-neutral-medium': 'var(--g-color-base-neutral-medium)',
        'base-neutral-medium-hover': 'var(--g-color-base-neutral-medium-hover)',
        'base-neutral-heavy': 'var(--g-color-base-neutral-heavy)',
        'base-neutral-heavy-hover': 'var(--g-color-base-neutral-heavy-hover)',
        'base-misc-light': 'var(--g-color-base-misc-light)',
        'base-misc-light-hover': 'var(--g-color-base-misc-light-hover)',
        'base-misc-medium': 'var(--g-color-base-misc-medium)',
        'base-misc-medium-hover': 'var(--g-color-base-misc-medium-hover)',
        'base-misc-heavy': 'var(--g-color-base-misc-heavy)',
        'base-misc-heavy-hover': 'var(--g-color-base-misc-heavy-hover)',
        'base-light': 'var(--g-color-base-light)',
        'base-light-hover': 'var(--g-color-base-light-hover)',
        'base-light-simple-hover': 'var(--g-color-base-light-simple-hover)',
        'base-light-disabled': 'var(--g-color-base-light-disabled)',
        'base-light-accent-disabled':
          'var(--g-color-base-light-accent-disabled)',
        'base-float': 'var(--g-color-base-float)',
        'base-float-hover': 'var(--g-color-base-float-hover)',
        'base-float-heavy': 'var(--g-color-base-float-heavy)',
        'base-float-accent': 'var(--g-color-base-float-accent)',
        'base-float-accent-hover': 'var(--g-color-base-float-accent-hover)',
        'base-float-announcement': 'var(--g-color-base-float-announcement)',
        'base-modal': 'var(--g-color-base-modal)',
        'line-generic': 'var(--g-color-line-generic)',
        'line-generic-hover': 'var(--g-color-line-generic-hover)',
        'line-generic-active': 'var(--g-color-line-generic-active)',
        'line-generic-accent': 'var(--g-color-line-generic-accent)',
        'line-generic-accent-hover': 'var(--g-color-line-generic-accent-hover)',
        'line-generic-solid': 'var(--g-color-line-generic-solid)',
        'line-brand': 'var(--g-color-line-brand)',
        'line-info': 'var(--g-color-line-info)',
        'line-positive': 'var(--g-color-line-positive)',
        'line-warning': 'var(--g-color-line-warning)',
        'line-danger': 'var(--g-color-line-danger)',
        'line-misc': 'var(--g-color-line-misc)',
        'line-light': 'var(--g-color-line-light)',
        'sfx-veil': 'var(--g-color-sfx-veil)',
        'sfx-shadow': 'var(--g-color-sfx-shadow)',
        'sfx-shadow-heavy': 'var(--g-color-sfx-shadow-heavy)',
        'sfx-shadow-light': 'var(--g-color-sfx-shadow-light)',
        'sfx-fade': 'var(--g-color-sfx-fade)',
        'scroll-track': 'var(--g-color-scroll-track)',
        'scroll-handle': 'var(--g-color-scroll-handle)',
        'scroll-handle-hover': 'var(--g-color-scroll-handle-hover)',
        'scroll-corner': 'var(--g-color-scroll-corner)',
        'infographics-axis': 'var(--g-color-infographics-axis)',
        'infographics-tooltip-bg': 'var(--g-color-infographics-help-bg)',
      },
      dark: {
        1000: 'var(--color-dark-1000)',
      },
      primary: {
        1000: 'var(--color-primary-1000)',
      },
      'base-background': 'var(--color-base-background)',
    },
  },
  plugins: [require('tailwindcss-animate'), require('tailwind-children')],
  important: 'html',
};
