// Code generated by go-swagger; DO NOT EDIT.

package acl

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new acl API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new acl API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new acl API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for acl API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteAPIV1RoleRule(params *DeleteAPIV1RoleRuleParams, opts ...ClientOption) (*DeleteAPIV1RoleRuleOK, error)

	DeleteAPIV1UsergroupUser(params *DeleteAPIV1UsergroupUserParams, opts ...ClientOption) (*DeleteAPIV1UsergroupUserOK, error)

	GetAPIV1Permissions(params *GetAPIV1PermissionsParams, opts ...ClientOption) (*GetAPIV1PermissionsOK, error)

	GetAPIV2ACLCheck(params *GetAPIV2ACLCheckParams, opts ...ClientOption) (*GetAPIV2ACLCheckOK, error)

	GetAPIV2ACLUsers(params *GetAPIV2ACLUsersParams, opts ...ClientOption) (*GetAPIV2ACLUsersOK, error)

	GetAPIV2MeCapabilities(params *GetAPIV2MeCapabilitiesParams, opts ...ClientOption) (*GetAPIV2MeCapabilitiesOK, error)

	PostAPIV1Disclaim(params *PostAPIV1DisclaimParams, opts ...ClientOption) (*PostAPIV1DisclaimOK, error)

	PostAPIV1Grant(params *PostAPIV1GrantParams, opts ...ClientOption) (*PostAPIV1GrantOK, error)

	PostAPIV1RoleRule(params *PostAPIV1RoleRuleParams, opts ...ClientOption) (*PostAPIV1RoleRuleOK, error)

	PostAPIV1UsergroupUser(params *PostAPIV1UsergroupUserParams, opts ...ClientOption) (*PostAPIV1UsergroupUserOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteAPIV1RoleRule removes rule from role
*/
func (a *Client) DeleteAPIV1RoleRule(params *DeleteAPIV1RoleRuleParams, opts ...ClientOption) (*DeleteAPIV1RoleRuleOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteAPIV1RoleRuleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteAPIV1RoleRule",
		Method:             "DELETE",
		PathPattern:        "/api/v1/role/rule",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteAPIV1RoleRuleReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteAPIV1RoleRuleOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteAPIV1RoleRule: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteAPIV1UsergroupUser removes user from user group
*/
func (a *Client) DeleteAPIV1UsergroupUser(params *DeleteAPIV1UsergroupUserParams, opts ...ClientOption) (*DeleteAPIV1UsergroupUserOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteAPIV1UsergroupUserParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteAPIV1UsergroupUser",
		Method:             "DELETE",
		PathPattern:        "/api/v1/usergroup/user",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteAPIV1UsergroupUserReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteAPIV1UsergroupUserOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteAPIV1UsergroupUser: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1Permissions lists user s permitted actions on the given resource
*/
func (a *Client) GetAPIV1Permissions(params *GetAPIV1PermissionsParams, opts ...ClientOption) (*GetAPIV1PermissionsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1PermissionsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1Permissions",
		Method:             "GET",
		PathPattern:        "/api/v1/permissions",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1PermissionsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1PermissionsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1Permissions: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV2ACLCheck lists user s permitted actions on the given object
*/
func (a *Client) GetAPIV2ACLCheck(params *GetAPIV2ACLCheckParams, opts ...ClientOption) (*GetAPIV2ACLCheckOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV2ACLCheckParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV2ACLCheck",
		Method:             "GET",
		PathPattern:        "/api/v2/acl/check",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV2ACLCheckReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV2ACLCheckOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV2ACLCheck: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV2ACLUsers lists users and permitted actions on the given object
*/
func (a *Client) GetAPIV2ACLUsers(params *GetAPIV2ACLUsersParams, opts ...ClientOption) (*GetAPIV2ACLUsersOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV2ACLUsersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV2ACLUsers",
		Method:             "GET",
		PathPattern:        "/api/v2/acl/users",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV2ACLUsersReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV2ACLUsersOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV2ACLUsers: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV2MeCapabilities gets current user capabilities
*/
func (a *Client) GetAPIV2MeCapabilities(params *GetAPIV2MeCapabilitiesParams, opts ...ClientOption) (*GetAPIV2MeCapabilitiesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV2MeCapabilitiesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV2MeCapabilities",
		Method:             "GET",
		PathPattern:        "/api/v2/me/capabilities",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV2MeCapabilitiesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV2MeCapabilitiesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV2MeCapabilities: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIV1Disclaim disclaims permission
*/
func (a *Client) PostAPIV1Disclaim(params *PostAPIV1DisclaimParams, opts ...ClientOption) (*PostAPIV1DisclaimOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1DisclaimParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1Disclaim",
		Method:             "POST",
		PathPattern:        "/api/v1/disclaim",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1DisclaimReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1DisclaimOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1Disclaim: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIV1Grant grants permission
*/
func (a *Client) PostAPIV1Grant(params *PostAPIV1GrantParams, opts ...ClientOption) (*PostAPIV1GrantOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1GrantParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1Grant",
		Method:             "POST",
		PathPattern:        "/api/v1/grant",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1GrantReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1GrantOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1Grant: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIV1RoleRule adds rule to role
*/
func (a *Client) PostAPIV1RoleRule(params *PostAPIV1RoleRuleParams, opts ...ClientOption) (*PostAPIV1RoleRuleOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1RoleRuleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1RoleRule",
		Method:             "POST",
		PathPattern:        "/api/v1/role/rule",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1RoleRuleReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1RoleRuleOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1RoleRule: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIV1UsergroupUser adds user to user group
*/
func (a *Client) PostAPIV1UsergroupUser(params *PostAPIV1UsergroupUserParams, opts ...ClientOption) (*PostAPIV1UsergroupUserOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1UsergroupUserParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1UsergroupUser",
		Method:             "POST",
		PathPattern:        "/api/v1/usergroup/user",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1UsergroupUserReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1UsergroupUserOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1UsergroupUser: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
