// Code generated by go-swagger; DO NOT EDIT.

package acl

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.corp.mail.ru/ai/streamflow/backend/cplane/tests/private/models"
)

// GetAPIV1PermissionsReader is a Reader for the GetAPIV1Permissions structure.
type GetAPIV1PermissionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1PermissionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1PermissionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1PermissionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAPIV1PermissionsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAPIV1PermissionsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV1PermissionsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1PermissionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/permissions] GetAPIV1Permissions", response, response.Code())
	}
}

// NewGetAPIV1PermissionsOK creates a GetAPIV1PermissionsOK with default headers values
func NewGetAPIV1PermissionsOK() *GetAPIV1PermissionsOK {
	return &GetAPIV1PermissionsOK{}
}

/*
GetAPIV1PermissionsOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1PermissionsOK struct {
	Payload *models.ResponsesCheckPermissionsResponse
}

// IsSuccess returns true when this get Api v1 permissions o k response has a 2xx status code
func (o *GetAPIV1PermissionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 permissions o k response has a 3xx status code
func (o *GetAPIV1PermissionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 permissions o k response has a 4xx status code
func (o *GetAPIV1PermissionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 permissions o k response has a 5xx status code
func (o *GetAPIV1PermissionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 permissions o k response a status code equal to that given
func (o *GetAPIV1PermissionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 permissions o k response
func (o *GetAPIV1PermissionsOK) Code() int {
	return 200
}

func (o *GetAPIV1PermissionsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/permissions][%d] getApiV1PermissionsOK %s", 200, payload)
}

func (o *GetAPIV1PermissionsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/permissions][%d] getApiV1PermissionsOK %s", 200, payload)
}

func (o *GetAPIV1PermissionsOK) GetPayload() *models.ResponsesCheckPermissionsResponse {
	return o.Payload
}

func (o *GetAPIV1PermissionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesCheckPermissionsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1PermissionsBadRequest creates a GetAPIV1PermissionsBadRequest with default headers values
func NewGetAPIV1PermissionsBadRequest() *GetAPIV1PermissionsBadRequest {
	return &GetAPIV1PermissionsBadRequest{}
}

/*
GetAPIV1PermissionsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAPIV1PermissionsBadRequest struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 permissions bad request response has a 2xx status code
func (o *GetAPIV1PermissionsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 permissions bad request response has a 3xx status code
func (o *GetAPIV1PermissionsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 permissions bad request response has a 4xx status code
func (o *GetAPIV1PermissionsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 permissions bad request response has a 5xx status code
func (o *GetAPIV1PermissionsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 permissions bad request response a status code equal to that given
func (o *GetAPIV1PermissionsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v1 permissions bad request response
func (o *GetAPIV1PermissionsBadRequest) Code() int {
	return 400
}

func (o *GetAPIV1PermissionsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/permissions][%d] getApiV1PermissionsBadRequest %s", 400, payload)
}

func (o *GetAPIV1PermissionsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/permissions][%d] getApiV1PermissionsBadRequest %s", 400, payload)
}

func (o *GetAPIV1PermissionsBadRequest) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1PermissionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1PermissionsUnauthorized creates a GetAPIV1PermissionsUnauthorized with default headers values
func NewGetAPIV1PermissionsUnauthorized() *GetAPIV1PermissionsUnauthorized {
	return &GetAPIV1PermissionsUnauthorized{}
}

/*
GetAPIV1PermissionsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAPIV1PermissionsUnauthorized struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 permissions unauthorized response has a 2xx status code
func (o *GetAPIV1PermissionsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 permissions unauthorized response has a 3xx status code
func (o *GetAPIV1PermissionsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 permissions unauthorized response has a 4xx status code
func (o *GetAPIV1PermissionsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 permissions unauthorized response has a 5xx status code
func (o *GetAPIV1PermissionsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 permissions unauthorized response a status code equal to that given
func (o *GetAPIV1PermissionsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v1 permissions unauthorized response
func (o *GetAPIV1PermissionsUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV1PermissionsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/permissions][%d] getApiV1PermissionsUnauthorized %s", 401, payload)
}

func (o *GetAPIV1PermissionsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/permissions][%d] getApiV1PermissionsUnauthorized %s", 401, payload)
}

func (o *GetAPIV1PermissionsUnauthorized) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1PermissionsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1PermissionsForbidden creates a GetAPIV1PermissionsForbidden with default headers values
func NewGetAPIV1PermissionsForbidden() *GetAPIV1PermissionsForbidden {
	return &GetAPIV1PermissionsForbidden{}
}

/*
GetAPIV1PermissionsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAPIV1PermissionsForbidden struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 permissions forbidden response has a 2xx status code
func (o *GetAPIV1PermissionsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 permissions forbidden response has a 3xx status code
func (o *GetAPIV1PermissionsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 permissions forbidden response has a 4xx status code
func (o *GetAPIV1PermissionsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 permissions forbidden response has a 5xx status code
func (o *GetAPIV1PermissionsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 permissions forbidden response a status code equal to that given
func (o *GetAPIV1PermissionsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v1 permissions forbidden response
func (o *GetAPIV1PermissionsForbidden) Code() int {
	return 403
}

func (o *GetAPIV1PermissionsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/permissions][%d] getApiV1PermissionsForbidden %s", 403, payload)
}

func (o *GetAPIV1PermissionsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/permissions][%d] getApiV1PermissionsForbidden %s", 403, payload)
}

func (o *GetAPIV1PermissionsForbidden) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1PermissionsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1PermissionsNotFound creates a GetAPIV1PermissionsNotFound with default headers values
func NewGetAPIV1PermissionsNotFound() *GetAPIV1PermissionsNotFound {
	return &GetAPIV1PermissionsNotFound{}
}

/*
GetAPIV1PermissionsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAPIV1PermissionsNotFound struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 permissions not found response has a 2xx status code
func (o *GetAPIV1PermissionsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 permissions not found response has a 3xx status code
func (o *GetAPIV1PermissionsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 permissions not found response has a 4xx status code
func (o *GetAPIV1PermissionsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 permissions not found response has a 5xx status code
func (o *GetAPIV1PermissionsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 permissions not found response a status code equal to that given
func (o *GetAPIV1PermissionsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v1 permissions not found response
func (o *GetAPIV1PermissionsNotFound) Code() int {
	return 404
}

func (o *GetAPIV1PermissionsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/permissions][%d] getApiV1PermissionsNotFound %s", 404, payload)
}

func (o *GetAPIV1PermissionsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/permissions][%d] getApiV1PermissionsNotFound %s", 404, payload)
}

func (o *GetAPIV1PermissionsNotFound) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1PermissionsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1PermissionsInternalServerError creates a GetAPIV1PermissionsInternalServerError with default headers values
func NewGetAPIV1PermissionsInternalServerError() *GetAPIV1PermissionsInternalServerError {
	return &GetAPIV1PermissionsInternalServerError{}
}

/*
GetAPIV1PermissionsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetAPIV1PermissionsInternalServerError struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 permissions internal server error response has a 2xx status code
func (o *GetAPIV1PermissionsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 permissions internal server error response has a 3xx status code
func (o *GetAPIV1PermissionsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 permissions internal server error response has a 4xx status code
func (o *GetAPIV1PermissionsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 permissions internal server error response has a 5xx status code
func (o *GetAPIV1PermissionsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 permissions internal server error response a status code equal to that given
func (o *GetAPIV1PermissionsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 permissions internal server error response
func (o *GetAPIV1PermissionsInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1PermissionsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/permissions][%d] getApiV1PermissionsInternalServerError %s", 500, payload)
}

func (o *GetAPIV1PermissionsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/permissions][%d] getApiV1PermissionsInternalServerError %s", 500, payload)
}

func (o *GetAPIV1PermissionsInternalServerError) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1PermissionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
