// Code generated by go-swagger; DO NOT EDIT.

package acl

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.corp.mail.ru/ai/streamflow/backend/cplane/tests/private/models"
)

// PostAPIV1GrantReader is a Reader for the PostAPIV1Grant structure.
type PostAPIV1GrantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1GrantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1GrantOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1GrantBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1GrantUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostAPIV1GrantForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPIV1GrantNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1GrantInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/grant] PostAPIV1Grant", response, response.Code())
	}
}

// NewPostAPIV1GrantOK creates a PostAPIV1GrantOK with default headers values
func NewPostAPIV1GrantOK() *PostAPIV1GrantOK {
	return &PostAPIV1GrantOK{}
}

/*
PostAPIV1GrantOK describes a response with status code 200, with default header values.

OK
*/
type PostAPIV1GrantOK struct {
	Payload models.ResponsesEmptyResponse
}

// IsSuccess returns true when this post Api v1 grant o k response has a 2xx status code
func (o *PostAPIV1GrantOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 grant o k response has a 3xx status code
func (o *PostAPIV1GrantOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 grant o k response has a 4xx status code
func (o *PostAPIV1GrantOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 grant o k response has a 5xx status code
func (o *PostAPIV1GrantOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 grant o k response a status code equal to that given
func (o *PostAPIV1GrantOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 grant o k response
func (o *PostAPIV1GrantOK) Code() int {
	return 200
}

func (o *PostAPIV1GrantOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/grant][%d] postApiV1GrantOK %s", 200, payload)
}

func (o *PostAPIV1GrantOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/grant][%d] postApiV1GrantOK %s", 200, payload)
}

func (o *PostAPIV1GrantOK) GetPayload() models.ResponsesEmptyResponse {
	return o.Payload
}

func (o *PostAPIV1GrantOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1GrantBadRequest creates a PostAPIV1GrantBadRequest with default headers values
func NewPostAPIV1GrantBadRequest() *PostAPIV1GrantBadRequest {
	return &PostAPIV1GrantBadRequest{}
}

/*
PostAPIV1GrantBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAPIV1GrantBadRequest struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this post Api v1 grant bad request response has a 2xx status code
func (o *PostAPIV1GrantBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 grant bad request response has a 3xx status code
func (o *PostAPIV1GrantBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 grant bad request response has a 4xx status code
func (o *PostAPIV1GrantBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 grant bad request response has a 5xx status code
func (o *PostAPIV1GrantBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 grant bad request response a status code equal to that given
func (o *PostAPIV1GrantBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 grant bad request response
func (o *PostAPIV1GrantBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1GrantBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/grant][%d] postApiV1GrantBadRequest %s", 400, payload)
}

func (o *PostAPIV1GrantBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/grant][%d] postApiV1GrantBadRequest %s", 400, payload)
}

func (o *PostAPIV1GrantBadRequest) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *PostAPIV1GrantBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1GrantUnauthorized creates a PostAPIV1GrantUnauthorized with default headers values
func NewPostAPIV1GrantUnauthorized() *PostAPIV1GrantUnauthorized {
	return &PostAPIV1GrantUnauthorized{}
}

/*
PostAPIV1GrantUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostAPIV1GrantUnauthorized struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this post Api v1 grant unauthorized response has a 2xx status code
func (o *PostAPIV1GrantUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 grant unauthorized response has a 3xx status code
func (o *PostAPIV1GrantUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 grant unauthorized response has a 4xx status code
func (o *PostAPIV1GrantUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 grant unauthorized response has a 5xx status code
func (o *PostAPIV1GrantUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 grant unauthorized response a status code equal to that given
func (o *PostAPIV1GrantUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 grant unauthorized response
func (o *PostAPIV1GrantUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1GrantUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/grant][%d] postApiV1GrantUnauthorized %s", 401, payload)
}

func (o *PostAPIV1GrantUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/grant][%d] postApiV1GrantUnauthorized %s", 401, payload)
}

func (o *PostAPIV1GrantUnauthorized) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *PostAPIV1GrantUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1GrantForbidden creates a PostAPIV1GrantForbidden with default headers values
func NewPostAPIV1GrantForbidden() *PostAPIV1GrantForbidden {
	return &PostAPIV1GrantForbidden{}
}

/*
PostAPIV1GrantForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PostAPIV1GrantForbidden struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this post Api v1 grant forbidden response has a 2xx status code
func (o *PostAPIV1GrantForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 grant forbidden response has a 3xx status code
func (o *PostAPIV1GrantForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 grant forbidden response has a 4xx status code
func (o *PostAPIV1GrantForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 grant forbidden response has a 5xx status code
func (o *PostAPIV1GrantForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 grant forbidden response a status code equal to that given
func (o *PostAPIV1GrantForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post Api v1 grant forbidden response
func (o *PostAPIV1GrantForbidden) Code() int {
	return 403
}

func (o *PostAPIV1GrantForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/grant][%d] postApiV1GrantForbidden %s", 403, payload)
}

func (o *PostAPIV1GrantForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/grant][%d] postApiV1GrantForbidden %s", 403, payload)
}

func (o *PostAPIV1GrantForbidden) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *PostAPIV1GrantForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1GrantNotFound creates a PostAPIV1GrantNotFound with default headers values
func NewPostAPIV1GrantNotFound() *PostAPIV1GrantNotFound {
	return &PostAPIV1GrantNotFound{}
}

/*
PostAPIV1GrantNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PostAPIV1GrantNotFound struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this post Api v1 grant not found response has a 2xx status code
func (o *PostAPIV1GrantNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 grant not found response has a 3xx status code
func (o *PostAPIV1GrantNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 grant not found response has a 4xx status code
func (o *PostAPIV1GrantNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 grant not found response has a 5xx status code
func (o *PostAPIV1GrantNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 grant not found response a status code equal to that given
func (o *PostAPIV1GrantNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post Api v1 grant not found response
func (o *PostAPIV1GrantNotFound) Code() int {
	return 404
}

func (o *PostAPIV1GrantNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/grant][%d] postApiV1GrantNotFound %s", 404, payload)
}

func (o *PostAPIV1GrantNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/grant][%d] postApiV1GrantNotFound %s", 404, payload)
}

func (o *PostAPIV1GrantNotFound) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *PostAPIV1GrantNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1GrantInternalServerError creates a PostAPIV1GrantInternalServerError with default headers values
func NewPostAPIV1GrantInternalServerError() *PostAPIV1GrantInternalServerError {
	return &PostAPIV1GrantInternalServerError{}
}

/*
PostAPIV1GrantInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PostAPIV1GrantInternalServerError struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this post Api v1 grant internal server error response has a 2xx status code
func (o *PostAPIV1GrantInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 grant internal server error response has a 3xx status code
func (o *PostAPIV1GrantInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 grant internal server error response has a 4xx status code
func (o *PostAPIV1GrantInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 grant internal server error response has a 5xx status code
func (o *PostAPIV1GrantInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 grant internal server error response a status code equal to that given
func (o *PostAPIV1GrantInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 grant internal server error response
func (o *PostAPIV1GrantInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1GrantInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/grant][%d] postApiV1GrantInternalServerError %s", 500, payload)
}

func (o *PostAPIV1GrantInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/grant][%d] postApiV1GrantInternalServerError %s", 500, payload)
}

func (o *PostAPIV1GrantInternalServerError) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *PostAPIV1GrantInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
