// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV2UserRolesParams creates a new GetAPIV2UserRolesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV2UserRolesParams() *GetAPIV2UserRolesParams {
	return &GetAPIV2UserRolesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV2UserRolesParamsWithTimeout creates a new GetAPIV2UserRolesParams object
// with the ability to set a timeout on a request.
func NewGetAPIV2UserRolesParamsWithTimeout(timeout time.Duration) *GetAPIV2UserRolesParams {
	return &GetAPIV2UserRolesParams{
		timeout: timeout,
	}
}

// NewGetAPIV2UserRolesParamsWithContext creates a new GetAPIV2UserRolesParams object
// with the ability to set a context for a request.
func NewGetAPIV2UserRolesParamsWithContext(ctx context.Context) *GetAPIV2UserRolesParams {
	return &GetAPIV2UserRolesParams{
		Context: ctx,
	}
}

// NewGetAPIV2UserRolesParamsWithHTTPClient creates a new GetAPIV2UserRolesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV2UserRolesParamsWithHTTPClient(client *http.Client) *GetAPIV2UserRolesParams {
	return &GetAPIV2UserRolesParams{
		HTTPClient: client,
	}
}

/*
GetAPIV2UserRolesParams contains all the parameters to send to the API endpoint

	for the get API v2 user roles operation.

	Typically these are written to a http.Request.
*/
type GetAPIV2UserRolesParams struct {

	/* UserID.

	   user id
	*/
	UserID int64

	/* XSuperuserToken.

	   superuser token
	*/
	XSuperuserToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v2 user roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV2UserRolesParams) WithDefaults() *GetAPIV2UserRolesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v2 user roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV2UserRolesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v2 user roles params
func (o *GetAPIV2UserRolesParams) WithTimeout(timeout time.Duration) *GetAPIV2UserRolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v2 user roles params
func (o *GetAPIV2UserRolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v2 user roles params
func (o *GetAPIV2UserRolesParams) WithContext(ctx context.Context) *GetAPIV2UserRolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v2 user roles params
func (o *GetAPIV2UserRolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v2 user roles params
func (o *GetAPIV2UserRolesParams) WithHTTPClient(client *http.Client) *GetAPIV2UserRolesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v2 user roles params
func (o *GetAPIV2UserRolesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the get API v2 user roles params
func (o *GetAPIV2UserRolesParams) WithUserID(userID int64) *GetAPIV2UserRolesParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get API v2 user roles params
func (o *GetAPIV2UserRolesParams) SetUserID(userID int64) {
	o.UserID = userID
}

// WithXSuperuserToken adds the xSuperuserToken to the get API v2 user roles params
func (o *GetAPIV2UserRolesParams) WithXSuperuserToken(xSuperuserToken *string) *GetAPIV2UserRolesParams {
	o.SetXSuperuserToken(xSuperuserToken)
	return o
}

// SetXSuperuserToken adds the xSuperuserToken to the get API v2 user roles params
func (o *GetAPIV2UserRolesParams) SetXSuperuserToken(xSuperuserToken *string) {
	o.XSuperuserToken = xSuperuserToken
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV2UserRolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param user_id
	qrUserID := o.UserID
	qUserID := swag.FormatInt64(qrUserID)
	if qUserID != "" {

		if err := r.SetQueryParam("user_id", qUserID); err != nil {
			return err
		}
	}

	if o.XSuperuserToken != nil {

		// header param x-superuser-token
		if err := r.SetHeaderParam("x-superuser-token", *o.XSuperuserToken); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
