// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.corp.mail.ru/ai/streamflow/backend/cplane/tests/private/models"
)

// GetAPIV2UserRolesReader is a Reader for the GetAPIV2UserRoles structure.
type GetAPIV2UserRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV2UserRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV2UserRolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV2UserRolesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAPIV2UserRolesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAPIV2UserRolesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV2UserRolesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV2UserRolesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v2/user/roles] GetAPIV2UserRoles", response, response.Code())
	}
}

// NewGetAPIV2UserRolesOK creates a GetAPIV2UserRolesOK with default headers values
func NewGetAPIV2UserRolesOK() *GetAPIV2UserRolesOK {
	return &GetAPIV2UserRolesOK{}
}

/*
GetAPIV2UserRolesOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV2UserRolesOK struct {
	Payload *models.ResponsesListRolesResponse
}

// IsSuccess returns true when this get Api v2 user roles o k response has a 2xx status code
func (o *GetAPIV2UserRolesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v2 user roles o k response has a 3xx status code
func (o *GetAPIV2UserRolesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 user roles o k response has a 4xx status code
func (o *GetAPIV2UserRolesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v2 user roles o k response has a 5xx status code
func (o *GetAPIV2UserRolesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 user roles o k response a status code equal to that given
func (o *GetAPIV2UserRolesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v2 user roles o k response
func (o *GetAPIV2UserRolesOK) Code() int {
	return 200
}

func (o *GetAPIV2UserRolesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/user/roles][%d] getApiV2UserRolesOK %s", 200, payload)
}

func (o *GetAPIV2UserRolesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/user/roles][%d] getApiV2UserRolesOK %s", 200, payload)
}

func (o *GetAPIV2UserRolesOK) GetPayload() *models.ResponsesListRolesResponse {
	return o.Payload
}

func (o *GetAPIV2UserRolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesListRolesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV2UserRolesBadRequest creates a GetAPIV2UserRolesBadRequest with default headers values
func NewGetAPIV2UserRolesBadRequest() *GetAPIV2UserRolesBadRequest {
	return &GetAPIV2UserRolesBadRequest{}
}

/*
GetAPIV2UserRolesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAPIV2UserRolesBadRequest struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v2 user roles bad request response has a 2xx status code
func (o *GetAPIV2UserRolesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 user roles bad request response has a 3xx status code
func (o *GetAPIV2UserRolesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 user roles bad request response has a 4xx status code
func (o *GetAPIV2UserRolesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v2 user roles bad request response has a 5xx status code
func (o *GetAPIV2UserRolesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 user roles bad request response a status code equal to that given
func (o *GetAPIV2UserRolesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v2 user roles bad request response
func (o *GetAPIV2UserRolesBadRequest) Code() int {
	return 400
}

func (o *GetAPIV2UserRolesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/user/roles][%d] getApiV2UserRolesBadRequest %s", 400, payload)
}

func (o *GetAPIV2UserRolesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/user/roles][%d] getApiV2UserRolesBadRequest %s", 400, payload)
}

func (o *GetAPIV2UserRolesBadRequest) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV2UserRolesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV2UserRolesUnauthorized creates a GetAPIV2UserRolesUnauthorized with default headers values
func NewGetAPIV2UserRolesUnauthorized() *GetAPIV2UserRolesUnauthorized {
	return &GetAPIV2UserRolesUnauthorized{}
}

/*
GetAPIV2UserRolesUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAPIV2UserRolesUnauthorized struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v2 user roles unauthorized response has a 2xx status code
func (o *GetAPIV2UserRolesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 user roles unauthorized response has a 3xx status code
func (o *GetAPIV2UserRolesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 user roles unauthorized response has a 4xx status code
func (o *GetAPIV2UserRolesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v2 user roles unauthorized response has a 5xx status code
func (o *GetAPIV2UserRolesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 user roles unauthorized response a status code equal to that given
func (o *GetAPIV2UserRolesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v2 user roles unauthorized response
func (o *GetAPIV2UserRolesUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV2UserRolesUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/user/roles][%d] getApiV2UserRolesUnauthorized %s", 401, payload)
}

func (o *GetAPIV2UserRolesUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/user/roles][%d] getApiV2UserRolesUnauthorized %s", 401, payload)
}

func (o *GetAPIV2UserRolesUnauthorized) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV2UserRolesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV2UserRolesForbidden creates a GetAPIV2UserRolesForbidden with default headers values
func NewGetAPIV2UserRolesForbidden() *GetAPIV2UserRolesForbidden {
	return &GetAPIV2UserRolesForbidden{}
}

/*
GetAPIV2UserRolesForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAPIV2UserRolesForbidden struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v2 user roles forbidden response has a 2xx status code
func (o *GetAPIV2UserRolesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 user roles forbidden response has a 3xx status code
func (o *GetAPIV2UserRolesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 user roles forbidden response has a 4xx status code
func (o *GetAPIV2UserRolesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v2 user roles forbidden response has a 5xx status code
func (o *GetAPIV2UserRolesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 user roles forbidden response a status code equal to that given
func (o *GetAPIV2UserRolesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v2 user roles forbidden response
func (o *GetAPIV2UserRolesForbidden) Code() int {
	return 403
}

func (o *GetAPIV2UserRolesForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/user/roles][%d] getApiV2UserRolesForbidden %s", 403, payload)
}

func (o *GetAPIV2UserRolesForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/user/roles][%d] getApiV2UserRolesForbidden %s", 403, payload)
}

func (o *GetAPIV2UserRolesForbidden) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV2UserRolesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV2UserRolesNotFound creates a GetAPIV2UserRolesNotFound with default headers values
func NewGetAPIV2UserRolesNotFound() *GetAPIV2UserRolesNotFound {
	return &GetAPIV2UserRolesNotFound{}
}

/*
GetAPIV2UserRolesNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAPIV2UserRolesNotFound struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v2 user roles not found response has a 2xx status code
func (o *GetAPIV2UserRolesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 user roles not found response has a 3xx status code
func (o *GetAPIV2UserRolesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 user roles not found response has a 4xx status code
func (o *GetAPIV2UserRolesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v2 user roles not found response has a 5xx status code
func (o *GetAPIV2UserRolesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 user roles not found response a status code equal to that given
func (o *GetAPIV2UserRolesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v2 user roles not found response
func (o *GetAPIV2UserRolesNotFound) Code() int {
	return 404
}

func (o *GetAPIV2UserRolesNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/user/roles][%d] getApiV2UserRolesNotFound %s", 404, payload)
}

func (o *GetAPIV2UserRolesNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/user/roles][%d] getApiV2UserRolesNotFound %s", 404, payload)
}

func (o *GetAPIV2UserRolesNotFound) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV2UserRolesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV2UserRolesInternalServerError creates a GetAPIV2UserRolesInternalServerError with default headers values
func NewGetAPIV2UserRolesInternalServerError() *GetAPIV2UserRolesInternalServerError {
	return &GetAPIV2UserRolesInternalServerError{}
}

/*
GetAPIV2UserRolesInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetAPIV2UserRolesInternalServerError struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v2 user roles internal server error response has a 2xx status code
func (o *GetAPIV2UserRolesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v2 user roles internal server error response has a 3xx status code
func (o *GetAPIV2UserRolesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 user roles internal server error response has a 4xx status code
func (o *GetAPIV2UserRolesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v2 user roles internal server error response has a 5xx status code
func (o *GetAPIV2UserRolesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v2 user roles internal server error response a status code equal to that given
func (o *GetAPIV2UserRolesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v2 user roles internal server error response
func (o *GetAPIV2UserRolesInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV2UserRolesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/user/roles][%d] getApiV2UserRolesInternalServerError %s", 500, payload)
}

func (o *GetAPIV2UserRolesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/user/roles][%d] getApiV2UserRolesInternalServerError %s", 500, payload)
}

func (o *GetAPIV2UserRolesInternalServerError) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV2UserRolesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
