// Code generated by go-swagger; DO NOT EDIT.

package user

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.corp.mail.ru/ai/streamflow/backend/cplane/tests/private/models"
)

// GetAPIV1WhoAmIReader is a Reader for the GetAPIV1WhoAmI structure.
type GetAPIV1WhoAmIReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1WhoAmIReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1WhoAmIOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetAPIV1WhoAmIForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1WhoAmIInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/who_am_i] GetAPIV1WhoAmI", response, response.Code())
	}
}

// NewGetAPIV1WhoAmIOK creates a GetAPIV1WhoAmIOK with default headers values
func NewGetAPIV1WhoAmIOK() *GetAPIV1WhoAmIOK {
	return &GetAPIV1WhoAmIOK{}
}

/*
GetAPIV1WhoAmIOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1WhoAmIOK struct {
	Payload *models.ResponsesUserByNameResponse
}

// IsSuccess returns true when this get Api v1 who am i o k response has a 2xx status code
func (o *GetAPIV1WhoAmIOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 who am i o k response has a 3xx status code
func (o *GetAPIV1WhoAmIOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 who am i o k response has a 4xx status code
func (o *GetAPIV1WhoAmIOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 who am i o k response has a 5xx status code
func (o *GetAPIV1WhoAmIOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 who am i o k response a status code equal to that given
func (o *GetAPIV1WhoAmIOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 who am i o k response
func (o *GetAPIV1WhoAmIOK) Code() int {
	return 200
}

func (o *GetAPIV1WhoAmIOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/who_am_i][%d] getApiV1WhoAmIOK %s", 200, payload)
}

func (o *GetAPIV1WhoAmIOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/who_am_i][%d] getApiV1WhoAmIOK %s", 200, payload)
}

func (o *GetAPIV1WhoAmIOK) GetPayload() *models.ResponsesUserByNameResponse {
	return o.Payload
}

func (o *GetAPIV1WhoAmIOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesUserByNameResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1WhoAmIForbidden creates a GetAPIV1WhoAmIForbidden with default headers values
func NewGetAPIV1WhoAmIForbidden() *GetAPIV1WhoAmIForbidden {
	return &GetAPIV1WhoAmIForbidden{}
}

/*
GetAPIV1WhoAmIForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAPIV1WhoAmIForbidden struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 who am i forbidden response has a 2xx status code
func (o *GetAPIV1WhoAmIForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 who am i forbidden response has a 3xx status code
func (o *GetAPIV1WhoAmIForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 who am i forbidden response has a 4xx status code
func (o *GetAPIV1WhoAmIForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 who am i forbidden response has a 5xx status code
func (o *GetAPIV1WhoAmIForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 who am i forbidden response a status code equal to that given
func (o *GetAPIV1WhoAmIForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Api v1 who am i forbidden response
func (o *GetAPIV1WhoAmIForbidden) Code() int {
	return 403
}

func (o *GetAPIV1WhoAmIForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/who_am_i][%d] getApiV1WhoAmIForbidden %s", 403, payload)
}

func (o *GetAPIV1WhoAmIForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/who_am_i][%d] getApiV1WhoAmIForbidden %s", 403, payload)
}

func (o *GetAPIV1WhoAmIForbidden) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1WhoAmIForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1WhoAmIInternalServerError creates a GetAPIV1WhoAmIInternalServerError with default headers values
func NewGetAPIV1WhoAmIInternalServerError() *GetAPIV1WhoAmIInternalServerError {
	return &GetAPIV1WhoAmIInternalServerError{}
}

/*
GetAPIV1WhoAmIInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetAPIV1WhoAmIInternalServerError struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 who am i internal server error response has a 2xx status code
func (o *GetAPIV1WhoAmIInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 who am i internal server error response has a 3xx status code
func (o *GetAPIV1WhoAmIInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 who am i internal server error response has a 4xx status code
func (o *GetAPIV1WhoAmIInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 who am i internal server error response has a 5xx status code
func (o *GetAPIV1WhoAmIInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 who am i internal server error response a status code equal to that given
func (o *GetAPIV1WhoAmIInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 who am i internal server error response
func (o *GetAPIV1WhoAmIInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1WhoAmIInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/who_am_i][%d] getApiV1WhoAmIInternalServerError %s", 500, payload)
}

func (o *GetAPIV1WhoAmIInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/who_am_i][%d] getApiV1WhoAmIInternalServerError %s", 500, payload)
}

func (o *GetAPIV1WhoAmIInternalServerError) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1WhoAmIInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
