// Code generated by go-swagger; DO NOT EDIT.

package user

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new user API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new user API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new user API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for user API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetAPIV1User(params *GetAPIV1UserParams, opts ...ClientOption) (*GetAPIV1UserOK, error)

	GetAPIV1Users(params *GetAPIV1UsersParams, opts ...ClientOption) (*GetAPIV1UsersOK, error)

	GetAPIV1WhoAmI(params *GetAPIV1WhoAmIParams, opts ...ClientOption) (*GetAPIV1WhoAmIOK, error)

	GetAPIV2UserRoles(params *GetAPIV2UserRolesParams, opts ...ClientOption) (*GetAPIV2UserRolesOK, error)

	PostAPIV1User(params *PostAPIV1UserParams, opts ...ClientOption) (*PostAPIV1UserOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetAPIV1User gets user by name
*/
func (a *Client) GetAPIV1User(params *GetAPIV1UserParams, opts ...ClientOption) (*GetAPIV1UserOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1UserParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1User",
		Method:             "GET",
		PathPattern:        "/api/v1/user",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1UserReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1UserOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1User: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1Users lists users in user group
*/
func (a *Client) GetAPIV1Users(params *GetAPIV1UsersParams, opts ...ClientOption) (*GetAPIV1UsersOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1UsersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1Users",
		Method:             "GET",
		PathPattern:        "/api/v1/users",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1UsersReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1UsersOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1Users: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV1WhoAmI whos am i
*/
func (a *Client) GetAPIV1WhoAmI(params *GetAPIV1WhoAmIParams, opts ...ClientOption) (*GetAPIV1WhoAmIOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV1WhoAmIParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV1WhoAmI",
		Method:             "GET",
		PathPattern:        "/api/v1/who_am_i",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1WhoAmIReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV1WhoAmIOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV1WhoAmI: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPIV2UserRoles lists user roles
*/
func (a *Client) GetAPIV2UserRoles(params *GetAPIV2UserRolesParams, opts ...ClientOption) (*GetAPIV2UserRolesOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPIV2UserRolesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPIV2UserRoles",
		Method:             "GET",
		PathPattern:        "/api/v2/user/roles",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV2UserRolesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPIV2UserRolesOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPIV2UserRoles: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPIV1User creates user
*/
func (a *Client) PostAPIV1User(params *PostAPIV1UserParams, opts ...ClientOption) (*PostAPIV1UserOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPIV1UserParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPIV1User",
		Method:             "POST",
		PathPattern:        "/api/v1/user",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPIV1UserReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPIV1UserOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPIV1User: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
