// Code generated by go-swagger; DO NOT EDIT.

package idm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"gitlab.corp.mail.ru/ai/streamflow/backend/cplane/tests/private/models"
)

// NewPostAPIV2IdmProjectRolesParams creates a new PostAPIV2IdmProjectRolesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV2IdmProjectRolesParams() *PostAPIV2IdmProjectRolesParams {
	return &PostAPIV2IdmProjectRolesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV2IdmProjectRolesParamsWithTimeout creates a new PostAPIV2IdmProjectRolesParams object
// with the ability to set a timeout on a request.
func NewPostAPIV2IdmProjectRolesParamsWithTimeout(timeout time.Duration) *PostAPIV2IdmProjectRolesParams {
	return &PostAPIV2IdmProjectRolesParams{
		timeout: timeout,
	}
}

// NewPostAPIV2IdmProjectRolesParamsWithContext creates a new PostAPIV2IdmProjectRolesParams object
// with the ability to set a context for a request.
func NewPostAPIV2IdmProjectRolesParamsWithContext(ctx context.Context) *PostAPIV2IdmProjectRolesParams {
	return &PostAPIV2IdmProjectRolesParams{
		Context: ctx,
	}
}

// NewPostAPIV2IdmProjectRolesParamsWithHTTPClient creates a new PostAPIV2IdmProjectRolesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV2IdmProjectRolesParamsWithHTTPClient(client *http.Client) *PostAPIV2IdmProjectRolesParams {
	return &PostAPIV2IdmProjectRolesParams{
		HTTPClient: client,
	}
}

/*
PostAPIV2IdmProjectRolesParams contains all the parameters to send to the API endpoint

	for the post API v2 idm project roles operation.

	Typically these are written to a http.Request.
*/
type PostAPIV2IdmProjectRolesParams struct {

	/* Request.

	   request body
	*/
	Request models.RequestsCreateProjectRolesRequest

	/* XSuperuserToken.

	   superuser token
	*/
	XSuperuserToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v2 idm project roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV2IdmProjectRolesParams) WithDefaults() *PostAPIV2IdmProjectRolesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v2 idm project roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV2IdmProjectRolesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v2 idm project roles params
func (o *PostAPIV2IdmProjectRolesParams) WithTimeout(timeout time.Duration) *PostAPIV2IdmProjectRolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v2 idm project roles params
func (o *PostAPIV2IdmProjectRolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v2 idm project roles params
func (o *PostAPIV2IdmProjectRolesParams) WithContext(ctx context.Context) *PostAPIV2IdmProjectRolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v2 idm project roles params
func (o *PostAPIV2IdmProjectRolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v2 idm project roles params
func (o *PostAPIV2IdmProjectRolesParams) WithHTTPClient(client *http.Client) *PostAPIV2IdmProjectRolesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v2 idm project roles params
func (o *PostAPIV2IdmProjectRolesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post API v2 idm project roles params
func (o *PostAPIV2IdmProjectRolesParams) WithRequest(request models.RequestsCreateProjectRolesRequest) *PostAPIV2IdmProjectRolesParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post API v2 idm project roles params
func (o *PostAPIV2IdmProjectRolesParams) SetRequest(request models.RequestsCreateProjectRolesRequest) {
	o.Request = request
}

// WithXSuperuserToken adds the xSuperuserToken to the post API v2 idm project roles params
func (o *PostAPIV2IdmProjectRolesParams) WithXSuperuserToken(xSuperuserToken *string) *PostAPIV2IdmProjectRolesParams {
	o.SetXSuperuserToken(xSuperuserToken)
	return o
}

// SetXSuperuserToken adds the xSuperuserToken to the post API v2 idm project roles params
func (o *PostAPIV2IdmProjectRolesParams) SetXSuperuserToken(xSuperuserToken *string) {
	o.XSuperuserToken = xSuperuserToken
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV2IdmProjectRolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if o.XSuperuserToken != nil {

		// header param x-superuser-token
		if err := r.SetHeaderParam("x-superuser-token", *o.XSuperuserToken); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
