// Package jobd provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package jobd

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for CreateTaskMode.
const (
	Parallel   CreateTaskMode = "parallel"
	Sequential CreateTaskMode = "sequential"
)

// Defines values for EventEventType.
const (
	EventEventTypeCancelled EventEventType = "cancelled"
	EventEventTypeCompleted EventEventType = "completed"
	EventEventTypeCreated   EventEventType = "created"
	EventEventTypeFailed    EventEventType = "failed"
	EventEventTypePaused    EventEventType = "paused"
	EventEventTypeResumed   EventEventType = "resumed"
	EventEventTypeStarted   EventEventType = "started"
	EventEventTypeTimeout   EventEventType = "timeout"
)

// Defines values for EventWithJobEventType.
const (
	EventWithJobEventTypeCancelled EventWithJobEventType = "cancelled"
	EventWithJobEventTypeCompleted EventWithJobEventType = "completed"
	EventWithJobEventTypeCreated   EventWithJobEventType = "created"
	EventWithJobEventTypeFailed    EventWithJobEventType = "failed"
	EventWithJobEventTypePaused    EventWithJobEventType = "paused"
	EventWithJobEventTypeResumed   EventWithJobEventType = "resumed"
	EventWithJobEventTypeStarted   EventWithJobEventType = "started"
	EventWithJobEventTypeTimeout   EventWithJobEventType = "timeout"
)

// Defines values for JobEntityType.
const (
	JobEntityTypeDataset JobEntityType = "dataset"
	JobEntityTypeNamespace  JobEntityType = "namespace"
	JobEntityTypeExperiment   JobEntityType = "experiment"
	JobEntityTypeProject    JobEntityType = "project"
)

// Defines values for JobStatus.
const (
	JobStatusCancelled JobStatus = "cancelled"
	JobStatusCompleted JobStatus = "completed"
	JobStatusFailed    JobStatus = "failed"
	JobStatusPaused    JobStatus = "paused"
	JobStatusPending   JobStatus = "pending"
	JobStatusQueued    JobStatus = "queued"
	JobStatusRunning   JobStatus = "running"
	JobStatusTimeout   JobStatus = "timeout"
)

// Defines values for LinkedEntityType.
const (
	LinkedEntityTypeDataset LinkedEntityType = "dataset"
	LinkedEntityTypeNamespace  LinkedEntityType = "namespace"
	LinkedEntityTypeExperiment   LinkedEntityType = "experiment"
	LinkedEntityTypeProject    LinkedEntityType = "project"
)

// Defines values for LogEntryLevel.
const (
	LogEntryLevelDEBUG LogEntryLevel = "DEBUG"
	LogEntryLevelERROR LogEntryLevel = "ERROR"
	LogEntryLevelINFO  LogEntryLevel = "INFO"
	LogEntryLevelWARN  LogEntryLevel = "WARN"
)

// Defines values for TaskStatus.
const (
	TaskStatusCancelled TaskStatus = "cancelled"
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusFailed    TaskStatus = "failed"
	TaskStatusPending   TaskStatus = "pending"
	TaskStatusRunning   TaskStatus = "running"
)

// Defines values for UpdateJobRequestStatus.
const (
	UpdateJobRequestStatusCancelled UpdateJobRequestStatus = "cancelled"
	UpdateJobRequestStatusCompleted UpdateJobRequestStatus = "completed"
	UpdateJobRequestStatusFailed    UpdateJobRequestStatus = "failed"
	UpdateJobRequestStatusPaused    UpdateJobRequestStatus = "paused"
	UpdateJobRequestStatusPending   UpdateJobRequestStatus = "pending"
	UpdateJobRequestStatusQueued    UpdateJobRequestStatus = "queued"
	UpdateJobRequestStatusRunning   UpdateJobRequestStatus = "running"
	UpdateJobRequestStatusTimeout   UpdateJobRequestStatus = "timeout"
)

// Defines values for UpdateTaskRequestStatus.
const (
	UpdateTaskRequestStatusCancelled UpdateTaskRequestStatus = "cancelled"
	UpdateTaskRequestStatusCompleted UpdateTaskRequestStatus = "completed"
	UpdateTaskRequestStatusFailed    UpdateTaskRequestStatus = "failed"
	UpdateTaskRequestStatusPending   UpdateTaskRequestStatus = "pending"
	UpdateTaskRequestStatusRunning   UpdateTaskRequestStatus = "running"
)

// Defines values for ListAllEventsParamsEntityType.
const (
	ListAllEventsParamsEntityTypeDataset ListAllEventsParamsEntityType = "dataset"
	ListAllEventsParamsEntityTypeNamespace  ListAllEventsParamsEntityType = "namespace"
	ListAllEventsParamsEntityTypeExperiment   ListAllEventsParamsEntityType = "experiment"
	ListAllEventsParamsEntityTypeProject    ListAllEventsParamsEntityType = "project"
)

// Defines values for ListAllEventsParamsEventType.
const (
	ListAllEventsParamsEventTypeCancelled ListAllEventsParamsEventType = "cancelled"
	ListAllEventsParamsEventTypeCompleted ListAllEventsParamsEventType = "completed"
	ListAllEventsParamsEventTypeCreated   ListAllEventsParamsEventType = "created"
	ListAllEventsParamsEventTypeFailed    ListAllEventsParamsEventType = "failed"
	ListAllEventsParamsEventTypePaused    ListAllEventsParamsEventType = "paused"
	ListAllEventsParamsEventTypeResumed   ListAllEventsParamsEventType = "resumed"
	ListAllEventsParamsEventTypeStarted   ListAllEventsParamsEventType = "started"
	ListAllEventsParamsEventTypeTimeout   ListAllEventsParamsEventType = "timeout"
)

// Defines values for ListAllEventsParamsSort.
const (
	EventType ListAllEventsParamsSort = "event_type"
	JobId     ListAllEventsParamsSort = "job_id"
	Timestamp ListAllEventsParamsSort = "timestamp"
)

// Defines values for ListAllEventsParamsOrder.
const (
	ListAllEventsParamsOrderAsc  ListAllEventsParamsOrder = "asc"
	ListAllEventsParamsOrderDesc ListAllEventsParamsOrder = "desc"
)

// Defines values for ListJobsParamsEntityType.
const (
	ListJobsParamsEntityTypeDataset ListJobsParamsEntityType = "dataset"
	ListJobsParamsEntityTypeNamespace  ListJobsParamsEntityType = "namespace"
	ListJobsParamsEntityTypeExperiment   ListJobsParamsEntityType = "experiment"
	ListJobsParamsEntityTypeProject    ListJobsParamsEntityType = "project"
)

// Defines values for ListJobsParamsStatus.
const (
	ListJobsParamsStatusCancelled ListJobsParamsStatus = "cancelled"
	ListJobsParamsStatusCompleted ListJobsParamsStatus = "completed"
	ListJobsParamsStatusFailed    ListJobsParamsStatus = "failed"
	ListJobsParamsStatusPaused    ListJobsParamsStatus = "paused"
	ListJobsParamsStatusPending   ListJobsParamsStatus = "pending"
	ListJobsParamsStatusQueued    ListJobsParamsStatus = "queued"
	ListJobsParamsStatusRunning   ListJobsParamsStatus = "running"
	ListJobsParamsStatusTimeout   ListJobsParamsStatus = "timeout"
)

// Defines values for ListJobsParamsSort.
const (
	CreatedAt  ListJobsParamsSort = "created_at"
	FinishedAt ListJobsParamsSort = "finished_at"
	Name       ListJobsParamsSort = "name"
	StartedAt  ListJobsParamsSort = "started_at"
	Status     ListJobsParamsSort = "status"
	UpdatedAt  ListJobsParamsSort = "updated_at"
)

// Defines values for ListJobsParamsOrder.
const (
	ListJobsParamsOrderAsc  ListJobsParamsOrder = "asc"
	ListJobsParamsOrderDesc ListJobsParamsOrder = "desc"
)

// Defines values for GetEventsParamsEventType.
const (
	GetEventsParamsEventTypeCancelled GetEventsParamsEventType = "cancelled"
	GetEventsParamsEventTypeCompleted GetEventsParamsEventType = "completed"
	GetEventsParamsEventTypeCreated   GetEventsParamsEventType = "created"
	GetEventsParamsEventTypeFailed    GetEventsParamsEventType = "failed"
	GetEventsParamsEventTypePaused    GetEventsParamsEventType = "paused"
	GetEventsParamsEventTypeResumed   GetEventsParamsEventType = "resumed"
	GetEventsParamsEventTypeStarted   GetEventsParamsEventType = "started"
	GetEventsParamsEventTypeTimeout   GetEventsParamsEventType = "timeout"
)

// Defines values for GetLogsParamsLevel.
const (
	GetLogsParamsLevelDEBUG GetLogsParamsLevel = "DEBUG"
	GetLogsParamsLevelERROR GetLogsParamsLevel = "ERROR"
	GetLogsParamsLevelINFO  GetLogsParamsLevel = "INFO"
	GetLogsParamsLevelWARN  GetLogsParamsLevel = "WARN"
)

// Defines values for ListTasksParamsStatus.
const (
	ListTasksParamsStatusCancelled ListTasksParamsStatus = "cancelled"
	ListTasksParamsStatusCompleted ListTasksParamsStatus = "completed"
	ListTasksParamsStatusFailed    ListTasksParamsStatus = "failed"
	ListTasksParamsStatusPending   ListTasksParamsStatus = "pending"
	ListTasksParamsStatusRunning   ListTasksParamsStatus = "running"
)

// CreateJobRequest defines model for CreateJobRequest.
type CreateJobRequest struct {
	// Config Конфигурация джобы
	Config *map[string]interface{} `json:"config,omitempty"`

	// Description Описание джобы
	Description *string       `json:"description,omitempty"`
	Entity      *LinkedEntity `json:"entity,omitempty"`

	// ExecutionTarget Целевая система для выполнения
	ExecutionTarget *string `json:"execution_target,omitempty"`

	// MaxRetries Максимальное количество повторов при ошибке
	MaxRetries *int32 `json:"max_retries,omitempty"`

	// Name Название джобы
	Name string `json:"name"`

	// Parameters Параметры джобы
	Parameters *map[string]interface{} `json:"parameters,omitempty"`

	// Priority Приоритет выполнения (0-10)
	Priority *int32 `json:"priority,omitempty"`

	// Steps Список шагов для выполнения
	Steps *[]CreateStep `json:"steps,omitempty"`

	// Tags Теги для категоризации
	Tags *[]string `json:"tags,omitempty"`

	// Tasks Список тасок для выполнения
	Tasks *[]CreateTask `json:"tasks,omitempty"`

	// Type Тип джобы
	Type string `json:"type"`
}

// CreateStep defines model for CreateStep.
type CreateStep struct {
	// Config Конфигурация шага
	Config *map[string]interface{} `json:"config,omitempty"`

	// Description Описание шага
	Description *string `json:"description,omitempty"`

	// Name Название шага
	Name string `json:"name"`

	// Order Порядок выполнения шага
	Order *int32 `json:"order,omitempty"`
}

// CreateTask defines model for CreateTask.
type CreateTask struct {
	// Config Конфигурация таски
	Config *map[string]interface{} `json:"config,omitempty"`

	// Description Описание таски
	Description *string `json:"description,omitempty"`

	// Mode Режим выполнения таски
	Mode *CreateTaskMode `json:"mode,omitempty"`

	// Name Название таски
	Name string `json:"name"`

	// Order Порядок выполнения таски
	Order *int32 `json:"order,omitempty"`
}

// CreateTaskMode Режим выполнения таски
type CreateTaskMode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Код ошибки
	Code *string `json:"code,omitempty"`

	// Details Дополнительные детали ошибки
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Описание ошибки
	Error *string `json:"error,omitempty"`
}

// Event defines model for Event.
type Event struct {
	// Details Детали события
	Details *map[string]interface{} `json:"details,omitempty"`

	// EventType Тип события
	EventType *EventEventType `json:"event_type,omitempty"`

	// Id ID события
	Id *int64 `json:"id,omitempty"`

	// JobId ID джобы
	JobId *int64 `json:"job_id,omitempty"`

	// Timestamp Время события
	Timestamp *time.Time `json:"timestamp,omitempty"`

	// UserId ID пользователя, инициировавшего событие
	UserId *string `json:"user_id,omitempty"`
}

// EventEventType Тип события
type EventEventType string

// EventWithJob Событие с полной информацией о джобе
type EventWithJob struct {
	// Details Детали события
	Details *map[string]interface{} `json:"details,omitempty"`

	// EventType Тип события
	EventType *EventWithJobEventType `json:"event_type,omitempty"`

	// Id ID события
	Id  *int64 `json:"id,omitempty"`
	Job *Job   `json:"job,omitempty"`

	// JobId ID джобы
	JobId *int64 `json:"job_id,omitempty"`

	// Timestamp Время события
	Timestamp *time.Time `json:"timestamp,omitempty"`

	// UserId ID пользователя, инициировавшего событие
	UserId *string `json:"user_id,omitempty"`
}

// EventWithJobEventType Тип события
type EventWithJobEventType string

// EventsList defines model for EventsList.
type EventsList struct {
	Events *[]Event `json:"events,omitempty"`

	// Limit Лимит записей на странице
	Limit *int32 `json:"limit,omitempty"`

	// Offset Смещение
	Offset *int32 `json:"offset,omitempty"`

	// Total Общее количество событий
	Total *int32 `json:"total,omitempty"`
}

// EventsListExtended defines model for EventsListExtended.
type EventsListExtended struct {
	Events *[]EventWithJob `json:"events,omitempty"`

	// Limit Лимит записей на странице
	Limit *int32 `json:"limit,omitempty"`

	// Offset Смещение
	Offset *int32 `json:"offset,omitempty"`

	// Total Общее количество событий
	Total *int32 `json:"total,omitempty"`
}

// Job defines model for Job.
type Job struct {
	// Config Конфигурация джобы
	Config *map[string]interface{} `json:"config,omitempty"`

	// CreatedAt Время создания
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// CreatedBy Кто создал джобу
	CreatedBy *string `json:"created_by,omitempty"`

	// Description Описание джобы
	Description *string `json:"description,omitempty"`

	// EntityId ID связанной сущности
	EntityId *int64 `json:"entity_id,omitempty"`

	// EntityType Тип связанной сущности
	EntityType *JobEntityType `json:"entity_type,omitempty"`

	// ErrorMessage Сообщение об ошибке
	ErrorMessage *string `json:"error_message,omitempty"`

	// FinishedAt Время завершения
	FinishedAt *time.Time `json:"finished_at,omitempty"`

	// Id ID джобы
	Id *int64 `json:"id,omitempty"`

	// MaxRetries Максимальное количество повторов
	MaxRetries *int32 `json:"max_retries,omitempty"`

	// Name Название джобы
	Name *string `json:"name,omitempty"`

	// Parameters Параметры джобы
	Parameters *map[string]interface{} `json:"parameters,omitempty"`

	// Priority Приоритет выполнения
	Priority *int32 `json:"priority,omitempty"`

	// Progress Прогресс выполнения (0-100)
	Progress *int32 `json:"progress,omitempty"`

	// Result Результат выполнения
	Result *map[string]interface{} `json:"result,omitempty"`

	// RetryCount Текущее количество повторов
	RetryCount *int32 `json:"retry_count,omitempty"`

	// Stages Стейджи джобы
	Stages *[]Stage `json:"stages,omitempty"`

	// StartedAt Время начала выполнения
	StartedAt *time.Time `json:"started_at,omitempty"`

	// Status Текущий статус джобы
	Status *JobStatus `json:"status,omitempty"`

	// StatusDescription Описание статуса джобы
	StatusDescription *string `json:"status_description,omitempty"`

	// Tags Теги джобы
	Tags *[]string `json:"tags,omitempty"`

	// Type Тип джобы
	Type *string `json:"type,omitempty"`

	// UpdatedAt Время последнего обновления
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// JobEntityType Тип связанной сущности
type JobEntityType string

// JobStatus Текущий статус джобы
type JobStatus string

// JobCreated defines model for JobCreated.
type JobCreated struct {
	Job *struct {
		// Id ID созданной джобы
		Id *int64 `json:"id,omitempty"`

		// Name Название джобы
		Name *string `json:"name,omitempty"`

		// Type Тип джобы
		Type *string `json:"type,omitempty"`
	} `json:"job,omitempty"`
}

// JobDetails defines model for JobDetails.
type JobDetails struct {
	Job *Job `json:"job,omitempty"`
}

// JobsList defines model for JobsList.
type JobsList struct {
	Jobs *[]Job `json:"jobs,omitempty"`

	// Pages Количество страниц
	Pages *int32 `json:"pages,omitempty"`

	// Total Общее количество джоб (для пагинации)
	Total *int32 `json:"total,omitempty"`
}

// LinkedEntity defines model for LinkedEntity.
type LinkedEntity struct {
	// Id ID сущности
	Id int64 `json:"id"`

	// Type Тип сущности
	Type LinkedEntityType `json:"type"`
}

// LinkedEntityType Тип сущности
type LinkedEntityType string

// LogEntry defines model for LogEntry.
type LogEntry struct {
	// Id ID лог-записи
	Id *int64 `json:"id,omitempty"`

	// JobId ID джобы
	JobId *int64 `json:"job_id,omitempty"`

	// Level Уровень лога
	Level *LogEntryLevel `json:"level,omitempty"`

	// Message Сообщение лога
	Message *string `json:"message,omitempty"`

	// Metadata Дополнительные метаданные
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// TaskId ID таски (опционально)
	TaskId *int64 `json:"task_id,omitempty"`

	// Timestamp Время записи лога
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// LogEntryLevel Уровень лога
type LogEntryLevel string

// LogsList defines model for LogsList.
type LogsList struct {
	// Limit Лимит записей на странице
	Limit *int32      `json:"limit,omitempty"`
	Logs  *[]LogEntry `json:"logs,omitempty"`

	// Offset Смещение
	Offset *int32 `json:"offset,omitempty"`

	// Total Общее количество логов
	Total *int32 `json:"total,omitempty"`
}

// Stage defines model for Stage.
type Stage struct {
	// Actions Доступные действия для стейджа
	Actions *[]string `json:"actions,omitempty"`

	// Description Описание стейджа
	Description *string `json:"description,omitempty"`

	// Logs Логи стейджа в виде текста
	Logs *string `json:"logs,omitempty"`

	// Name Название стейджа
	Name *string `json:"name,omitempty"`

	// Order Порядок выполнения стейджа
	Order *int32 `json:"order,omitempty"`

	// Required Обязательный ли стейдж
	Required *bool `json:"required,omitempty"`

	// StepId ID соответствующего шага (если существует)
	StepId *int64 `json:"step_id,omitempty"`

	// StepStatus Статус соответствующего шага (если существует)
	StepStatus *string `json:"step_status,omitempty"`
}

// Task defines model for Task.
type Task struct {
	// Config Конфигурация таски
	Config *map[string]interface{} `json:"config,omitempty"`

	// CreatedAt Время создания
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Description Описание таски
	Description *string `json:"description,omitempty"`

	// ErrorMessage Сообщение об ошибке
	ErrorMessage *string `json:"error_message,omitempty"`

	// FinishedAt Время завершения
	FinishedAt *time.Time `json:"finished_at,omitempty"`

	// Id ID таски
	Id *int64 `json:"id,omitempty"`

	// JobId ID джобы
	JobId *int64 `json:"job_id,omitempty"`

	// Name Название таски
	Name *string `json:"name,omitempty"`

	// OrchTaskId ID таски в оркестраторе
	OrchTaskId *string `json:"orch_task_id,omitempty"`

	// Order Порядок выполнения
	Order *int32 `json:"order,omitempty"`

	// Result Результат выполнения
	Result *map[string]interface{} `json:"result,omitempty"`

	// StartedAt Время начала выполнения
	StartedAt *time.Time `json:"started_at,omitempty"`

	// Status Статус таски
	Status *TaskStatus `json:"status,omitempty"`
}

// TaskStatus Статус таски
type TaskStatus string

// TasksList defines model for TasksList.
type TasksList struct {
	Tasks *[]Task `json:"tasks,omitempty"`
}

// UpdateJobRequest defines model for UpdateJobRequest.
type UpdateJobRequest struct {
	// ErrorMessage Сообщение об ошибке
	ErrorMessage *string `json:"error_message,omitempty"`

	// Progress Прогресс выполнения (0-100)
	Progress *int32 `json:"progress,omitempty"`

	// Result Результат выполнения
	Result *map[string]interface{} `json:"result,omitempty"`

	// Status Новый статус джобы
	Status *UpdateJobRequestStatus `json:"status,omitempty"`
}

// UpdateJobRequestStatus Новый статус джобы
type UpdateJobRequestStatus string

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	// ErrorMessage Сообщение об ошибке
	ErrorMessage *string `json:"error_message,omitempty"`

	// Result Результат выполнения
	Result *map[string]interface{} `json:"result,omitempty"`

	// Status Новый статус таски
	Status *UpdateTaskRequestStatus `json:"status,omitempty"`
}

// UpdateTaskRequestStatus Новый статус таски
type UpdateTaskRequestStatus string

// ListAllEventsParams defines parameters for ListAllEvents.
type ListAllEventsParams struct {
	// JobId Фильтр по ID джобы (опционально)
	JobId *int64 `form:"job_id,omitempty" json:"job_id,omitempty"`

	// EntityType Фильтр по типу сущности
	EntityType *ListAllEventsParamsEntityType `form:"entity_type,omitempty" json:"entity_type,omitempty"`

	// EntityId Фильтр по ID сущности
	EntityId *int64 `form:"entity_id,omitempty" json:"entity_id,omitempty"`

	// EventType Фильтр по типу события
	EventType *ListAllEventsParamsEventType `form:"event_type,omitempty" json:"event_type,omitempty"`

	// JobType Фильтр по типу джобы
	JobType *string `form:"job_type,omitempty" json:"job_type,omitempty"`

	// Limit Количество записей на странице (по умолчанию 50)
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение для пагинации (по умолчанию 0)
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// Sort Поле для сортировки (по умолчанию timestamp)
	Sort *ListAllEventsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Order Порядок сортировки (по умолчанию desc)
	Order *ListAllEventsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// ListAllEventsParamsEntityType defines parameters for ListAllEvents.
type ListAllEventsParamsEntityType string

// ListAllEventsParamsEventType defines parameters for ListAllEvents.
type ListAllEventsParamsEventType string

// ListAllEventsParamsSort defines parameters for ListAllEvents.
type ListAllEventsParamsSort string

// ListAllEventsParamsOrder defines parameters for ListAllEvents.
type ListAllEventsParamsOrder string

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	// EntityType Тип сущности (experiment, dataset, project, namespace)
	EntityType *ListJobsParamsEntityType `form:"entity_type,omitempty" json:"entity_type,omitempty"`

	// EntityId ID сущности
	EntityId *int64 `form:"entity_id,omitempty" json:"entity_id,omitempty"`

	// Type Тип джобы
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// Status Статус джобы
	Status *ListJobsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// CreatedBy Кто создал джобу
	CreatedBy *string `form:"created_by,omitempty" json:"created_by,omitempty"`

	// Limit Количество записей на странице (по умолчанию 20)
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение для пагинации (по умолчанию 0)
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// Sort Поле для сортировки (по умолчанию created_at)
	Sort *ListJobsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Order Порядок сортировки (по умолчанию desc)
	Order *ListJobsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// ListJobsParamsEntityType defines parameters for ListJobs.
type ListJobsParamsEntityType string

// ListJobsParamsStatus defines parameters for ListJobs.
type ListJobsParamsStatus string

// ListJobsParamsSort defines parameters for ListJobs.
type ListJobsParamsSort string

// ListJobsParamsOrder defines parameters for ListJobs.
type ListJobsParamsOrder string

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	// EventType Фильтр по типу события
	EventType *GetEventsParamsEventType `form:"event_type,omitempty" json:"event_type,omitempty"`

	// Limit Количество записей на странице (по умолчанию 50)
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение для пагинации (по умолчанию 0)
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetEventsParamsEventType defines parameters for GetEvents.
type GetEventsParamsEventType string

// GetLogsParams defines parameters for GetLogs.
type GetLogsParams struct {
	// TaskId Фильтр по ID таски
	TaskId *int64 `form:"task_id,omitempty" json:"task_id,omitempty"`

	// Level Фильтр по уровню лога
	Level *GetLogsParamsLevel `form:"level,omitempty" json:"level,omitempty"`

	// Limit Количество записей на странице (по умолчанию 100)
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Смещение для пагинации (по умолчанию 0)
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetLogsParamsLevel defines parameters for GetLogs.
type GetLogsParamsLevel string

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	// Status Фильтр по статусу таски
	Status *ListTasksParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListTasksParamsStatus defines parameters for ListTasks.
type ListTasksParamsStatus string

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = CreateJobRequest

// UpdateJobJSONRequestBody defines body for UpdateJob for application/json ContentType.
type UpdateJobJSONRequestBody = UpdateJobRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = UpdateTaskRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListAllEvents request
	ListAllEvents(ctx context.Context, params *ListAllEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListJobs request
	ListJobs(ctx context.Context, params *ListJobsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateJobWithBody request with any body
	CreateJobWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateJob(ctx context.Context, body CreateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteJob request
	DeleteJob(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetJob request
	GetJob(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateJobWithBody request with any body
	UpdateJobWithBody(ctx context.Context, id int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateJob(ctx context.Context, id int64, body UpdateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelJob request
	CancelJob(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEvents request
	GetEvents(ctx context.Context, id int64, params *GetEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetLogs request
	GetLogs(ctx context.Context, id int64, params *GetLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RetryJob request
	RetryJob(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListTasks request
	ListTasks(ctx context.Context, id int64, params *ListTasksParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTask request
	GetTask(ctx context.Context, id int64, taskId int64, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateTaskWithBody request with any body
	UpdateTaskWithBody(ctx context.Context, id int64, taskId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateTask(ctx context.Context, id int64, taskId int64, body UpdateTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListAllEvents(ctx context.Context, params *ListAllEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAllEventsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListJobs(ctx context.Context, params *ListJobsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListJobsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateJobWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateJobRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateJob(ctx context.Context, body CreateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateJobRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteJob(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteJobRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetJob(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetJobRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateJobWithBody(ctx context.Context, id int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateJobRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateJob(ctx context.Context, id int64, body UpdateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateJobRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CancelJob(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelJobRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetEvents(ctx context.Context, id int64, params *GetEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEventsRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetLogs(ctx context.Context, id int64, params *GetLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLogsRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RetryJob(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRetryJobRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListTasks(ctx context.Context, id int64, params *ListTasksParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListTasksRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTask(ctx context.Context, id int64, taskId int64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTaskRequest(c.Server, id, taskId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateTaskWithBody(ctx context.Context, id int64, taskId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateTaskRequestWithBody(c.Server, id, taskId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateTask(ctx context.Context, id int64, taskId int64, body UpdateTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateTaskRequest(c.Server, id, taskId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListAllEventsRequest generates requests for ListAllEvents
func NewListAllEventsRequest(server string, params *ListAllEventsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.JobId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "job_id", runtime.ParamLocationQuery, *params.JobId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.EntityType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "entity_type", runtime.ParamLocationQuery, *params.EntityType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.EntityId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "entity_id", runtime.ParamLocationQuery, *params.EntityId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.EventType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "event_type", runtime.ParamLocationQuery, *params.EventType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.JobType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "job_type", runtime.ParamLocationQuery, *params.JobType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Sort != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort", runtime.ParamLocationQuery, *params.Sort); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Order != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "order", runtime.ParamLocationQuery, *params.Order); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListJobsRequest generates requests for ListJobs
func NewListJobsRequest(server string, params *ListJobsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.EntityType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "entity_type", runtime.ParamLocationQuery, *params.EntityType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.EntityId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "entity_id", runtime.ParamLocationQuery, *params.EntityId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "type", runtime.ParamLocationQuery, *params.Type); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "status", runtime.ParamLocationQuery, *params.Status); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CreatedBy != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "created_by", runtime.ParamLocationQuery, *params.CreatedBy); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Sort != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort", runtime.ParamLocationQuery, *params.Sort); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Order != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "order", runtime.ParamLocationQuery, *params.Order); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateJobRequest calls the generic CreateJob builder with application/json body
func NewCreateJobRequest(server string, body CreateJobJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateJobRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateJobRequestWithBody generates requests for CreateJob with any type of body
func NewCreateJobRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteJobRequest generates requests for DeleteJob
func NewDeleteJobRequest(server string, id int64) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetJobRequest generates requests for GetJob
func NewGetJobRequest(server string, id int64) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateJobRequest calls the generic UpdateJob builder with application/json body
func NewUpdateJobRequest(server string, id int64, body UpdateJobJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateJobRequestWithBody(server, id, "application/json", bodyReader)
}

// NewUpdateJobRequestWithBody generates requests for UpdateJob with any type of body
func NewUpdateJobRequestWithBody(server string, id int64, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCancelJobRequest generates requests for CancelJob
func NewCancelJobRequest(server string, id int64) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s/cancel", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetEventsRequest generates requests for GetEvents
func NewGetEventsRequest(server string, id int64, params *GetEventsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s/events", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.EventType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "event_type", runtime.ParamLocationQuery, *params.EventType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetLogsRequest generates requests for GetLogs
func NewGetLogsRequest(server string, id int64, params *GetLogsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s/logs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.TaskId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "task_id", runtime.ParamLocationQuery, *params.TaskId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Level != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "level", runtime.ParamLocationQuery, *params.Level); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRetryJobRequest generates requests for RetryJob
func NewRetryJobRequest(server string, id int64) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s/retry", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListTasksRequest generates requests for ListTasks
func NewListTasksRequest(server string, id int64, params *ListTasksParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s/tasks", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "status", runtime.ParamLocationQuery, *params.Status); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTaskRequest generates requests for GetTask
func NewGetTaskRequest(server string, id int64, taskId int64) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "taskId", runtime.ParamLocationPath, taskId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s/tasks/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateTaskRequest calls the generic UpdateTask builder with application/json body
func NewUpdateTaskRequest(server string, id int64, taskId int64, body UpdateTaskJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateTaskRequestWithBody(server, id, taskId, "application/json", bodyReader)
}

// NewUpdateTaskRequestWithBody generates requests for UpdateTask with any type of body
func NewUpdateTaskRequestWithBody(server string, id int64, taskId int64, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "taskId", runtime.ParamLocationPath, taskId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/jobs/%s/tasks/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListAllEventsWithResponse request
	ListAllEventsWithResponse(ctx context.Context, params *ListAllEventsParams, reqEditors ...RequestEditorFn) (*ListAllEventsResponse, error)

	// ListJobsWithResponse request
	ListJobsWithResponse(ctx context.Context, params *ListJobsParams, reqEditors ...RequestEditorFn) (*ListJobsResponse, error)

	// CreateJobWithBodyWithResponse request with any body
	CreateJobWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateJobResponse, error)

	CreateJobWithResponse(ctx context.Context, body CreateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateJobResponse, error)

	// DeleteJobWithResponse request
	DeleteJobWithResponse(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*DeleteJobResponse, error)

	// GetJobWithResponse request
	GetJobWithResponse(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*GetJobResponse, error)

	// UpdateJobWithBodyWithResponse request with any body
	UpdateJobWithBodyWithResponse(ctx context.Context, id int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateJobResponse, error)

	UpdateJobWithResponse(ctx context.Context, id int64, body UpdateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateJobResponse, error)

	// CancelJobWithResponse request
	CancelJobWithResponse(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*CancelJobResponse, error)

	// GetEventsWithResponse request
	GetEventsWithResponse(ctx context.Context, id int64, params *GetEventsParams, reqEditors ...RequestEditorFn) (*GetEventsResponse, error)

	// GetLogsWithResponse request
	GetLogsWithResponse(ctx context.Context, id int64, params *GetLogsParams, reqEditors ...RequestEditorFn) (*GetLogsResponse, error)

	// RetryJobWithResponse request
	RetryJobWithResponse(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*RetryJobResponse, error)

	// ListTasksWithResponse request
	ListTasksWithResponse(ctx context.Context, id int64, params *ListTasksParams, reqEditors ...RequestEditorFn) (*ListTasksResponse, error)

	// GetTaskWithResponse request
	GetTaskWithResponse(ctx context.Context, id int64, taskId int64, reqEditors ...RequestEditorFn) (*GetTaskResponse, error)

	// UpdateTaskWithBodyWithResponse request with any body
	UpdateTaskWithBodyWithResponse(ctx context.Context, id int64, taskId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateTaskResponse, error)

	UpdateTaskWithResponse(ctx context.Context, id int64, taskId int64, body UpdateTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateTaskResponse, error)
}

type ListAllEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EventsListExtended
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListAllEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAllEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListJobsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JobsList
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListJobsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListJobsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *JobCreated
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JobDetails
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JobDetails
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r UpdateJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CancelJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JobDetails
	JSON404      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CancelJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EventsList
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LogsList
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RetryJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JobDetails
	JSON404      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r RetryJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RetryJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListTasksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TasksList
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListTasksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListTasksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTaskResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Task
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetTaskResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTaskResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateTaskResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Task
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r UpdateTaskResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateTaskResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListAllEventsWithResponse request returning *ListAllEventsResponse
func (c *ClientWithResponses) ListAllEventsWithResponse(ctx context.Context, params *ListAllEventsParams, reqEditors ...RequestEditorFn) (*ListAllEventsResponse, error) {
	rsp, err := c.ListAllEvents(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAllEventsResponse(rsp)
}

// ListJobsWithResponse request returning *ListJobsResponse
func (c *ClientWithResponses) ListJobsWithResponse(ctx context.Context, params *ListJobsParams, reqEditors ...RequestEditorFn) (*ListJobsResponse, error) {
	rsp, err := c.ListJobs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListJobsResponse(rsp)
}

// CreateJobWithBodyWithResponse request with arbitrary body returning *CreateJobResponse
func (c *ClientWithResponses) CreateJobWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateJobResponse, error) {
	rsp, err := c.CreateJobWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateJobResponse(rsp)
}

func (c *ClientWithResponses) CreateJobWithResponse(ctx context.Context, body CreateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateJobResponse, error) {
	rsp, err := c.CreateJob(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateJobResponse(rsp)
}

// DeleteJobWithResponse request returning *DeleteJobResponse
func (c *ClientWithResponses) DeleteJobWithResponse(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*DeleteJobResponse, error) {
	rsp, err := c.DeleteJob(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteJobResponse(rsp)
}

// GetJobWithResponse request returning *GetJobResponse
func (c *ClientWithResponses) GetJobWithResponse(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*GetJobResponse, error) {
	rsp, err := c.GetJob(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetJobResponse(rsp)
}

// UpdateJobWithBodyWithResponse request with arbitrary body returning *UpdateJobResponse
func (c *ClientWithResponses) UpdateJobWithBodyWithResponse(ctx context.Context, id int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateJobResponse, error) {
	rsp, err := c.UpdateJobWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateJobResponse(rsp)
}

func (c *ClientWithResponses) UpdateJobWithResponse(ctx context.Context, id int64, body UpdateJobJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateJobResponse, error) {
	rsp, err := c.UpdateJob(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateJobResponse(rsp)
}

// CancelJobWithResponse request returning *CancelJobResponse
func (c *ClientWithResponses) CancelJobWithResponse(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*CancelJobResponse, error) {
	rsp, err := c.CancelJob(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelJobResponse(rsp)
}

// GetEventsWithResponse request returning *GetEventsResponse
func (c *ClientWithResponses) GetEventsWithResponse(ctx context.Context, id int64, params *GetEventsParams, reqEditors ...RequestEditorFn) (*GetEventsResponse, error) {
	rsp, err := c.GetEvents(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEventsResponse(rsp)
}

// GetLogsWithResponse request returning *GetLogsResponse
func (c *ClientWithResponses) GetLogsWithResponse(ctx context.Context, id int64, params *GetLogsParams, reqEditors ...RequestEditorFn) (*GetLogsResponse, error) {
	rsp, err := c.GetLogs(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetLogsResponse(rsp)
}

// RetryJobWithResponse request returning *RetryJobResponse
func (c *ClientWithResponses) RetryJobWithResponse(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*RetryJobResponse, error) {
	rsp, err := c.RetryJob(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRetryJobResponse(rsp)
}

// ListTasksWithResponse request returning *ListTasksResponse
func (c *ClientWithResponses) ListTasksWithResponse(ctx context.Context, id int64, params *ListTasksParams, reqEditors ...RequestEditorFn) (*ListTasksResponse, error) {
	rsp, err := c.ListTasks(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListTasksResponse(rsp)
}

// GetTaskWithResponse request returning *GetTaskResponse
func (c *ClientWithResponses) GetTaskWithResponse(ctx context.Context, id int64, taskId int64, reqEditors ...RequestEditorFn) (*GetTaskResponse, error) {
	rsp, err := c.GetTask(ctx, id, taskId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTaskResponse(rsp)
}

// UpdateTaskWithBodyWithResponse request with arbitrary body returning *UpdateTaskResponse
func (c *ClientWithResponses) UpdateTaskWithBodyWithResponse(ctx context.Context, id int64, taskId int64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateTaskResponse, error) {
	rsp, err := c.UpdateTaskWithBody(ctx, id, taskId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateTaskResponse(rsp)
}

func (c *ClientWithResponses) UpdateTaskWithResponse(ctx context.Context, id int64, taskId int64, body UpdateTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateTaskResponse, error) {
	rsp, err := c.UpdateTask(ctx, id, taskId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateTaskResponse(rsp)
}

// ParseListAllEventsResponse parses an HTTP response from a ListAllEventsWithResponse call
func ParseListAllEventsResponse(rsp *http.Response) (*ListAllEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAllEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventsListExtended
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListJobsResponse parses an HTTP response from a ListJobsWithResponse call
func ParseListJobsResponse(rsp *http.Response) (*ListJobsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListJobsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JobsList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateJobResponse parses an HTTP response from a CreateJobWithResponse call
func ParseCreateJobResponse(rsp *http.Response) (*CreateJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest JobCreated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteJobResponse parses an HTTP response from a DeleteJobWithResponse call
func ParseDeleteJobResponse(rsp *http.Response) (*DeleteJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetJobResponse parses an HTTP response from a GetJobWithResponse call
func ParseGetJobResponse(rsp *http.Response) (*GetJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JobDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseUpdateJobResponse parses an HTTP response from a UpdateJobWithResponse call
func ParseUpdateJobResponse(rsp *http.Response) (*UpdateJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JobDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCancelJobResponse parses an HTTP response from a CancelJobWithResponse call
func ParseCancelJobResponse(rsp *http.Response) (*CancelJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JobDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetEventsResponse parses an HTTP response from a GetEventsWithResponse call
func ParseGetEventsResponse(rsp *http.Response) (*GetEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventsList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetLogsResponse parses an HTTP response from a GetLogsWithResponse call
func ParseGetLogsResponse(rsp *http.Response) (*GetLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LogsList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRetryJobResponse parses an HTTP response from a RetryJobWithResponse call
func ParseRetryJobResponse(rsp *http.Response) (*RetryJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RetryJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JobDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListTasksResponse parses an HTTP response from a ListTasksWithResponse call
func ParseListTasksResponse(rsp *http.Response) (*ListTasksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListTasksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TasksList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetTaskResponse parses an HTTP response from a GetTaskWithResponse call
func ParseGetTaskResponse(rsp *http.Response) (*GetTaskResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTaskResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Task
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseUpdateTaskResponse parses an HTTP response from a UpdateTaskWithResponse call
func ParseUpdateTaskResponse(rsp *http.Response) (*UpdateTaskResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateTaskResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Task
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
