// Code generated by go-swagger; DO NOT EDIT.

package jobs

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.corp.mail.ru/ai/streamflow/backend/cplane/tests/private/models"
)

// GetAPIV1JobEventsReader is a Reader for the GetAPIV1JobEvents structure.
type GetAPIV1JobEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1JobEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1JobEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1JobEventsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAPIV1JobEventsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV1JobEventsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1JobEventsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetAPIV1JobEventsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/job/events] GetAPIV1JobEvents", response, response.Code())
	}
}

// NewGetAPIV1JobEventsOK creates a GetAPIV1JobEventsOK with default headers values
func NewGetAPIV1JobEventsOK() *GetAPIV1JobEventsOK {
	return &GetAPIV1JobEventsOK{}
}

/*
GetAPIV1JobEventsOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1JobEventsOK struct {
	Payload *models.ClientsListEventsResponse
}

// IsSuccess returns true when this get Api v1 job events o k response has a 2xx status code
func (o *GetAPIV1JobEventsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 job events o k response has a 3xx status code
func (o *GetAPIV1JobEventsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 job events o k response has a 4xx status code
func (o *GetAPIV1JobEventsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 job events o k response has a 5xx status code
func (o *GetAPIV1JobEventsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 job events o k response a status code equal to that given
func (o *GetAPIV1JobEventsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 job events o k response
func (o *GetAPIV1JobEventsOK) Code() int {
	return 200
}

func (o *GetAPIV1JobEventsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job/events][%d] getApiV1JobEventsOK %s", 200, payload)
}

func (o *GetAPIV1JobEventsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job/events][%d] getApiV1JobEventsOK %s", 200, payload)
}

func (o *GetAPIV1JobEventsOK) GetPayload() *models.ClientsListEventsResponse {
	return o.Payload
}

func (o *GetAPIV1JobEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClientsListEventsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1JobEventsBadRequest creates a GetAPIV1JobEventsBadRequest with default headers values
func NewGetAPIV1JobEventsBadRequest() *GetAPIV1JobEventsBadRequest {
	return &GetAPIV1JobEventsBadRequest{}
}

/*
GetAPIV1JobEventsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAPIV1JobEventsBadRequest struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 job events bad request response has a 2xx status code
func (o *GetAPIV1JobEventsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 job events bad request response has a 3xx status code
func (o *GetAPIV1JobEventsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 job events bad request response has a 4xx status code
func (o *GetAPIV1JobEventsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 job events bad request response has a 5xx status code
func (o *GetAPIV1JobEventsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 job events bad request response a status code equal to that given
func (o *GetAPIV1JobEventsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v1 job events bad request response
func (o *GetAPIV1JobEventsBadRequest) Code() int {
	return 400
}

func (o *GetAPIV1JobEventsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job/events][%d] getApiV1JobEventsBadRequest %s", 400, payload)
}

func (o *GetAPIV1JobEventsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job/events][%d] getApiV1JobEventsBadRequest %s", 400, payload)
}

func (o *GetAPIV1JobEventsBadRequest) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1JobEventsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1JobEventsUnauthorized creates a GetAPIV1JobEventsUnauthorized with default headers values
func NewGetAPIV1JobEventsUnauthorized() *GetAPIV1JobEventsUnauthorized {
	return &GetAPIV1JobEventsUnauthorized{}
}

/*
GetAPIV1JobEventsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAPIV1JobEventsUnauthorized struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 job events unauthorized response has a 2xx status code
func (o *GetAPIV1JobEventsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 job events unauthorized response has a 3xx status code
func (o *GetAPIV1JobEventsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 job events unauthorized response has a 4xx status code
func (o *GetAPIV1JobEventsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 job events unauthorized response has a 5xx status code
func (o *GetAPIV1JobEventsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 job events unauthorized response a status code equal to that given
func (o *GetAPIV1JobEventsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v1 job events unauthorized response
func (o *GetAPIV1JobEventsUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV1JobEventsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job/events][%d] getApiV1JobEventsUnauthorized %s", 401, payload)
}

func (o *GetAPIV1JobEventsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job/events][%d] getApiV1JobEventsUnauthorized %s", 401, payload)
}

func (o *GetAPIV1JobEventsUnauthorized) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1JobEventsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1JobEventsNotFound creates a GetAPIV1JobEventsNotFound with default headers values
func NewGetAPIV1JobEventsNotFound() *GetAPIV1JobEventsNotFound {
	return &GetAPIV1JobEventsNotFound{}
}

/*
GetAPIV1JobEventsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAPIV1JobEventsNotFound struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 job events not found response has a 2xx status code
func (o *GetAPIV1JobEventsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 job events not found response has a 3xx status code
func (o *GetAPIV1JobEventsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 job events not found response has a 4xx status code
func (o *GetAPIV1JobEventsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 job events not found response has a 5xx status code
func (o *GetAPIV1JobEventsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 job events not found response a status code equal to that given
func (o *GetAPIV1JobEventsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v1 job events not found response
func (o *GetAPIV1JobEventsNotFound) Code() int {
	return 404
}

func (o *GetAPIV1JobEventsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job/events][%d] getApiV1JobEventsNotFound %s", 404, payload)
}

func (o *GetAPIV1JobEventsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job/events][%d] getApiV1JobEventsNotFound %s", 404, payload)
}

func (o *GetAPIV1JobEventsNotFound) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1JobEventsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1JobEventsInternalServerError creates a GetAPIV1JobEventsInternalServerError with default headers values
func NewGetAPIV1JobEventsInternalServerError() *GetAPIV1JobEventsInternalServerError {
	return &GetAPIV1JobEventsInternalServerError{}
}

/*
GetAPIV1JobEventsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetAPIV1JobEventsInternalServerError struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 job events internal server error response has a 2xx status code
func (o *GetAPIV1JobEventsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 job events internal server error response has a 3xx status code
func (o *GetAPIV1JobEventsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 job events internal server error response has a 4xx status code
func (o *GetAPIV1JobEventsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 job events internal server error response has a 5xx status code
func (o *GetAPIV1JobEventsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 job events internal server error response a status code equal to that given
func (o *GetAPIV1JobEventsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 job events internal server error response
func (o *GetAPIV1JobEventsInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1JobEventsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job/events][%d] getApiV1JobEventsInternalServerError %s", 500, payload)
}

func (o *GetAPIV1JobEventsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job/events][%d] getApiV1JobEventsInternalServerError %s", 500, payload)
}

func (o *GetAPIV1JobEventsInternalServerError) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1JobEventsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1JobEventsServiceUnavailable creates a GetAPIV1JobEventsServiceUnavailable with default headers values
func NewGetAPIV1JobEventsServiceUnavailable() *GetAPIV1JobEventsServiceUnavailable {
	return &GetAPIV1JobEventsServiceUnavailable{}
}

/*
GetAPIV1JobEventsServiceUnavailable describes a response with status code 503, with default header values.

Service Unavailable
*/
type GetAPIV1JobEventsServiceUnavailable struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 job events service unavailable response has a 2xx status code
func (o *GetAPIV1JobEventsServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 job events service unavailable response has a 3xx status code
func (o *GetAPIV1JobEventsServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 job events service unavailable response has a 4xx status code
func (o *GetAPIV1JobEventsServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 job events service unavailable response has a 5xx status code
func (o *GetAPIV1JobEventsServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 job events service unavailable response a status code equal to that given
func (o *GetAPIV1JobEventsServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the get Api v1 job events service unavailable response
func (o *GetAPIV1JobEventsServiceUnavailable) Code() int {
	return 503
}

func (o *GetAPIV1JobEventsServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job/events][%d] getApiV1JobEventsServiceUnavailable %s", 503, payload)
}

func (o *GetAPIV1JobEventsServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job/events][%d] getApiV1JobEventsServiceUnavailable %s", 503, payload)
}

func (o *GetAPIV1JobEventsServiceUnavailable) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1JobEventsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
