// Code generated by go-swagger; DO NOT EDIT.

package jobs

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.corp.mail.ru/ai/streamflow/backend/cplane/tests/private/models"
)

// GetAPIV1JobReader is a Reader for the GetAPIV1Job structure.
type GetAPIV1JobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1JobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1JobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1JobBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAPIV1JobUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV1JobNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1JobInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetAPIV1JobServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/job] GetAPIV1Job", response, response.Code())
	}
}

// NewGetAPIV1JobOK creates a GetAPIV1JobOK with default headers values
func NewGetAPIV1JobOK() *GetAPIV1JobOK {
	return &GetAPIV1JobOK{}
}

/*
GetAPIV1JobOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1JobOK struct {
	Payload *models.ClientsGetJobResponse
}

// IsSuccess returns true when this get Api v1 job o k response has a 2xx status code
func (o *GetAPIV1JobOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 job o k response has a 3xx status code
func (o *GetAPIV1JobOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 job o k response has a 4xx status code
func (o *GetAPIV1JobOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 job o k response has a 5xx status code
func (o *GetAPIV1JobOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 job o k response a status code equal to that given
func (o *GetAPIV1JobOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 job o k response
func (o *GetAPIV1JobOK) Code() int {
	return 200
}

func (o *GetAPIV1JobOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job][%d] getApiV1JobOK %s", 200, payload)
}

func (o *GetAPIV1JobOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job][%d] getApiV1JobOK %s", 200, payload)
}

func (o *GetAPIV1JobOK) GetPayload() *models.ClientsGetJobResponse {
	return o.Payload
}

func (o *GetAPIV1JobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClientsGetJobResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1JobBadRequest creates a GetAPIV1JobBadRequest with default headers values
func NewGetAPIV1JobBadRequest() *GetAPIV1JobBadRequest {
	return &GetAPIV1JobBadRequest{}
}

/*
GetAPIV1JobBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAPIV1JobBadRequest struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 job bad request response has a 2xx status code
func (o *GetAPIV1JobBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 job bad request response has a 3xx status code
func (o *GetAPIV1JobBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 job bad request response has a 4xx status code
func (o *GetAPIV1JobBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 job bad request response has a 5xx status code
func (o *GetAPIV1JobBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 job bad request response a status code equal to that given
func (o *GetAPIV1JobBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v1 job bad request response
func (o *GetAPIV1JobBadRequest) Code() int {
	return 400
}

func (o *GetAPIV1JobBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job][%d] getApiV1JobBadRequest %s", 400, payload)
}

func (o *GetAPIV1JobBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job][%d] getApiV1JobBadRequest %s", 400, payload)
}

func (o *GetAPIV1JobBadRequest) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1JobBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1JobUnauthorized creates a GetAPIV1JobUnauthorized with default headers values
func NewGetAPIV1JobUnauthorized() *GetAPIV1JobUnauthorized {
	return &GetAPIV1JobUnauthorized{}
}

/*
GetAPIV1JobUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAPIV1JobUnauthorized struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 job unauthorized response has a 2xx status code
func (o *GetAPIV1JobUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 job unauthorized response has a 3xx status code
func (o *GetAPIV1JobUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 job unauthorized response has a 4xx status code
func (o *GetAPIV1JobUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 job unauthorized response has a 5xx status code
func (o *GetAPIV1JobUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 job unauthorized response a status code equal to that given
func (o *GetAPIV1JobUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v1 job unauthorized response
func (o *GetAPIV1JobUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV1JobUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job][%d] getApiV1JobUnauthorized %s", 401, payload)
}

func (o *GetAPIV1JobUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job][%d] getApiV1JobUnauthorized %s", 401, payload)
}

func (o *GetAPIV1JobUnauthorized) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1JobUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1JobNotFound creates a GetAPIV1JobNotFound with default headers values
func NewGetAPIV1JobNotFound() *GetAPIV1JobNotFound {
	return &GetAPIV1JobNotFound{}
}

/*
GetAPIV1JobNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAPIV1JobNotFound struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 job not found response has a 2xx status code
func (o *GetAPIV1JobNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 job not found response has a 3xx status code
func (o *GetAPIV1JobNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 job not found response has a 4xx status code
func (o *GetAPIV1JobNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 job not found response has a 5xx status code
func (o *GetAPIV1JobNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 job not found response a status code equal to that given
func (o *GetAPIV1JobNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v1 job not found response
func (o *GetAPIV1JobNotFound) Code() int {
	return 404
}

func (o *GetAPIV1JobNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job][%d] getApiV1JobNotFound %s", 404, payload)
}

func (o *GetAPIV1JobNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job][%d] getApiV1JobNotFound %s", 404, payload)
}

func (o *GetAPIV1JobNotFound) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1JobNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1JobInternalServerError creates a GetAPIV1JobInternalServerError with default headers values
func NewGetAPIV1JobInternalServerError() *GetAPIV1JobInternalServerError {
	return &GetAPIV1JobInternalServerError{}
}

/*
GetAPIV1JobInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetAPIV1JobInternalServerError struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 job internal server error response has a 2xx status code
func (o *GetAPIV1JobInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 job internal server error response has a 3xx status code
func (o *GetAPIV1JobInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 job internal server error response has a 4xx status code
func (o *GetAPIV1JobInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 job internal server error response has a 5xx status code
func (o *GetAPIV1JobInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 job internal server error response a status code equal to that given
func (o *GetAPIV1JobInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 job internal server error response
func (o *GetAPIV1JobInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1JobInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job][%d] getApiV1JobInternalServerError %s", 500, payload)
}

func (o *GetAPIV1JobInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job][%d] getApiV1JobInternalServerError %s", 500, payload)
}

func (o *GetAPIV1JobInternalServerError) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1JobInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1JobServiceUnavailable creates a GetAPIV1JobServiceUnavailable with default headers values
func NewGetAPIV1JobServiceUnavailable() *GetAPIV1JobServiceUnavailable {
	return &GetAPIV1JobServiceUnavailable{}
}

/*
GetAPIV1JobServiceUnavailable describes a response with status code 503, with default header values.

Service Unavailable
*/
type GetAPIV1JobServiceUnavailable struct {
	Payload *models.ResponsesErrorResponse
}

// IsSuccess returns true when this get Api v1 job service unavailable response has a 2xx status code
func (o *GetAPIV1JobServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 job service unavailable response has a 3xx status code
func (o *GetAPIV1JobServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 job service unavailable response has a 4xx status code
func (o *GetAPIV1JobServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 job service unavailable response has a 5xx status code
func (o *GetAPIV1JobServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 job service unavailable response a status code equal to that given
func (o *GetAPIV1JobServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the get Api v1 job service unavailable response
func (o *GetAPIV1JobServiceUnavailable) Code() int {
	return 503
}

func (o *GetAPIV1JobServiceUnavailable) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job][%d] getApiV1JobServiceUnavailable %s", 503, payload)
}

func (o *GetAPIV1JobServiceUnavailable) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/job][%d] getApiV1JobServiceUnavailable %s", 503, payload)
}

func (o *GetAPIV1JobServiceUnavailable) GetPayload() *models.ResponsesErrorResponse {
	return o.Payload
}

func (o *GetAPIV1JobServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
