// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"gitlab.corp.mail.ru/ai/streamflow/backend/cplane/tests/private/models"
)

// NewPostAPIV1RoleParams creates a new PostAPIV1RoleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1RoleParams() *PostAPIV1RoleParams {
	return &PostAPIV1RoleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1RoleParamsWithTimeout creates a new PostAPIV1RoleParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1RoleParamsWithTimeout(timeout time.Duration) *PostAPIV1RoleParams {
	return &PostAPIV1RoleParams{
		timeout: timeout,
	}
}

// NewPostAPIV1RoleParamsWithContext creates a new PostAPIV1RoleParams object
// with the ability to set a context for a request.
func NewPostAPIV1RoleParamsWithContext(ctx context.Context) *PostAPIV1RoleParams {
	return &PostAPIV1RoleParams{
		Context: ctx,
	}
}

// NewPostAPIV1RoleParamsWithHTTPClient creates a new PostAPIV1RoleParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1RoleParamsWithHTTPClient(client *http.Client) *PostAPIV1RoleParams {
	return &PostAPIV1RoleParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1RoleParams contains all the parameters to send to the API endpoint

	for the post API v1 role operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1RoleParams struct {

	/* Request.

	   request body
	*/
	Request *models.RequestsCreateRoleRequest

	/* XSuperuserToken.

	   superuser token
	*/
	XSuperuserToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1RoleParams) WithDefaults() *PostAPIV1RoleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 role params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1RoleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 role params
func (o *PostAPIV1RoleParams) WithTimeout(timeout time.Duration) *PostAPIV1RoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 role params
func (o *PostAPIV1RoleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 role params
func (o *PostAPIV1RoleParams) WithContext(ctx context.Context) *PostAPIV1RoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 role params
func (o *PostAPIV1RoleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 role params
func (o *PostAPIV1RoleParams) WithHTTPClient(client *http.Client) *PostAPIV1RoleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 role params
func (o *PostAPIV1RoleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post API v1 role params
func (o *PostAPIV1RoleParams) WithRequest(request *models.RequestsCreateRoleRequest) *PostAPIV1RoleParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post API v1 role params
func (o *PostAPIV1RoleParams) SetRequest(request *models.RequestsCreateRoleRequest) {
	o.Request = request
}

// WithXSuperuserToken adds the xSuperuserToken to the post API v1 role params
func (o *PostAPIV1RoleParams) WithXSuperuserToken(xSuperuserToken *string) *PostAPIV1RoleParams {
	o.SetXSuperuserToken(xSuperuserToken)
	return o
}

// SetXSuperuserToken adds the xSuperuserToken to the post API v1 role params
func (o *PostAPIV1RoleParams) SetXSuperuserToken(xSuperuserToken *string) {
	o.XSuperuserToken = xSuperuserToken
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1RoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if o.XSuperuserToken != nil {

		// header param x-superuser-token
		if err := r.SetHeaderParam("x-superuser-token", *o.XSuperuserToken); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
